[[message]]
key = 'TUTORIAL_CATEGORY_17'
old = '覚者の基本'
new = 'The Arisen'
[[message]]
key = 'TUTORIAL_CATEGORY_8'
old = '冒険の基礎知識'
new = 'Adventuring Basics'
[[message]]
key = 'TUTORIAL_CATEGORY_15'
old = 'ジョブの操作と役割'
new = 'Job Roles'
[[message]]
key = 'TUTORIAL_CATEGORY_3'
old = 'クエストのルール'
new = 'About Quests'
[[message]]
key = 'TUTORIAL_CATEGORY_12'
old = '施設と拠点'
new = 'Establishments and Locations'
[[message]]
key = 'TUTORIAL_CATEGORY_4'
old = '便利なシステム機能'
new = 'Menu Functions'
[[message]]
key = 'TUTORIAL_CATEGORY_18'
old = 'ポーンの基本'
new = 'Pawns'
[[message]]
key = 'TUTORIAL_CATEGORY_19'
old = 'クラフト手引き'
new = 'Crafting Basics'
[[message]]
key = 'TUTORIAL_CATEGORY_20'
old = 'コンテンツ紹介'
new = 'Dungeons'
[[message]]
key = 'TUTORIAL_CATEGORY_21'
old = 'シナリオ進行'
new = 'Scenarios'
[[message]]
key = 'TUTORIAL_CATEGORY_22'
old = 'サブストーリー'
new = 'Substories'
[[message]]
key = 'TUTORIAL_CATEGORY_23'
old = '黒呪の迷宮'
new = 'Bitterblack Maze'
[[message]]
key = 'TUTORIAL_CATEGORY_24'
old = '暗黒の大竜晶破壊戦'
[[message]]
key = 'TUTORIAL_CATEGORY_25'
old = 'ドラゴンアビリティ'
new = 'Dragon Abilities'
