[[message]]
old = 'レバーがある'
new = 'There is a lever'
[[message]]
old = '引きますか'
new = 'Pull the lever?'
[[message]]
old = '引く'
new = 'Pull'
[[message]]
old = '引かない'
new = "Don't Pull"
[[message]]
old = '扉には鍵がかかっている――'
new = 'The door is locked'
[[message]]
old = '鍵を使いますか'
new = 'Use the key?'
[[message]]
old = '使う'
new = 'Use'
[[message]]
old = '使わない'
new = "Don't Use"
[[message]]
old = 'エリアマスターにより封鎖されている――'
new = 'It is blocked by the Area Master.'
[[message]]
old = '''
鍵がかかっている――
開くには<COL ffdc78>《<NAME ITEM>》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"<NAME ITEM>"</COL> is needed to open.'''
[[message]]
old = 'こちら側からは開かないようだ'
new = 'It cannot open from this side.'
[[message]]
old = '不思議な力で封印されている'
new = 'It is sealed with a mysterious force.'
[[message]]
old = '何かが引っ掛かって開かない'
new = 'It seems to be caught on something.'
[[message]]
old = '厳重に封印されている――'
new = 'It has been strongly sealed.'
[[message]]
old = '文字はかすれていて読めない'
new = 'The characters are faint and cannot be read.'
[[message]]
old = 'すでに息絶えている――'
new = 'Out of breath...'
[[message]]
old = '特に気になるものはない'
new = 'Nothing of intrest here.'
[[message]]
old = '何か仕掛けがあるようだ'
new = 'Something feels off here.'
[[message]]
old = '''
この先は他の覚者とパーティーを組んだ
状態では進入できません'''
new = '''
You cannot enter alone.
Make a party with other Arisen.'''
[[message]]
old = '''
一人、またはポーンのみを連れて
訪れてください'''
new = '''
Please take only one
person or pawn.'''
[[message]]
old = '行き先選択'
new = 'Select Destination'
[[message]]
old = '各ステージ名'
new = 'Name of each stage'
[[message]]
old = 'やめる'
new = 'Quit'
[[message]]
old = '準備完了！　進行マーカーに触れてください'
new = 'Ready! Please touch the progress marker.'
[[message]]
old = '準備完了！　待機してください'
new = 'Ready! Please wait.'
[[message]]
old = '''
パーティー全員が集合するまで
サークル内で待機してください'''
new = '''
Please wait in the circle until
the entire party is ready, '''
[[message]]
old = 'リーダーが進行準備・パーティー招集を行いました'
new = 'Leader has begun a progress preparation.'
[[message]]
old = '''
パーティー全員が集まり、準備完了したら
進行マーカーに触れてください'''
new = '''
Gather the party if you are ready.
Please touch the progress marker.'''
[[message]]
old = '''
イベントを進行しますか？
※パーティー要請中の場合はキャンセルされます'''
new = '''
Are you sure you want to proceed with
the event?
※ If there is a party request, it will be
canceled.'''
[[message]]
old = '準備開始（パーティー招集）'
new = 'Prepare (begin gathering party)'
[[message]]
old = 'キャンセル'
new = 'Cancel'
[[message]]
old = 'イベント進行はリーダーのみ可能です'
new = 'Only the party leader can progress the event.'
[[message]]
old = 'イベント進行確認'
new = 'Confirm Event Progress'
[[message]]
old = '進行する'
new = 'Proceed'
[[message]]
old = 'キャンセル'
new = 'Cancel'
[[message]]
old = '''
イベント進行待機に入ります
準備はよろしいですか？'''
new = '''
You will begin waiting to progress the event.
Are you sure you are ready?'''
[[message]]
old = 'はい'
new = 'Yes'
[[message]]
old = 'いいえ'
new = 'No'
[[message]]
old = '待機を解除しますか？'
new = 'Are you sure you want to cancel waiting?'
[[message]]
old = 'はい'
new = 'Yes'
[[message]]
old = 'いいえ'
new = 'No'
[[message]]
old = '''
メンバーが集合するまで
サークル内で待機してください'''
new = '''
Until the party members are ready, 
please wait in the circle.'''
[[message]]
old = 'イベント進行確認'
new = 'Confirm Event Progress'
[[message]]
old = '進行する'
new = 'Proceed'
[[message]]
old = '準備解除（パーティー招集中止）'
new = 'Disband (stop gathering party)'
[[message]]
old = 'キャンセル'
new = 'Cancel'
[[message]]
old = 'イベント進行確認'
new = 'Confirm Event Progress'
[[message]]
old = '準備完了、待機'
new = 'Ready and waiting.'
[[message]]
old = '準備解除（パーティー招集中止）'
new = 'Disband (stop gathering party)'
[[message]]
old = 'キャンセル'
new = 'Cancel'
[[message]]
old = '''
イベント進行確認
（全メンバーの準備完了を待ちます）'''
new = '''
Confirm Event Progress
(Wait for all party members to be ready)'''
[[message]]
old = '準備解除（パーティー招集中止）'
new = 'Disband (stop gathering party)'
[[message]]
old = 'キャンセル'
new = 'Cancel'
[[message]]
old = '''
門のような意匠がある
わずかに不思議な気配を感じる――'''
new = '''
It seems to have a design similar to a gate.
It makes you feel slightly strange...'''
[[message]]
old = '''
――扉は閉ざされている――
メンバー全員が集まらなければ
この先へは進めません
メンバーを招集しますか？'''
new = '''
The door is closed.
You can proceed ahead if you gather the party.
Do you want to begin gathering party?'''
[[message]]
old = 'はい'
new = 'Yes'
[[message]]
old = 'いいえ'
new = 'No'
[[message]]
old = '''
――扉は閉ざされている――
リーダーアクションがなければ
この先へは進めません'''
new = '''
The door is closed.
Cannot proceed ahead without the leader.'''
[[message]]
old = '''
扉を開き先へ向かいますか？
（全メンバーが準備完了しました）'''
new = '''
Do you want to go through the door?
(Party Ready)'''
[[message]]
old = 'はい'
new = 'Yes'
[[message]]
old = 'いいえ（パーティー招集中止）'
new = 'No (stop gathering party)'
[[message]]
old = '''
鍵を使用して扉を開きますか？
（全メンバーが準備完了しました）'''
new = '''
Do you want to open the door using the key?
(Party Ready)'''
[[message]]
old = 'はい'
new = 'Yes'
[[message]]
old = 'いいえ'
new = 'No'
[[message]]
old = '''
扉は固く閉ざされており
開きそうにない'''
new = '''
The door is firmly shut.
Unlikely to be opened.'''
[[message]]
old = '''
特定のコンテンツ中は
この先に移動できません'''
[[message]]
old = '残り時間が追加されました'
new = 'Remaining time added'
[[message]]
old = '''
鍵がかかっている――
開くには<COL ffdc78>《未来の装飾鍵》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"未来の装飾鍵"</COL> is needed to open.'''
[[message]]
old = '''
鍵がかかっている――
開くには<COL ffdc78>《竜力の鍵》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"Key of Dragon Force"</COL> is needed to open.'''
[[message]]
old = '''
鍵がかかっている――
開くには<COL ffdc78>《昌石の鍵》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"Key of Gemstones"</COL> is needed to open.'''
[[message]]
old = '''
鍵がかかっている――
開くには<COL ffdc78>《財宝の鍵》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"Key of Treasures"</COL> is needed to open.'''
[[message]]
old = '''
鍵がかかっている――
開くには<COL ffdc78>《宝飾の鍵》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"Key of Jewelry"</COL> is needed to open.'''
[[message]]
old = '白竜杯に参加可能になりました'
new = 'You can now participate in the White Dragon Cup.'
[[message]]
old = '''
鍵がかかっている――
解放には<COL ffdc78>《宝飾の鍵》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"Key of Jewelry"</COL> is needed to release.'''
[[message]]
old = '''
<COL ffdc78>敵との戦闘で一度も死亡状態になりませんでした
クリア時のボーナス報酬が多くなります</COL>'''
[[message]]
old = '''
<COL ffdc78>パーティーメンバーが死亡状態になりました
クリア時のボーナス報酬が下がります</COL>'''
[[message]]
old = '''
<COL ffdc78>胞子の広がりを阻止――！
クリア時のボーナス報酬が追加されます</COL>'''
[[message]]
old = '敵はあわてて逃げ出した！'
new = 'The enemy panicked and ran away!'
[[message]]
old = '胞子が集まり始めている――'
new = 'Spores are starting to gather'
[[message]]
old = '汚染植物が出現――！'
new = 'Infected plants have appeared!'
[[message]]
old = '''
胞子の広がりを阻止――
クリア時のボーナス報酬が追加！'''
new = '''
Prevent the spread of spores!
Bonus reward is added!'''
[[message]]
old = '隠れていた魔物が姿を現した――！'
new = 'The hidden monster has appeared!'
[[message]]
old = '''
傷ついた魔物の痕跡は、
住処へと続いているようだ――'''
new = '''
There are traces from the wounded monster
It seems to lead towards its den.'''
[[message]]
old = '救助対象が疲れてきたようだ――'
new = 'Your rescue target seems to be getting tired...'
[[message]]
old = '救助対象はかなり辛そうだ――'
new = 'Your rescue target seems to be struggling...'
[[message]]
old = '救助対象が戦線離脱した――'
new = 'Your rescue target has left the battlefield...'
[[message]]
old = '''
<COL ffdc78>迅速な救助に成功しました
クリア時のボーナス報酬が追加されます</COL>'''
new = '''
<COL ffdc78>Quick Rescue successful!
Bonus Rewards gained!</COL>'''
[[message]]
old = '''
<COL ffdc78>迅速な救助に失敗しました
クリア時のボーナス報酬は追加されません</COL>'''
new = '''
<COL ffdc78>Quick Rescue has failed!
Bonus Rewards are lost.</COL>'''
[[message]]
old = '''
鍵がかかっている――
開くには<COL ffdc78>《<NAME ITEM>》</COL>が必要だ'''
new = '''
It is locked.
<COL ffdc78>"<NAME ITEM>"</COL> is needed to open.'''
[[message]]
old = '今は転移の力を失っているようだ――'
new = 'It seems to have lost the power to teleport...'
[[message]]
old = '''
イベントを進行しますか？
※パーティー要請中の場合はキャンセルされます'''
new = '''
Are you sure you want to proceed with
the event?
※ If there is a party request, it will be
canceled.'''
[[message]]
old = '準備開始'
new = 'Start Preparation'
[[message]]
old = 'キャンセル'
new = 'Cancel'
[[message]]
old = 'イベント進行確認'
new = 'Confirm Event Progress'
[[message]]
old = '進行する'
new = 'Proceed'
[[message]]
old = '準備解除'
new = 'Cancel Preparation'
[[message]]
old = 'キャンセル'
new = 'Cancel'
[[message]]
old = '新たな証拠品を手に入れた！'
new = 'Got a new piece of evidence!'
[[message]]
old = '誰かの話し声が聞こえる――'
new = "Someone's voice can be heard――"
[[message]]
old = '憲兵が見張っている――この先には行けなさそうだ'
[[message]]
old = '誰かが襲われている！　助けなければ――'
[[message]]
old = '遠くから悲鳴が聞こえた――'
[[message]]
old = 'どこからか剣戟の音が聞こえる――'
[[message]]
old = 'レジスタンスに新たな仲間が加わった！'
new = 'A new friend joins the resistance!'
[[message]]
old = '諜報活動領域外へ移動したため、クエストを終了しました'
[[message]]
old = '諜報任務が進行した――'
[[message]]
old = 'ハントターゲットを討伐した！'
new = 'Hunt target subjugated!'
[[message]]
old = 'ボーナスターゲットを討伐した！'
new = 'Bonus target subjugated!'
[[message]]
old = '闇の力によって封じられている'
[[message]]
old = 'ハントターゲットを発見した！'
new = 'Hunt target found!'
[[message]]
old = 'ボーナスターゲットを発見した！'
new = 'Bonus target found!'
[[message]]
old = '封鎖されたエリアが解放された――'
[[message]]
old = '''
メインクエストが進行可能になりました
一度パーティーを解散してからトラバースに話しかけて下さい'''
