[[message]]
key = 'NORMAL_SKILL_NAME_08_113'
old = '<PADM>闘波の構え<KEYM>構えの変更（闘波の構え）'
new = '<PADM>Seeker Stance<KEYM>Change Stance (Seeker Stance)'
[[message]]
key = 'NORMAL_SKILL_NAME_08_114'
old = '闘波の魔眼'
new = 'Magick Eye: Seeker'
[[message]]
key = 'NORMAL_SKILL_NAME_08_115'
old = '闘波の矢'
new = 'Seeker Arrow'
[[message]]
key = 'NORMAL_SKILL_NAME_08_116'
old = '闘波の集中'
new = 'Concentration: Seeker'
[[message]]
key = 'NORMAL_SKILL_NAME_08_117'
old = '<PADM>助真の構え<KEYM>構えの変更（助真の構え）'
new = '<PADM>True Aid Stance<KEYM>Change Stance (True Aid Stance)'
[[message]]
key = 'NORMAL_SKILL_NAME_08_118'
old = '助真の魔眼'
new = 'Magick Eye: True Aid'
[[message]]
key = 'NORMAL_SKILL_NAME_08_119'
old = '助真の矢'
new = 'True Aid Arrow'
[[message]]
key = 'NORMAL_SKILL_NAME_08_120'
old = '助真の集中'
new = 'Concentration: True Aid'
[[message]]
key = 'NORMAL_SKILL_NAME_08_121'
old = '前蹴り'
new = 'Front Kick'
[[message]]
key = 'NORMAL_SKILL_NAME_08_122'
old = '癒しの装'
new = 'Healing Shroud'
[[message]]
key = 'NORMAL_SKILL_NAME_08_123'
old = '狙いの神眼'
new = "God's Eye: Aim"
[[message]]
key = 'NORMAL_SKILL_NAME_08_135'
old = '奮わせ直魔矢'
new = 'Invigorating Magick Arrow'
[[message]]
key = 'NORMAL_SKILL_NAME_08_178'
old = '魔眼転移'
