[[message]]
key = 'NORMAL_SKILL_COMMAND_08_113'
old = '<PADM><KC WEAPON_SUB>を押す<KEYM><KC HOLD_BOW>を押して構えてから<ICON MOUSE_WHL_4>で構え切替（初期設定の場合）'
new = '''
<PADM>Press <KC WEAPON_SUB>.<KEYM>Press and hold <KC HOLD_BOW>, then <ICON MOUSE_WHL_4> (default setting)
to switch stance.'''
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_114'
old = '<PADM><KC WEAPON_SUB>を押しながら右スティックを倒す<KEYM>闘波の構え中にマウス移動'
new = '<PADM>Press and hold <KC WEAPON_SUB>, then move the right stick<KEYM>During Seeker Stance, move the mouse</KEYM>.'
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_115'
old = '闘波の構え中に<KC SHOOT>を押す'
new = 'During Seeker Stance, press <KC SHOOT>.'
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_116'
old = '敵を狙って集中しジャストタイミングで矢を放つ'
new = '''
Focus concentration on enemies and fire arrows
with perfect timing.'''
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_117'
old = '<PADM><KC WEAPON_MAIN>を押す<KEYM><KC HOLD_BOW>を押して構えてから<ICON MOUSE_WHL_4>で構え切替（初期設定の場合）'
new = '''
<PADM>Press <KC WEAPON_MAIN>.<KEYM>Press and hold <KC HOLD_BOW>, then <ICON MOUSE_WHL_4> (default setting)
to switch stance.'''
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_118'
old = '<PADM><KC WEAPON_MAIN>を押しながら右スティックを倒す<KEYM>助真の構え中にマウス移動'
new = '<PADM>Press and hold <KC WEAPON_MAIN>, then move the right stick<KEYM>During True Aid Stance, move the mouse</KEYM>.'
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_119'
old = '助真の構え中に<KC SHOOT>を押す'
new = 'During True Aid Stance, press <KC SHOOT>.'
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_120'
old = '味方を狙って集中しジャストタイミングで矢を放つ'
new = '''
Focus concentration on allies and fire arrows
with perfect timing.'''
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_121'
old = '<KC ATTACK1>を押す'
new = 'Press <KC ATTACK1>.'
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_122'
old = '<KC CHANGE_ARROW>を押す'
new = 'Press <KC CHANGE_ARROW>.'
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_123'
old = '<PADM><KC WEAPON_SUB>または<KC WEAPON_MAIN>を押しながら右スティックを倒す<KEYM>闘波／助真の構え中にマウス移動'
new = '<PADM>Press and hold <KC WEAPON_SUB> or <KC WEAPON_MAIN>, then move the right stick<KEYM>During Seeker/True Aid Stance, move the mouse</KEYM>.'
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_135'
old = 'しがみつき中に<KC ATTACK1>を押す'
new = '''
While climbing an enemy,
press <KC ATTACK1>.'''
[[message]]
key = 'NORMAL_SKILL_COMMAND_08_178'
old = '<KC RELOAD>を押す'
new = 'Press <KC RELOAD>.'
