[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_1'
old = 'ノーマルホワイト'
new = 'Normal White'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_2'
old = 'ノーマルレッド'
new = 'Normal Red'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_3'
old = 'ノーマルグリーン'
new = 'Normal Green'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_4'
old = 'ノーマルブルー'
new = 'Normal Blue'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_5'
old = 'ノーマルブラウン'
new = 'Normal Brown'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_6'
old = 'ダークマーブル'
new = 'Dark Marble'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_7'
old = 'オールドスクロール'
new = 'Old Scroll'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_8'
old = 'ファイヤー'
new = 'Fire'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_9'
old = 'セフィロトツリー'
new = 'Sefirotic Tree'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_10'
old = 'ドラゴン'
new = 'Dragon'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_11'
old = 'アルカナ'
new = 'Arcana'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_12'
old = 'シーリングワックス'
new = 'Sealing Wax'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_13'
old = 'ロイヤルティ'
new = 'Royalty'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_14'
old = 'シック'
new = 'Chic'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_15'
old = '紋章'
new = 'Coat of Arms'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_16'
old = 'リーガルブルー'
new = 'Regal Blue'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_17'
old = 'レスタニア全土'
new = 'Lestania All Over'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_18'
old = 'オペラカーテン'
new = 'Opera Curtain'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_19'
old = '石畳'
new = 'Cobblestone'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_20'
old = 'チョコレート'
new = 'Chocolate'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_21'
old = 'ブック'
new = 'Book'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_22'
old = '白竜シンボル'
new = 'The White Dragon Symbol'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_23'
old = 'アーガイル'
new = 'Argyle'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_24'
old = 'モンスターズ'
new = 'Monsters'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_25'
old = 'マリン・ノート'
new = 'Marine Note'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_26'
old = 'エレガント'
new = 'Elegant'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_27'
old = 'スティグマ'
new = 'Stigma'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_28'
old = 'スポットライト'
new = 'Spotlight'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_29'
old = 'ウッドボード'
new = 'Wood Board'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_30'
old = 'オベリスク'
new = 'Obelisk'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_31'
old = '神殿'
new = 'Temple'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_32'
old = 'ゲート'
new = 'Gate'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_33'
old = '燐光虫'
new = 'Glowworms'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_34'
old = 'サマー'
new = 'Summer'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_35'
old = 'トリック・オア・トリート'
new = 'Trick or Treat'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_36'
old = 'カラフルエッグ'
new = 'Colorful Eggs'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_37'
old = '知識の木'
new = 'Tree of Knowledge'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_38'
old = 'アンティークパターン'
new = 'Antique Pattern'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_39'
old = 'ウッドテクスチャ'
new = 'Wood Texture'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_40'
old = 'ステンドグラス'
new = 'Stained Glass'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_41'
old = 'ウェーブストライプ'
new = 'Wave Stripes'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_42'
old = 'ピンクフラワー'
new = 'Pink Flowers'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_43'
old = 'クラシックフラワー'
new = 'Classic Flowers'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_44'
old = 'ゴールドダマスク'
new = 'Gold Damascus'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_45'
old = 'アンティークウッドフレーム'
new = 'Antique Wood Frame'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_46'
old = 'リム石碑'
new = 'Rift Monument'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_47'
old = 'レリーフ'
new = 'Relief'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_48'
old = '格子柄'
new = 'Plaid'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_49'
old = 'モノグラム'
new = 'Monogram'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_50'
old = 'オールドストライプ'
new = 'Old Stripes'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_51'
old = 'アーバン'
new = 'Urban'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_52'
old = 'アンティーク'
new = 'Antique'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_53'
old = 'キューブ'
new = 'Cubes'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_54'
old = 'ロイヤル'
new = 'Royal'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_55'
old = 'エピック'
new = 'Epic'
[[message]]
key = 'ARISENCARD_BACKGROUND_NAME_56'
old = 'レジェンダリー'
new = 'Legendary'
