[[message]]
key = 'menu_item'
old = 'アイテムバッグ'
new = 'Item Bag'
[[message]]
key = 'menu_key_item'
old = 'キーアイテム'
new = 'Key Items'
[[message]]
key = 'menu_equip_status'
old = 'ステータス・装備'
new = 'Status / Equipment'
[[message]]
key = 'menu_newspaper'
old = 'レスタニアニュース'
new = 'Lestania News'
[[message]]
key = 'menu_quest'
old = 'クエストログ'
new = 'Quest Log'
[[message]]
key = 'menu_master'
old = 'ジョブ修練ログ'
new = 'Job Training Log'
[[message]]
key = 'menu_tutorial'
old = 'チュートリアルガイド'
new = 'Tutorial'
[[message]]
key = 'menu_map'
old = 'マップ'
new = 'Map'
[[message]]
key = 'menu_lobby'
old = 'ロビー情報'
new = 'Lobby Information'
[[message]]
key = 'menu_rim_transport'
old = 'リム転移'
new = 'Rift Teleport'
[[message]]
key = 'menu_party'
old = 'パーティー管理'
new = 'Party Management'
[[message]]
key = 'menu_clan'
old = 'クランステータス'
new = 'Clan Status'
[[message]]
key = 'menu_community'
old = 'コミュニティリスト'
new = 'Community List'
[[message]]
key = 'menu_photo'
old = 'フォトモード'
new = 'Photo Mode'
[[message]]
key = 'menu_gp_charge'
old = '黄金石の確認'
new = 'Check Golden Gemstones'
[[message]]
key = 'menu_option_sys'
old = 'デバイス設定'
new = 'System Config'
[[message]]
key = 'menu_manual'
old = 'プレイマニュアル'
new = 'Play Manual'
[[message]]
key = 'menu_support'
old = 'サポート・報告'
new = 'Support / Report'
[[message]]
key = 'menu_license'
old = 'ライセンス'
new = 'License'
[[message]]
key = 'menu_shut_down'
old = 'ゲーム中断'
new = 'Exit Game'
[[message]]
key = 'menu_gp_status'
old = 'オンラインステーション'
new = 'Online Station'
[[message]]
key = 'menu_gp_shop'
old = 'オンラインショップ'
new = 'Online Shop'
[[message]]
key = 'menu_matching_profile'
old = 'プロフィール編集'
new = 'Edit Profile'
[[message]]
key = 'menu_ls'
old = 'グループチャット'
new = 'Group Chat'
[[message]]
key = 'menu_arisen_card'
old = '覚者プロフィール'
new = 'Arisen Profile'
[[message]]
key = 'menu_my_fixed_pattern'
old = 'マイ定型文'
new = 'My Phrases'
[[message]]
key = 'menu_fixed_pattern'
old = '定型文'
new = 'Phrases'
[[message]]
key = 'menu_emote'
old = 'エモート'
new = 'Emotes'
[[message]]
key = 'menu_mail'
old = 'メール'
new = 'Mail'
[[message]]
key = 'menu_pawn'
old = 'ポーン'
new = 'Pawns'
[[message]]
key = 'menu_pawn_command'
old = 'ポーン命令'
new = 'Pawn Order'
[[message]]
key = 'menu_achievement'
old = 'アチーブメント'
new = 'Achievements'
[[message]]
key = 'menu_server_change'
old = 'ワールド変更'
new = 'World Select'
[[message]]
key = 'menu_exit_contents'
old = 'コンテンツ中断'
new = 'Exit Content'
[[message]]
key = 'menu_option_chr'
old = 'ゲーム設定'
new = 'Game Config'
[[message]]
key = 'menu_area_infomation'
old = 'エリアリスト'
new = 'Area List'
[[message]]
key = 'menu_deli_box'
old = 'アイテムポスト'
new = 'Item Post'
[[message]]
key = 'menu_photo_album'
old = 'フォトアルバム'
new = 'Photo Albums'
[[message]]
key = 'menu_code'
old = 'イベントコード入力'
new = 'Event Code Input'
[[message]]
key = 'menu_login_bonus'
old = 'スタンプボーナス確認'
new = 'Check Stamp Bonus'
[[message]]
key = 'menu_confirm_go_title'
old = '''
ゲームを中断してタイトル画面に戻ります
よろしいですか？'''
new = 'Are you sure you want to exit to the title?'
[[message]]
key = 'menu_confirm_go_launcher'
old = '''
ログアウトしてランチャー画面に戻ります
よろしいですか？'''
new = 'Are you sure you want to exit to the launcher?'
[[message]]
key = 'menu_confirm_shutdown'
old = '''
ログアウトしてゲームを終了します
よろしいですか？'''
new = 'Are you sure you want to exit the game?'
[[message]]
key = 'menu_quit_select_shutdown'
old = 'ログアウトしてゲームを終了する'
new = 'Log out and exit game'
[[message]]
key = 'menu_quit_select_go_title'
old = 'タイトルに戻る'
new = 'Return to title'
[[message]]
key = 'menu_quit_select_go_launcher'
old = 'ログアウトしてランチャーに戻る'
new = 'Log out and return to launcher'
[[message]]
key = 'menu_gacha'
old = 'トレジャーズロット'
new = 'Treasure Lot'
[[message]]
key = 'menu_serch_player'
old = 'プレイヤー検索'
new = 'Player Search'
[[message]]
key = 'menu_entryboard'
old = 'エントリーボード'
new = 'Entryboard'
[[message]]
key = 'menu_quick_party'
old = 'クイックパーティー'
new = 'Quick Party'
[[message]]
key = 'menu_caplink'
old = 'カプリンク'
new = 'Caplink'
[[message]]
key = 'menu_ps_items'
old = ''
new = ''
[[message]]
key = 'menu_clan_management'
old = 'クラン管理'
new = 'Clan Management'
[[message]]
key = 'menu_boxgacha'
old = 'ボックストレジャーズロット'
new = 'Box Treasure Lot'
[[message]]
key = 'menu_time_event'
old = 'リワードミッション'
new = 'Reward Mission'
[[message]]
key = 'menu_ps_store'
old = ''
new = ''
[[message]]
key = 'menu_ps_store_buy'
old = ''
new = ''
[[message]]
key = 'menu_partyboard'
old = '募集掲示板'
new = 'Recruitment Board'
[[message]]
key = 'menu_partyboard_dialog'
old = 'パーティー募集掲示板のカテゴリを選択してください'
new = '''
Please select
Party Recruitment Board category.'''
[[message]]
key = 'menu_partyboard_type01'
old = 'パーティー募集掲示板を開く'
new = 'Open Party Recruitment Board'
[[message]]
key = 'menu_pq_history'
old = 'サブストーリーログ'
new = 'Substory Log'
[[message]]
key = 'menu_adv_guide'
old = '冒険ガイド'
new = 'Adventure Guide'
[[message]]
key = 'menu_infdelivery_event'
old = '大口納品イベント'
new = 'Large Delivery Event'
[[message]]
key = 'menu_exmboard_select'
old = 'EXM募集掲示板'
[[message]]
key = 'menu_exmboard_dialog'
old = 'エントリーするEXMを選択してください'
[[message]]
key = 'menu_board_select'
old = '確認する掲示板を選択してください'
[[message]]
key = 'menu_partyboard_select'
old = 'パーティー募集掲示板'
