[[message]]
key = 'OS_catalog_pawn'
old = 'クラフトマスターポーン'
new = 'Craft Master Pawns'
[[message]]
key = 'OS_index_en'
old = 'Online Shop'
new = 'Online Shop'
[[message]]
key = 'OS_index_jp'
old = 'オンラインショップ'
new = 'Online Shop'
[[message]]
key = 'OS_menu_gs_buy'
old = '黄金石の購入'
new = 'Buy Golden Gemstones'
[[message]]
key = 'OS_menu_status'
old = 'ステータスの確認'
new = 'Check Status'
[[message]]
key = 'OS_title_gs_buy'
old = '黄金石の購入'
new = 'Buy Golden Gemstones'
[[message]]
key = 'OS_cap_remnant'
old = 'CAP残高'
new = 'CAP Balance'
[[message]]
key = 'OS_cap'
old = 'CAP'
new = 'CAP'
[[message]]
key = 'OS_relogin'
old = '''
COGのログインが切れています
ブラウザからCOG認証を行ってください'''
[[message]]
key = 'OS_cogid'
old = 'COG ID'
new = 'COG ID'
[[message]]
key = 'OS_status_title'
old = '黄金石ステータス'
new = 'Golden Gemstone Status'
[[message]]
key = 'OS_status_bkbtn'
old = '黄金石ショップ'
new = 'Golden Gemstone Shop'
[[message]]
key = 'OS_status_ticket'
old = 'Ticket'
new = 'Ticket'
[[message]]
key = 'OS_status_cticket'
old = 'シルバーチケット'
new = 'Silver Tickets'
[[message]]
key = 'OS_status_usecourse'
old = 'Used Passport and Course'
new = 'Used Passport and Course'
[[message]]
key = 'OS_status_time_remaining'
old = '使用期限：'
new = 'Expires:'
[[message]]
key = 'OS_status_time'
old = '時間'
new = ' hours'
[[message]]
key = 'OS_status_newcourse'
old = '未使用コース'
new = 'Unused Courses'
[[message]]
key = 'OS_status_history'
old = '黄金石使用履歴'
new = 'GG Usage History'
[[message]]
key = 'OS_status'
old = 'ステータス'
new = 'Status'
[[message]]
key = 'OS_buy_item'
old = '''
<NAME ITEM> を 黄金石 <VAL> 個で購入します
よろしいですか？'''
[[message]]
key = 'OS_buy_goldstone'
old = '''
黄金石 <VAL> 個を <VAL CAP>で購入します
よろしいですか？'''
new = '''
Are you sure you want to purchase <VAL>
Golden Gemstones with <VAL CAP>?'''
[[message]]
key = 'OS_btn_ok'
old = '購入'
new = 'Buy'
[[message]]
key = 'OS_btn_ng'
old = 'キャンセル'
new = 'Cancel'
[[message]]
key = 'OS_catalog_pickup'
old = 'ピックアップ'
new = 'Pickup'
[[message]]
key = 'OS_catalog_option'
old = '<OPCS>'
new = '<OPCS>'
[[message]]
key = 'OS_catalog_wepon'
old = '武具・防具'
new = 'Weapon / Armor'
[[message]]
key = 'OS_status_time_remaining_day'
old = '日'
new = ' days'
[[message]]
key = 'OS_date'
old = '<DATE>'
new = '<DATE>'
[[message]]
key = 'OS_cod_impression'
old = 'COG認証'
[[message]]
key = 'OS_used_btn'
old = '使用中'
new = 'Active'
[[message]]
key = 'OS_use_btn'
old = '使用'
new = 'Use'
[[message]]
key = 'OS_use_confirm'
old = '<NAME ITEM>をいますぐ使用しますか？'
new = 'Do you want to use <NAME ITEM> right now?'
[[message]]
key = 'OS_use_item'
old = '''
<NAME ITEM>を使用します
よろしいですか？'''
new = '''
<NAME ITEM> will be used.
Is this okay?'''
[[message]]
key = 'OS_goldstone_num'
old = '黄金石 <VAL> 個'
new = '<VAL> Golden Gemstones'
[[message]]
key = 'OS_announce_buy_use_item'
old = '<NAME ETC> を購入して使用しました'
[[message]]
key = 'OS_announce_buy_gs'
old = '黄金石 <VAL> 個を購入しました'
new = 'Purchased <VAL> Golden Gemstones.'
[[message]]
key = 'OS_announce_use_item'
old = '<NAME ETC> を使用しました'
new = '<NAME ETC> has been used.'
[[message]]
key = 'OS_announce_voice'
old = 'ポーンボイス'
new = 'Pawn Voice'
[[message]]
key = 'OS_announce_buy'
old = '<NAME ETC> を購入しました'
new = '<NAME ETC> has been purchased.'
[[message]]
key = 'OS_announce_buyanduse'
old = '<NAME ETC> を購入して使用しました'
[[message]]
key = 'OS_announce_use'
old = '<NAME ETC> を使用しました'
new = '<NAME ETC> has been used.'
[[message]]
key = 'OS_announce_havingnum'
old = '所持数：<VAL>'
new = 'You have: <VAL>'
[[message]]
key = 'OS_announce_gpdialog'
old = '黄金石の確認'
new = 'Check GG'
[[message]]
key = 'OS_catalog_collabo'
old = 'コラボレーション装備'
new = 'Collaboration Equipment'
[[message]]
key = 'OS_buy_cap'
old = 'CAPチャージ'
new = 'Charge CAP'
[[message]]
key = 'OS_catalog_passport'
old = 'パスポート'
new = 'Passports'
[[message]]
key = 'OS_index_status_en'
old = 'Online Station'
new = 'Online Station'
[[message]]
key = 'OS_index_status_jp'
old = 'オンラインステーション'
new = 'Online Station'
[[message]]
key = 'OS_histry_information'
old = '最新50件(古い履歴から順に削除されます)'
new = 'The last 50 entries are shown (Older entries are deleted)'
[[message]]
key = 'OS_annnounce_nocap'
old = '戦闘中にCAPの購入はできません'
new = 'You cannot purchase CAP while in combat.'
[[message]]
key = 'OS_annnounce_multi_option'
old = 'ダブル特典・トリプル特典対象商品です'
[[message]]
key = 'OS_annnounce_nolist'
old = '表示するリストがありません'
[[message]]
key = 'OS_activetetimer_remaining'
old = '有効期限：'
new = 'Expires:'
[[message]]
key = 'OS_index_category'
old = 'Category'
new = 'Category'
[[message]]
key = 'OS_index_management'
old = 'COGアカウント管理'
[[message]]
key = 'OS_index_active'
old = '発動中'
new = 'Active'
[[message]]
key = 'OS_index_caption'
old = 'Details'
new = 'Details'
[[message]]
key = 'OS_index_price'
old = '価格：'
new = 'Price:'
[[message]]
key = 'OS_index_yen'
old = '円'
new = 'Yen'
[[message]]
key = 'OS_index_exrecord'
old = 'COG購入履歴（CAPの購入・継続利用権）'
[[message]]
key = 'OS_index_record'
old = 'COG購入履歴'
[[message]]
key = 'OS_index_loginskip'
old = 'ログインスキップ設定'
[[message]]
key = 'OS_index_loginskip_in_decide'
old = '決済時のログインスキップ：'
[[message]]
key = 'OS_index_valid'
old = '有効'
new = 'Valid'
[[message]]
key = 'OS_index_invalid'
old = '無効'
new = 'Invalid'
[[message]]
key = 'OS_index_loginskip_disable'
old = 'ログインスキップの解除'
[[message]]
key = 'OS_index_change_payment'
old = 'クレジットカード登録情報変更'
[[message]]
key = 'OS_index_change_records'
old = '登録情報変更'
[[message]]
key = 'OS_index_cancell_passport'
old = 'パスポート（クレジットカード継続）の解約'
[[message]]
key = 'OS_index_manage_charge'
old = '継続利用権 管理'
[[message]]
key = 'OS_index_pass_cource'
old = '<OPCS>'
new = '<OPCS>'
[[message]]
key = 'OS_index_equipment_item'
old = '装備・アイテム'
new = 'Equipment / Item'
[[message]]
key = 'OS_index_none'
old = 'なし'
new = 'None'
[[message]]
key = 'OS_catalog_pawn2'
old = 'クラフトマスターポーン'
new = 'Craft Master Pawn'
[[message]]
key = 'OS_announce_voice2'
old = 'ポーンボイス'
new = 'Pawn Voice'
[[message]]
key = 'OS_index_eninvalid'
old = '無効にする'
[[message]]
key = 'OS_dialog_is_invalid_logskip'
old = '決済時のログインスキップを無効化しますか？'
[[message]]
key = 'OS_dialog_done_invalid_logskip'
old = '決済時のログインスキップを無効化しました'
[[message]]
key = 'OS_index_mode_browser'
old = 'ブラウザ操作'
new = 'Use Browser'
[[message]]
key = 'OS_index_mode_shop'
old = 'ショップ操作'
new = 'Use Shop'
[[message]]
key = 'OS_annnounce_nocap1'
old = '今の状況ではCAPの購入はできません'
[[message]]
key = 'OS_annnounce_purchased'
old = '<NAME ETC> は既に購入済みです'
[[message]]
key = 'OS_catalog_storage'
old = 'ストレージ'
new = 'Storage'
[[message]]
key = 'OS_catalog_skillreset'
old = 'スキルリセット'
new = 'Skill Reset'
[[message]]
key = 'OS_dialog_buy_announce_afterfollow'
old = '''
ご購入された商品は
オンラインステーションの「未使用コース」から
ご使用いただけます'''
[[message]]
key = 'OS_catalog_fixed_phrase'
old = 'ボイス定型文'
[[message]]
key = 'OS_catalog_shortcut'
old = 'ショートカット'
new = 'Shortcut'
[[message]]
key = 'OS_pop_price_reload'
old = '価格が最新の情報に更新されました'
