[[message]]
key = 'OSD_index_en'
old = 'Status'
new = 'Status'
[[message]]
key = 'OSD_index_jp'
old = '黄金石の確認'
new = 'Check GG'
[[message]]
key = 'OSD_tab_goldstone'
old = '黄金石'
new = 'Golden Gemstones'
[[message]]
key = 'OSD_tab_effectivedate'
old = '有効期限'
new = 'Expiration Date'
[[message]]
key = 'OSD_tab_gethistory'
old = '獲得履歴'
new = 'Purchase History'
[[message]]
key = 'OSD_title_goldstone'
old = '所持黄金石'
new = 'Golden Gemstone Total'
[[message]]
key = 'OSD_title_goldstone_items'
old = '所持黄金石の内訳'
new = 'Breakdown of owned GG'
[[message]]
key = 'OSD_title_goldstone_pay'
old = '購入分'
new = 'Purchased'
[[message]]
key = 'OSD_title_goldstone_free'
old = '無料分'
new = 'Free'
[[message]]
key = 'OSD_warning'
old = '今月末で期限が切れる黄金石があります'
[[message]]
key = 'OSD_effectivedate_text1'
old = '黄金石の有効期限は、獲得から4か月後の月末までです'
new = 'GG expire at the end of the month, 4 months after purchase.'
[[message]]
key = 'OSD_effectivedate_text2'
old = 'まで有効の黄金石'
new = 'Gemstones expire'
[[message]]
key = 'OSD_date'
old = '<DATE>'
new = '<DATE>'
[[message]]
key = 'OSD_pay'
old = '購入分'
new = 'Purchased'
[[message]]
key = 'OSD_free'
old = '無料分'
new = 'Free'
[[message]]
key = 'OSD_eventcode_index_en'
old = 'Event Code'
new = 'Event Code'
[[message]]
key = 'OSD_eventcode_index_jp'
old = 'イベントコードの入力'
new = 'Input event code'
[[message]]
key = 'OSD_eventcode_title'
old = '16ケタのイベントコードを入力してください'
new = 'Please enter your 16-digit event code'
[[message]]
key = 'OSD_eventcode_ok'
old = '決定'
new = 'OK'
[[message]]
key = 'OSD_eventcode_warning'
old = 'イベントコードに関する注意'
new = 'Note about event codes'
[[message]]
key = 'OSD_eventcode_warning_text'
old = '''
イベントコード入力を5回失敗すると、
3時間イベントコードの入力ができなくなります

コード特典は現在ログイン中の
キャラクターのみに適用されます'''
new = '''
When you fail to input an event code 5 times,
you will not be able to enter event codes for 3 hours.

The code benefits are only applied to the
currently logged in character.'''
[[message]]
key = 'OSD_histry_information'
old = '最新50件(古い履歴から順に削除されます)'
new = 'The last 50 entries are shown (Older entries are deleted)'
[[message]]
key = 'OSD_announce_disbuyable'
old = '現在黄金石の購入を利用することができません'
[[message]]
key = 'OSD_msg_stampbornus'
old = 'スタンプボーナス'
new = 'Stamp Bonus'
[[message]]
key = 'OSD_msg_presents'
old = '運営からの配布'
[[message]]
key = 'ODS_msg_buy_option'
old = '購入特典'
[[message]]
key = 'OSD_notion_incomplete_input'
old = '全ての入力が終わらないと送信できません'
new = 'Please finish entering the entire code.'
[[message]]
key = 'OSD_buy'
old = 'オンラインショップで購入'
new = 'Online Shop Purchase'
[[message]]
key = 'OSD_buy_by_bonus'
old = 'オンラインショップで購入（ボーナス）'
new = 'Online Shop Purchase (Bonus)'
[[message]]
key = 'OSD_recieve_by_mail'
old = 'メールで受取'
new = 'Received in Mail'
[[message]]
key = 'OSD_msg_loginbornus'
old = 'ログインボーナス'
new = 'Login Bonus'
[[message]]
key = 'OSD_msg_no_history'
old = '履歴はありません'
new = 'There is no history.'
[[message]]
key = 'OSD_msg_no_list'
old = 'リストはありません'
new = 'There is no list.'
[[message]]
key = 'OSD_ps_buy'
old = 'PlayStation™Storeで購入'
new = 'PlayStation™ Store Purchase'
[[message]]
key = 'OSD_ps_buy_by_bonus'
old = 'PlayStation™Storeで購入（ボーナス）'
new = 'PlayStation™ Store Purchase (Bonus)'
