[[message]]
key = 'info_party_invite'
old = '<NAME TARGET> からパーティーへの招待があります'
new = '<NAME TARGET> has invited you to join a party'
[[message]]
key = 'info_party_invite_list'
old = '<NAME TARGET> からパーティーへの招待があります'
new = '<NAME TARGET> has invited you to join a party'
[[message]]
key = 'info_friend_req'
old = '<NAME TARGET> からフレンド申請があります'
new = '<NAME TARGET> has sent you a friend request'
[[message]]
key = 'info_friend_req_list'
old = 'フレンド申請があります'
new = 'There is a friend request'
[[message]]
key = 'info_clan_invite'
old = '<NAME TARGET>からクランへの招待があります'
new = '<NAME TARGET> has sent you a clan invite'
[[message]]
key = 'info_clan_invite_list'
old = 'クランから誘いがあります'
new = 'There is a clan invitation'
[[message]]
key = 'info_clan_mission'
old = '<NAME CLANMISSION> を達成した！'
new = '<NAME CLANMISSION> was achieved!'
[[message]]
key = 'info_clan_mission_list'
old = '<NAME CLANMISSION> を達成した！'
new = '<NAME CLANMISSION> was achieved!'
[[message]]
key = 'info_clan_levelup'
old = 'クランレベルが<VAL>になった！'
new = 'The clan level has reached <VAL>!'
[[message]]
key = 'info_clan_levelup_list'
old = 'クランの歴史が更新されました'
new = 'The clan history has been updated'
[[message]]
key = 'info_group_invite'
old = '<NAME TARGET> からグループチャットへの招待があります'
new = '<NAME TARGET> has invited you to a group chat'
[[message]]
key = 'info_group_invite_list'
old = '<NAME TARGET> からグループチャットへの招待があります'
new = '<NAME TARGET> has invited you to a group chat'
[[message]]
key = 'info_mail'
old = '新着メールが届きました'
new = 'New mail has arrived'
[[message]]
key = 'info_mail_list'
old = '未読／未取得メールがあります'
new = 'There is unread / unclaimed mail'
[[message]]
key = 'info_news'
old = 'レスタニアニュースが更新されました'
new = 'Lestania News has been updated'
[[message]]
key = 'info_news_list'
old = 'レスタニアニュースが更新されました'
new = 'Lestania News has been updated'
[[message]]
key = 'info_full_member'
old = 'エントリーメンバーが揃いました'
new = 'Entry members is now full'
[[message]]
key = 'info_full_member_list'
old = 'エントリーメンバーが揃いました'
new = 'Entry members is now full'
[[message]]
key = 'info_tutorial'
old = 'チュートリアル：<NAME TUTORIAL>'
new = 'Tutorial: <NAME TUTORIAL>'
[[message]]
key = 'info_tutorial_list'
old = 'チュートリアル：<NAME TUTORIAL>'
new = 'Tutorial: <NAME TUTORIAL>'
[[message]]
key = 'info_wait_quest'
old = '受注待ちのクエストがあります'
new = 'There are quest orders waiting'
[[message]]
key = 'info_wait_quest_list'
old = '受注待ちのクエストが<VAL>件あります'
new = 'There are quest orders waiting for quest <VAL>'
[[message]]
key = 'info_achieve'
old = 'アチーブメントを獲得しました'
new = 'You have earned an achievement'
[[message]]
key = 'info_achieve_list'
old = '<NAME ACHIEVE>を獲得しました'
new = '<NAME ACHIEVE> has been earned'
[[message]]
key = 'info_achieve_unlock'
old = '新たなアチーブメントが解放されました'
new = 'A new achievement has been unlocked'
[[message]]
key = 'info_achieve_unlock_list'
old = '新たなアチーブメントを解放しました'
new = 'A new achievement has been unlocked'
[[message]]
key = 'info_craft_finish'
old = 'クラフトが完成しました'
new = 'A craft has completed'
[[message]]
key = 'info_quest_end'
old = '配信期間が終了したクエストを破棄しました'
new = 'A quest has been canceled because the delivery time period has ended'
[[message]]
key = 'info_propose_quit_contents'
old = 'コンテンツ途中離脱の提案がありました'
new = 'There is a proposal to withdraw from the content'
[[message]]
key = 'info_propose_quit_contents_list'
old = 'コンテンツ途中離脱の提案が届いています'
new = 'A proposal to withdraw from the content has arrived'
[[message]]
key = 'info_quick_ready_wait_list'
old = 'クイックパーティーの準備完了を受付中'
new = 'The quick party is ready'
[[message]]
key = 'info_entry_board_ready_wait_list'
old = 'エントリーメンバーの準備完了を受付中'
new = 'The entryboard is ready'
[[message]]
key = 'info_quest_end_list'
old = '配信期間が終了したクエストを破棄しました'
new = 'A quest has been canceled because the delivery time period has ended'
[[message]]
key = 'info_entry_board_time_extension_list'
old = 'エントリーボードの募集時間を延長できます'
new = 'Entryboard recruitment time can be extended'
[[message]]
key = 'info_party_entry_accepted_list'
old = 'リーダーがパーティー要請を受諾しました'
new = 'The leader has accepted the party request'
[[message]]
key = 'info_clan_req'
old = '<NAME TARGET>からクラン加入申請がありました'
new = '<NAME TARGET> has requested to join the clan'
[[message]]
key = 'info_clan_req_info'
old = 'クランへの加入申請があります'
new = 'There is an application to join the clan'
[[message]]
key = 'info_clan_join_other'
old = '<NAME TARGET>がクランに加入しました'
new = '<NAME TARGET> has joined the clan'
[[message]]
key = 'info_clan_join'
old = '<NAME TARGET>がクランに加入しました'
new = '<NAME TARGET> has joined the clan'
[[message]]
key = 'info_clan_chg_master'
old = '<NAME TARGET>がクランマスターになりました'
new = '<NAME TARGET> has become the new clan master'
[[message]]
key = 'info_clan_chg_leader'
old = '<NAME TARGET>がクランリーダーになりました'
new = '<NAME TARGET> has become a new clan leader'
[[message]]
key = 'info_pt_leader_leave_list'
old = 'リーダーが不在です'
new = 'The party leader is missing'
[[message]]
key = 'info_pt_leader_leave'
old = '''
リーダーが不在です
白竜神殿かリムストーンのある拠点施設でリーダーを設定してください'''
new = '''
The party leader is missing.
Please set the party leader in an inn, at the White Dragon Temple, or at a Riftstone'''
[[message]]
key = 'info_bazzar_dealed'
old = 'バザーに出品中の<NAME ITEM>が取引成立しました'
new = '<NAME ITEM> has sold at the bazaar'
[[message]]
key = 'info_party_invite_pop'
old = 'パーティーへの招待があります'
new = 'There are party invitations'
[[message]]
key = 'info_caplink_chat'
old = 'カプリンク：新着チャットがあります'
new = 'Caplink: There is a new chat'
[[message]]
key = 'info_caplink_maintenance'
old = 'カプリンクが<VAL>からメンテナンスに入ります'
new = 'Caplink will enter maintenance at <VAL>'
[[message]]
key = 'info_caplink_friend_online'
old = 'カプリンク：カプトモがオンラインになりました'
new = 'Caplink: A friend has come online'
[[message]]
key = 'info_caplink_friend_request'
old = 'カプリンク：カプトモ申請が届いています'
new = 'Caplink: A friend request has arrived'
[[message]]
key = 'info_caplink_friend_consent'
old = 'カプリンク：カプトモが増えました'
[[message]]
key = 'info_caplink_invite'
old = 'カプリンク：ゲーム招待メッセージが届いています'
[[message]]
key = 'info_caplink_message'
old = 'カプリンク：メッセージが届いています'
[[message]]
key = 'info_caplink_friend_modify'
old = 'カプリンク：カプトモがプロフィールを変更しました'
[[message]]
key = 'info_caplink_invite_detail'
old = 'カプリンク：%sからゲーム招待メッセージが届いています'
[[message]]
key = 'info_caplink_friend_online_detail'
old = 'カプリンク：%sがオンラインになりました'
[[message]]
key = 'info_caplink_friend_content_detail'
old = 'カプリンク：%sとカプトモになりました'
[[message]]
key = 'info_entry_invitation'
old = '<NAME TARGET>からエントリーボードに招待されました'
new = 'Invited to the entry board by <NAME TARGET>'
[[message]]
key = 'info_entry_invitation_list'
old = '<NAME TARGET>からエントリーボードへの招待があります'
[[message]]
key = 'info_clan_invite_direct'
old = '<NAME TARGET>からクランへの直接招待があります'
[[message]]
key = 'info_clan_invite_list_direct'
old = 'クランから直接招待があります'
[[message]]
key = 'info_dlc_station_not_receive'
old = 'DLC Stationに未受け取りのダウンロードコンテンツがあります'
[[message]]
key = 'info_adv_guide_new_info'
old = '冒険ガイドに新たなクエストの紹介があります'
new = 'There is a new quest listed in the Adventure Guide'
[[message]]
key = 'info_daily_mission_complete_info'
old = 'リワードミッションで受け取れるアイテムがあります'
