[[message]]
key = 'kcd_000'
old = '移動 ↑'
new = 'Move ↑'
[[message]]
key = 'kcd_001'
old = '移動 ↓'
new = 'Move ↓'
[[message]]
key = 'kcd_002'
old = '移動 ←'
new = 'Move ←'
[[message]]
key = 'kcd_003'
old = '移動 →'
new = 'Move →'
[[message]]
key = 'kcd_004'
old = 'オートラン'
new = 'Auto-Run'
[[message]]
key = 'kcd_005'
old = '項目移動 ↑'
new = 'Item Move ↑'
[[message]]
key = 'kcd_006'
old = '項目移動 ↓'
new = 'Item Move ↓'
[[message]]
key = 'kcd_007'
old = '項目移動 ←'
new = 'Item Move ←'
[[message]]
key = 'kcd_008'
old = '項目移動 →'
new = 'Item Move →'
[[message]]
key = 'kcd_009'
old = 'チャット'
new = 'Chat'
[[message]]
key = 'kcd_010'
old = 'ダイレクトチャット'
new = 'Direct Chat'
[[message]]
key = 'kcd_011'
old = '''
マルチショートカット１
簡易コミュニケーション１'''
new = '''
Multi Shortcut 1
Simple Communication 1'''
[[message]]
key = 'kcd_012'
old = '''
マルチショートカット２
簡易コミュニケーション２'''
new = '''
Multi Shortcut 2
Simple Communication 2'''
[[message]]
key = 'kcd_013'
old = '''
マルチショートカット３
簡易コミュニケーション３'''
new = '''
Multi Shortcut 3
Simple Communication 3'''
[[message]]
key = 'kcd_014'
old = '''
マルチショートカット４
簡易コミュニケーション４'''
new = '''
Multi Shortcut 4
Simple Communication 4'''
[[message]]
key = 'kcd_015'
old = '''
マルチショートカット５
簡易コミュニケーション５'''
new = '''
Multi Shortcut 5
Simple Communication 5'''
[[message]]
key = 'kcd_016'
old = '''
マルチショートカット６
簡易コミュニケーション６'''
new = '''
Multi Shortcut 6
Simple Communication 6'''
[[message]]
key = 'kcd_017'
old = '''
マルチショートカット７
簡易コミュニケーション７'''
new = '''
Multi Shortcut 7
Simple Communication 7'''
[[message]]
key = 'kcd_018'
old = '''
マルチショートカット８
簡易コミュニケーション８'''
new = '''
Multi Shortcut 8
Simple Communication 8'''
[[message]]
key = 'kcd_019'
old = '''
マルチショートカット９
簡易コミュニケーションのページ切り替え ←'''
new = '''
Multi Shortcut 9
Simple Communication Page Switch ←'''
[[message]]
key = 'kcd_020'
old = '''
マルチショートカット１０
簡易コミュニケーションのページ切り替え →'''
new = '''
Multi Shortcut 10
Simple Communication Page Switch →'''
[[message]]
key = 'kcd_021'
old = 'マルチショートカット１１'
new = 'Multi Shortcut 11'
[[message]]
key = 'kcd_022'
old = 'マルチショートカット１２'
new = 'Multi Shortcut 12'
[[message]]
key = 'kcd_023'
old = 'ジャンプ / 行動キャンセル 等'
new = 'Jump / Cancel Action, etc'
[[message]]
key = 'kcd_024'
old = 'タッチアクション / つかむ / 耐える 等'
new = 'Interact / Grab / Endure, etc'
[[message]]
key = 'kcd_025'
old = 'ノーマルスキル１'
new = 'Normal Skill 1'
[[message]]
key = 'kcd_026'
old = 'ノーマルスキル２　※ハンター / エレメントアーチャーは別項目'
new = '''
Normal Skill 2
※ Hunter / Element Archer is separate'''
[[message]]
key = 'kcd_027'
old = '<COL DAEEF3>【Ｓｈ】</COL>アトラクト'
new = '<COL DAEEF3>(Sh)</COL> Attract'
[[message]]
key = 'kcd_028'
old = '武器を構える / 納める'
new = 'Hold Weapon / Accept'
[[message]]
key = 'kcd_029'
old = 'カスタムスキルパレット切り替え（長押し）'
new = 'Custom Skill Palette Switch (Long Press)'
[[message]]
key = 'kcd_030'
old = 'カスタムスキル１'
new = 'Custom Skill 1'
[[message]]
key = 'kcd_031'
old = 'カスタムスキル２'
new = 'Custom Skill 2'
[[message]]
key = 'kcd_032'
old = 'カスタムスキル３'
new = 'Custom Skill 3'
[[message]]
key = 'kcd_033'
old = 'カスタムスキル４'
new = 'Custom Skill 4'
[[message]]
key = 'kcd_034'
old = 'カメラリセット'
new = 'Camera Reset'
[[message]]
key = 'kcd_035'
old = 'ゲームメニュー'
new = 'Game Menu'
[[message]]
key = 'kcd_036'
old = 'ショートカット：ステータス・装備'
new = 'Shortcut: Status / Equipment'
[[message]]
key = 'kcd_037'
old = 'ショートカット：アイテムバッグ'
new = 'Shortcut: Item Bag'
[[message]]
key = 'kcd_038'
old = 'ショートカット：ゲーム設定'
new = 'Shortcut: Game Config'
[[message]]
key = 'kcd_039'
old = 'ショートカット：パーティー管理'
new = 'Shortcut: Party'
[[message]]
key = 'kcd_040'
old = 'ショートカット：チュートリアルガイド'
new = 'Shortcut: Tutorial'
[[message]]
key = 'kcd_041'
old = 'ショートカット：クエストログ'
new = 'Shortcut: Quest Log'
[[message]]
key = 'kcd_042'
old = 'ショートカット：コミュニティリスト'
new = 'Shortcut: Community List'
[[message]]
key = 'kcd_043'
old = 'ショートカット：マップ'
new = 'Shortcut: Map'
[[message]]
key = 'kcd_044'
old = '''
マルチショートカット、
簡易コミュニケーションの切り替え'''
new = '''
Multi Shortcut,
Toggle Simple Communication'''
[[message]]
key = 'kcd_045'
old = 'ミニマップ操作の起動'
new = 'Activate Mini-map Operation'
[[message]]
key = 'kcd_046'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_DECIDE></COL>と同じ機能（決定）'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_DECIDE></COL> (Decide)"
[[message]]
key = 'kcd_047'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_CANCEL></COL>と同じ機能（キャンセル）'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_CANCEL></COL> (Cancel)"
[[message]]
key = 'kcd_048'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_START></COL>と同じ機能'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_START></COL>"
[[message]]
key = 'kcd_049'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_X></COL>と同じ機能'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_X></COL>"
[[message]]
key = 'kcd_050'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_Y></COL>と同じ機能'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_Y></COL>"
[[message]]
key = 'kcd_051'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_LB></COL>と同じ機能'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_LB></COL>"
[[message]]
key = 'kcd_052'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_RB></COL>と同じ機能'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_RB></COL>"
[[message]]
key = 'kcd_053'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_LT></COL>と同じ機能'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_LT></COL>"
[[message]]
key = 'kcd_054'
old = '<PFWD 0>の<COL FFFFFF><KCP UI_RT></COL>と同じ機能'
new = "Same function as <PFWD 0>'s <COL FFFFFF><KCP UI_RT></COL>"
[[message]]
key = 'kcd_055'
old = 'マウス左ボタン（決定）'
new = 'Left Mouse Button (Decide)'
[[message]]
key = 'kcd_056'
old = 'マウス右ボタン（キャンセル）'
new = 'Right Mouse Button (Cancel)'
[[message]]
key = 'kcd_057'
old = 'マウス中ボタン（アイテムの複数選択 等）'
new = 'Middle Mouse Button (Multiple item selection, etc)'
[[message]]
key = 'kcd_058'
old = 'ミニマップ操作中：ウィンドウの拡縮'
new = 'During Mini-map Operation: Scale Window'
[[message]]
key = 'kcd_059'
old = 'ミニマップ操作中：マップ位置のロック'
new = 'During Mini-map Operation: Lock Map Position'
[[message]]
key = 'kcd_060'
old = 'ミニマップ操作中：フリーマーカーの設置 / 消去（長押し）'
new = 'During Mini-map Operation: Set Free Marker / Erase (Long Press)'
[[message]]
key = 'kcd_061'
old = '''
<COL DAEEF3>【Ｐｒ】</COL>セイントオーラ　<COL DAEEF3>【Ｓｈ】</COL>フォースエンチャント
<COL DAEEF3>【Ａｌ】</COL>エリクシル　<COL DAEEF3>【Ｓｐ】</COL>ヒールブースト　<COL DAEEF3>【Ｈｉ】</COL>バック・リープ'''
new = '''
<COL DAEEF3>(Pr)</COL> Holy Aura  <COL DAEEF3>(Sh)</COL> Force Enchantment
<COL DAEEF3>(Al)</COL> Elixir  <COL DAEEF3>(Sp)</COL> Heal Boost  <COL DAEEF3>(Hi)</COL> Back Leap'''
[[message]]
key = 'kcd_062'
old = '''
<COL DAEEF3>【Ｈｕ】</COL>しじま射ち（弓構え中）　<COL DAEEF3>【Ｓｏ】</COL>スペリング（詠唱中）
<COL DAEEF3>【Ｈｉ】</COL>ロックオン中のカメラ操作（ルイン・ブレード構え中）'''
new = '''
<COL DAEEF3>(Hu)</COL> Keen Sight (when aiming bow)  <COL DAEEF3>(So)</COL> Chanting
<COL DAEEF3>(Hi)</COL> Camera operation during lock on (in Ruin Blade stance)'''
[[message]]
key = 'kcd_063'
old = '（未使用）行動キャンセル'
new = '(Unused) Behavior Cancellation'
[[message]]
key = 'kcd_064'
old = '揺さぶる（しがみつき中）'
new = 'Shake (while clinging)'
[[message]]
key = 'kcd_065'
old = '''
<COL DAEEF3>【Ｓｏ】</COL>バックムーブ　　　<COL DAEEF3>【Ｗａ】</COL>退魔の身構え
<COL DAEEF3>【Ａｌ】</COL>アルケム・フーガ　<COL DAEEF3>【Ｓｐ】</COL>スカー・ムーヴ'''
new = '''
<COL DAEEF3>(So)</COL> Back Move  <COL DAEEF3>(Wa)</COL> Brace
<COL DAEEF3>(Al)</COL> Alchemical Fuga  <COL DAEEF3>(Sp)</COL> Scar Move'''
[[message]]
key = 'kcd_066'
old = '''
ダッシュ（移動キーと同時入力）
※この項目がブランクキーの場合、同じ移動キー２回でダッシュ'''
new = '''
Dash (simultaneous input with move key)
※ If this is a blank key, dash by pressing the move key twice'''
[[message]]
key = 'kcd_067'
old = '<COL DAEEF3>【Ｆｉ】</COL><COL DAEEF3>【Ｓｅ】</COL><COL DAEEF3>【Ｗａ】</COL>連係投げ'
new = '<COL DAEEF3>(Fi)</COL> <COL DAEEF3>(Se)</COL> <COL DAEEF3>(Wa)</COL> Linking Throw'
[[message]]
key = 'kcd_068'
old = '<COL DAEEF3>【Ｈｕ】</COL><COL DAEEF3>【Ｅｌ】</COL>弓構え'
new = '<COL DAEEF3>(Hu)</COL> <COL DAEEF3>(El)</COL> Aim'
[[message]]
key = 'kcd_069'
old = '<COL DAEEF3>【Ｈｕ】</COL><COL DAEEF3>【Ｅｌ】</COL>射撃（弓構え中）'
new = '<COL DAEEF3>(Hu)</COL> <COL DAEEF3>(El)</COL> Shoot (when aiming bow)'
[[message]]
key = 'kcd_070'
old = '（未使用）'
new = '(unused)'
[[message]]
key = 'kcd_071'
old = '<COL DAEEF3>【Ｈｕ】</COL>矢の切替え　<COL DAEEF3>【Ｅｌ】</COL>癒しの装'
new = '<COL DAEEF3>(Hu)</COL> Switch Arrows  <COL DAEEF3>(El)</COL> Healing Dress'
[[message]]
key = 'kcd_072'
old = '<COL DAEEF3>【Ｐｒ】</COL><COL DAEEF3>【Ｓｏ】</COL>ロックオンモード切り替え（詠唱中）'
new = '<COL DAEEF3>(Pr)</COL> <COL DAEEF3>(So)</COL> Lock on mode switch (casting)'
[[message]]
key = 'kcd_073'
old = '''
<COL DAEEF3>【Ｆｉ】</COL>ガード　　　<COL DAEEF3>【Ｓｈ】</COL>シールドロック
<COL DAEEF3>【Ｓｅ】</COL>ロープ構え　<COL DAEEF3>【Ｈｉ】</COL>ウィル・スタンス'''
new = '''
<COL DAEEF3>(Fi)</COL> Guard  <COL DAEEF3>(Sh)</COL> Shield Lock
<COL DAEEF3>(Se)</COL> Rope Stance  <COL DAEEF3>(Hi)</COL> Will Stance'''
[[message]]
key = 'kcd_074'
old = '<COL DAEEF3>【Ｐｒ】</COL>フィールドシフト　<COL DAEEF3>【Ｓｈ】</COL>フォースバースト'
new = '<COL DAEEF3>(Pr)</COL> Field Shift  <COL DAEEF3>(Sh)</COL> Force Burst'
[[message]]
key = 'kcd_075'
old = '<COL DAEEF3>【Ｓｅ】</COL>転身　<COL DAEEF3>【Ｈｉ】</COL>避翻斬'
new = '<COL DAEEF3>(Se)</COL> Forward Roll  <COL DAEEF3>(Hi)</COL> Dodge Counter Slash'
[[message]]
key = 'kcd_076'
old = '<COL DAEEF3>【Ｓｅ】</COL>ロープ投げ（ロープ構え中）'
new = '<COL DAEEF3>(Se)</COL> Throw Rope (Rope Holding)'
[[message]]
key = 'kcd_077'
old = '<COL DAEEF3>【Ｈｕ】</COL>矢の装填　　<COL DAEEF3>【Ｅｌ】</COL>魔眼転移'
new = '<COL DAEEF3>(Hu)</COL> Reload Arrows  <COL DAEEF3>(El)</COL>魔眼転移'
[[message]]
key = 'kcd_078'
old = '<COL DAEEF3>【Ａｌ】</COL>エリクシル・チェンジ　<COL DAEEF3>【Ｓｐ】</COL>アタックブースト'
new = '<COL DAEEF3>(Al)</COL> Change Elixir  <COL DAEEF3>(Sp)</COL> Attack Boost'
[[message]]
key = 'kcd_079'
old = '''
<COL DAEEF3>【Ｈｕ】</COL><COL DAEEF3>【Ｅｌ】</COL>構え変更（弓構え中）
※この項目がブランクキーの場合、マウスホイール前後で構え変更'''
new = '''
<COL DAEEF3>(Hu)</COL> <COL DAEEF3>(El)</COL> Change Stance (when aiming bow)
※ If this is a blank key, change stance by mouse wheel forward/back'''
[[message]]
key = 'kcd_080'
old = '''
カスタムスキルの追加入力（連打 / 派生 等）
※この項目がブランクキーの場合、各カスタムスキル設定キーで追加入力'''
new = '''
Custom Skill Additional Input (repeated hits/derivative/etc)
※ If this is a blank key, additional input with each Custom Skill key setting'''
[[message]]
key = 'kcd_081'
old = '<COL DAEEF3>【Ｈｉ】</COL>ルイン・ブレード'
new = '<COL DAEEF3>(Hi)</COL> Ruin Blade'
[[message]]
key = 'kcd_082'
old = '<COL DAEEF3>【Ｈｉ】</COL>ウィル・マーカー（ウィル・スタンス中）'
new = '<COL DAEEF3>(Hi)</COL> Will Marker (in Will Stance)'
