[[message]]
key = 'np_msg_icon_new'
old = '最近公開'
[[message]]
key = 'np_msg_icon_recommended'
old = 'ボーナス'
new = 'Bonus'
[[message]]
key = 'np_msg_icon_party'
old = 'PT推奨'
new = 'Party'
[[message]]
key = 'np_msg_menutitle_area'
old = 'エリア選択メニュー'
new = 'Area Select Menu'
[[message]]
key = 'np_msg_text_area'
old = 'エリア選択'
new = 'Area Select'
[[message]]
key = 'np_msg_category_news'
old = '本日のパーティーボーナス'
new = "Today's Party Bonus"
[[message]]
key = 'np_msg_fit'
old = '推奨'
[[message]]
key = 'np_msg_lv'
old = 'LV.'
new = 'LV.'
[[message]]
key = 'np_msg_heard'
old = '目撃文'
[[message]]
key = 'np_msg_reward'
old = '初回報酬'
[[message]]
key = 'np_msg_limit'
old = '<DATE> まで'
new = 'Until <DATE>'
[[message]]
key = 'np_msg_sercret_reward'
old = '未公開報酬'
new = 'Hidden Reward'
[[message]]
key = 'np_msg_reward_rim'
old = '<VAL RIM>'
new = '<VAL RIM>'
[[message]]
key = 'np_msg_reward_g'
old = '<VAL GOLD>'
new = '<VAL GOLD>'
[[message]]
key = 'np_msg_reward_exp'
old = '<VAL XP>'
new = '<VAL XP>'
[[message]]
key = 'np_msg_nothing'
old = '---'
new = '---'
[[message]]
key = 'np_msg_dialog_jump_check'
old = '''
<NAME AREA> に転移します
必要リム：<VAL RIM>
所持リム：<VAL RIM>'''
new = '''
You will teleport to <NAME AREA>.
Rift Crystal Cost: <VAL RIM>
Rift Crystal Total: <VAL RIM>'''
[[message]]
key = 'np_msg_dialoig_jump_norim'
old = '''
リムが不足しています
必要リム：<VAL RIM>
所持リム：<VAL RIM>'''
new = '''
You do not have enough Rift Crystals.
Rift Crystal Cost: <VAL RIM>
Rift Crystal Total: <VAL RIM>'''
[[message]]
key = 'np_msg_decision_decide'
old = '決定'
new = 'OK'
[[message]]
key = 'np_msg_decision_cansel'
old = 'キャンセル'
new = 'Cancel'
[[message]]
key = 'np_msg_article_event'
old = 'イベント情報'
new = 'Event Information'
[[message]]
key = 'np_msg_title'
old = 'レスタニアニュース'
new = 'Lestania News'
[[message]]
key = 'np_msg_guid_others'
old = '他のイベント情報'
new = 'Other Event Information'
[[message]]
key = 'np_msg_state_partin'
old = '参加中'
new = 'Participating'
[[message]]
key = 'np_msg_state_nopartin'
old = '参加受付中'
new = 'Accepting Participants'
[[message]]
key = 'np_msg_subtitle_event'
old = 'イベント情報'
new = 'Information'
[[message]]
key = 'np_msg_tab_ranking'
old = 'ランキング'
new = 'Ranking'
[[message]]
key = 'np_msg_rab_reward'
old = '報酬'
new = 'Rewards'
[[message]]
key = 'np_msg_pt'
old = 'pt'
new = 'pt'
[[message]]
key = 'np_msg_ranking'
old = 'ランキング'
new = 'Ranking'
[[message]]
key = 'np_msg_name'
old = '名前'
new = 'Name'
[[message]]
key = 'np_msg_clan'
old = 'クラン'
new = 'Clan'
[[message]]
key = 'np_msg_reward_boarder'
old = '累計スコア報酬'
new = 'Total Score Rewards'
[[message]]
key = 'np_msg_reward_ranking'
old = 'ランキング報酬'
new = 'Ranking Reward'
[[message]]
key = 'np_msg_rate'
old = '<VAL>'
new = '<VAL>'
[[message]]
key = 'np_msg_rate_period'
old = '<VAL>位～<VAL>位'
[[message]]
key = 'np_msg_noreward'
old = '報酬なし'
[[message]]
key = 'np_msg_update'
old = '集計日: <DATE>'
new = 'Tallied: <DATE>'
[[message]]
key = 'np_msg_starting'
old = '開始直後'
[[message]]
key = 'np_msg_hoursago'
old = '<VAL> 時間前'
[[message]]
key = 'np_msg_term'
old = '<DATE> - <DATE>'
new = '<DATE> - <DATE>'
[[message]]
key = 'np_msg_pt_period'
old = '<VAL>pt  - <VAL>pt'
new = '<VAL>pt - <VAL>pt'
[[message]]
key = 'np_msg_icon_ending'
old = '終了直前'
new = 'Ending'
[[message]]
key = 'np_msg_noquickpt'
old = '新聞クイックパーティは現在利用できません'
[[message]]
key = 'np_msg_mypoint'
old = 'スコア'
new = 'Score'
[[message]]
key = 'np_msg_area_select'
old = 'Area Select'
new = 'Area Select'
[[message]]
key = 'np_msg_condition'
old = '状況'
new = 'Conditions'
[[message]]
key = 'np_msg_period'
old = '配信期間'
new = 'Event Time'
[[message]]
key = 'np_msg_period_start'
old = '<DATE> から'
new = 'From <DATE>'
[[message]]
key = 'np_msg_period_end'
old = '<DATE> まで'
new = 'until <DATE>'
[[message]]
key = 'np_msg_rank'
old = '位'
[[message]]
key = 'np_msg_abst'
old = '概要'
new = 'Overview'
[[message]]
key = 'np_msg_entry_point'
old = '参加場所'
new = 'Entry Location'
[[message]]
key = 'np_msg_reward_info'
old = 'ハイスコア報酬例'
new = 'High Score Example Rewards'
[[message]]
key = 'np_msg_func_disable'
old = 'この機能は現在使用できません'
[[message]]
key = 'np_msg_ability_reward'
old = 'アビリティ：'
new = 'Augment: '
[[message]]
key = 'np_msg_total'
old = 'Total'
new = 'Total'
[[message]]
key = 'np_msg_no_ranking'
old = '現在ランキングは発表されていません'
new = 'Current rankings have not been published'
[[message]]
key = 'np_msg_no_quest'
old = '現在クエストの配信はありません'
[[message]]
key = 'np_msg_dailybonus'
old = '''
■<COL ffdc78>《本日のパーティーボーナス》</COL>詳細

＜ボーナス発生条件＞
　・対象のワールドクエストを他のプレイヤーと
　　パーティーを組んで<VAL>回クリア
　　（ポーンとの混成パーティーＯＫ）

＜ボーナス内容＞
　・クエスト報酬（XP/G/R/AP）にボーナス倍率
　・レベルや進行度の差による報酬ペナルティ無効

　※対象クエストはデイリーで変化します
　※各クエストの受注画面、ログの報酬欄にて
　　ボーナス詳細が確認できます'''
new = '''
■ <COL ffdc78>"Today's Party Bonus"</COL> Details

Bonus Condition:
　・Complete the target World Quest with other
　　players. With a full party, clear the
　　quest <VAL> times.
　　(Hybrid party with player and pawn is OK)

Bonus Content:
　・The quest reward (XP/G/R/AP) will be
　　increased.
　・The bonus may be penalized/disabled if
　　level difference is high/quests are not
　　on the same progress.

　※Target quest will change daily.
　※Within the quest log, you can check the
　　details of the bonuses.'''
[[message]]
key = 'np_msg_dailybonus_bo'
old = '''
■<COL ffdc78>《本日のパーティーボーナス》</COL>詳細

＜ボーナス発生条件＞
　・対象のワールドクエストを他のプレイヤーと
　　パーティーを組んで<VAL>回クリア
　　（ポーンとの混成パーティーＯＫ）

＜ボーナス内容＞
　<COL ffdc78>★本日は《ブラッドオーブ</COL><VAL BO><COL ffdc78>》追加！</COL>
　・クエスト報酬（XP/G/R/AP）にボーナス倍率
　・レベルや進行度の差による報酬ペナルティ無効

　※対象クエストはデイリーで変化します
　※各クエストの受注画面、ログの報酬欄にて
　　ボーナス詳細が確認できます'''
new = '''
■<COL ffdc78>"Today's Party Bonus"</COL> Details

＜Bonus Condition＞
　・Complete the target World Quest with other
　　players. With a full party, clear the
　　quest <VAL> times.
　　(Hybrid party with players and pawns is OK)

＜Bonus Content＞
　<COL ffdc78>★Today, "</COL><VAL BO><COL ffdc78> Blood Orbs" will be added!</COL>
　・The quest reward (XP/G/R/AP) will be increased.
　・The bonus may be penalized/disabled if level
　　difference is high/quests are not
　　on the same progress.

　※Target quest will change daily.
　※Within the quest log, you can check the
　　details of the bonuses.'''
[[message]]
key = 'np_msg_guide_partybonus'
old = 'パーティーボーナス情報'
new = 'Party Bonus Information'
[[message]]
key = 'np_msg_just'
old = '適正'
[[message]]
key = 'np_msg_pt_period_more'
old = '<VAL>pt 以上'
new = '<VAL>pt or more'
[[message]]
key = 'np_msg_state_preparation'
old = '開戦準備中'
new = 'Preparing'
[[message]]
key = 'np_msg_state_ranking'
old = '戦果分析中'
new = 'Veteran Analysis'
[[message]]
key = 'np_msg_state_receiving'
old = '報酬配分中'
new = 'Reward Claim'
[[message]]
key = 'np_msg_reward_item_num'
old = ' × '
new = ' x'
[[message]]
key = 'np_msg_no_gm'
old = '現在開催されていません'
[[message]]
key = 'np_msg_event_select'
old = 'Event Select'
[[message]]
key = 'np_msg_andmore'
old = 'and more...'
new = 'and more...'
[[message]]
key = 'np_msg_order_info'
old = '受注条件情報'
new = 'Accept Conditions'
[[message]]
key = 'np_msg_header_gm'
old = 'Grand Mission'
new = 'Grand Mission'
[[message]]
key = 'np_msg_header_wm'
old = 'War Mission'
new = 'War Mission'
[[message]]
key = 'np_msg_dp_info_title'
old = 'ポイント獲得状況'
new = 'Point Acquisition Status'
[[message]]
key = 'np_msg_dp_info_name_pos'
old = '<UNTN DP>'
new = '<UNTN DP>'
[[message]]
key = 'np_msg_dp_info_name_acc'
old = 'ウォーミッション累積ポイント'
new = 'War Mission Accumulated Points'
[[message]]
key = 'np_msg_dp_info_att_cap'
old = '注意事項'
new = 'Important Note'
[[message]]
key = 'np_msg_dp_info_att_inf'
old = '''
<UNTN DP>、ウォーミッション累積ポイントは
次回のコンテンツ開催時にリセットされます'''
[[message]]
key = 'np_msg_state_receiving_wm'
old = 'ランキング確定'
[[message]]
key = 'np_msg_wm_limited_condition_open'
old = '期間限定開催！'
[[message]]
key = 'np_msg_mypoint_wm'
old = 'ウォーミッション累積<UNIT PT>'
new = 'Cumulative War Mission <UNIT PT>'
[[message]]
key = 'np_msg_period_01'
old = '本作戦進行期間'
[[message]]
key = 'np_msg_period_02'
old = '戦果分析期間'
[[message]]
key = 'np_msg_period_03'
old = '報酬配分期間'
[[message]]
key = 'np_msg_wm_limited_multi_open'
old = '詳しくはコンテンツ窓口を確認してください'
