[[message]]
key = 'item_name'
old = '名称'
new = 'Name'
[[message]]
key = 'item_category'
old = 'カテゴリ'
new = 'Category'
[[message]]
key = 'item_max_possess'
old = '所持最大数'
new = 'Stack Size'
[[message]]
key = 'iitem_con'
old = 'アイコン'
new = 'Icon'
[[message]]
key = 'item_caption'
old = '説明'
new = 'Description'
[[message]]
key = 'item_grade'
old = 'グレード'
new = 'Grade'
[[message]]
key = 'item_rank'
old = 'アイテムランク'
new = 'Item Rank'
[[message]]
key = 'item_effect'
old = '効能'
new = 'Effect'
[[message]]
key = 'item_use_limit'
old = '使用制限'
new = 'Use Limit'
[[message]]
key = 'item_purchase_price'
old = '購入額'
new = 'Purchase Price'
[[message]]
key = 'item_sell_price'
old = '売却額'
new = 'Sell Value'
[[message]]
key = 'item_max_price'
old = 'バザー取引最高額'
new = 'Maximum Bazaar Price'
[[message]]
key = 'item_minimum_price'
old = 'バザー取引最低額'
new = 'Minimum Bazaar Price'
[[message]]
key = 'item_sell_ok'
old = '売却OK'
new = 'Sale OK'
[[message]]
key = 'item_bazaar_ok'
old = 'バザー出品OK'
new = 'Bazaar Exhibit OK'
[[message]]
key = 'item_material'
old = '素材分類'
[[message]]
key = 'item_levelcap'
old = '装備制限ジョブレベル'
[[message]]
key = 'item_equip_clast'
old = '装着中クレスト'
[[message]]
key = 'weight'
old = '重量'
new = 'Weight'
[[message]]
key = 'item_max_equip'
old = '最大装着数'
[[message]]
key = 'item_weapon_type'
old = '武器タイプ'
new = 'Weapon Type'
[[message]]
key = 'physical_attack'
old = '物理攻撃力'
new = 'Physical Attack'
[[message]]
key = 'magic_attack'
old = '魔法攻撃力'
new = 'Magick Attack'
[[message]]
key = 'item_phisical_property'
old = '物理属性'
new = 'Physical Attribute'
[[message]]
key = 'item_magic_property'
old = '魔法属性'
new = 'Magick Attribute'
[[message]]
key = 'item_strength'
old = '吹き飛ばし力'
new = 'Blow Power'
[[message]]
key = 'item_faint'
old = '気絶攻力'
new = 'Knockout Power'
[[message]]
key = 'item_chance'
old = 'チャンス攻力'
new = 'Chance Attack'
[[message]]
key = 'item_stagger'
old = '盾ガード値'
new = 'Guard Power'
[[message]]
key = 'item_num_of_load'
old = '矢装填数'
new = 'Max Loaded Arrows'
[[message]]
key = 'weakness_attack_subhuman'
old = '対敵特効【亜人】'
new = 'Demihuman Slayer'
[[message]]
key = 'weakness_attack_beast'
old = '対敵特効【獣】'
new = 'Beast Slayer'
[[message]]
key = 'weakness_attack_ogre'
old = '対敵特効【鬼人】'
new = 'Ogre Slayer'
[[message]]
key = 'weakness_attack_undead'
old = '対敵特効【腐死】'
new = 'Undead Slayer'
[[message]]
key = 'weakness_attack_skeleton'
old = '対敵特効【骸骨】'
new = 'Skeleton Slayer'
[[message]]
key = 'weakness_attack_winged'
old = '対敵特効【有翼】'
new = 'Winged Slayer'
[[message]]
key = 'weakness_attack_giant'
old = '対敵特効【巨人】'
new = 'Giant Slayer'
[[message]]
key = 'weakness_attack_softbody'
old = '対敵特効【軟体】'
new = 'Formless Slayer'
[[message]]
key = 'weakness_attack_soul'
old = '対敵特効【霊体】'
new = 'Spirit Slayer'
[[message]]
key = 'weakness_attack_curse'
old = '対敵特効【呪詛】'
new = 'Cursed Slayer'
[[message]]
key = 'weakness_attack_golem'
old = '対敵特効【造魔】'
new = 'Golem Slayer'
[[message]]
key = 'weakness_attack_human'
old = '対敵特効【人間】'
new = 'Human Slayer'
[[message]]
key = 'weakness_attack_alchemy'
old = '対敵特効【錬金】'
new = 'Alchemy Slayer'
[[message]]
key = 'weakness_attack_dragon'
old = '対敵特効【竜族】'
new = 'Dragon Slayer'
[[message]]
key = 'weakness_attack_demonic'
old = '対敵特効【魔族】'
new = 'Demon Slayer'
[[message]]
key = 'give_poison'
old = '与【毒】蓄積値'
new = 'Inflict Poison'
[[message]]
key = 'give_torpor'
old = '与【遅延】蓄積値'
new = 'Inflict Torpor'
[[message]]
key = 'give_sleep'
old = '与【睡眠】蓄積値'
new = 'Inflict Sleep'
[[message]]
key = 'give_drenching'
old = '与【水濡れ】蓄積値'
new = 'Inflict Drenching'
[[message]]
key = 'give_tarring'
old = '与【油濡れ】蓄積値'
new = 'Inflict Tarring'
[[message]]
key = 'give_stifling'
old = '与【スキル封印】蓄積値'
new = 'Inflict Skill Stifling'
[[message]]
key = 'give_softener'
old = '与【軟化】蓄積値'
new = 'Inflict Frail'
[[message]]
key = 'give_petrify'
old = '与【石化】蓄積値'
new = 'Inflict Petrification'
[[message]]
key = 'give_gold'
old = '与【黄金化】蓄積値'
new = 'Inflict Golden'
[[message]]
key = 'give_cought_fire'
old = '与【延焼】蓄積値'
new = 'Inflict Catching Fire'
[[message]]
key = 'give_frozen'
old = '与【凍結】蓄積値'
new = 'Inflict Frozen Solid'
[[message]]
key = 'give_thundershock'
old = '与【感電】蓄積値'
new = 'Inflict Shock'
[[message]]
key = 'give_holy_drain'
old = '与【聖吸】蓄積値'
new = 'Inflict Holy Drain'
[[message]]
key = 'give_darkness_mist'
old = '与【闇霧】蓄積値'
new = 'Inflict Blind'
[[message]]
key = 'give_fire_resist_down'
old = '与【炎防低下】蓄積値'
new = 'Inflict Fire Resist Down'
[[message]]
key = 'give_ice_resist_down'
old = '与【氷防低下】蓄積値'
new = 'Inflict Ice Resist Down'
[[message]]
key = 'give_thunder_resist_down'
old = '与【雷防低下】蓄積値'
new = 'Inflict Thunder Resist Down'
[[message]]
key = 'give_holy_resist_down'
old = '与【聖防低下】蓄積値'
new = 'Inflict Holy Resist Down'
[[message]]
key = 'give_dark_resist_down'
old = '与【闇防低下】蓄積値'
new = 'Inflict Dark Resist Down'
[[message]]
key = 'give_physical_attack_down'
old = '与【物攻低下】蓄積値'
new = 'Inflict Physical Atk. Down'
[[message]]
key = 'give_physical_difense_down'
old = '与【物防低下】蓄積値'
new = 'Inflict Physical Def. Down'
[[message]]
key = 'give_magic_attack_down'
old = '与【魔攻低下】蓄積値'
new = 'Inflict Magick Atk. Down'
[[message]]
key = 'give_magic_difense_down'
old = '与【魔防低下】蓄積値'
new = 'Inflict Magick Def. Down'
[[message]]
key = 'phisical_difence'
old = '物理防御力'
new = 'Physical Defense'
[[message]]
key = 'magic_difence'
old = '魔法防御力'
new = 'Magick Defense'
[[message]]
key = 'endurance'
old = '耐久力'
new = 'Endurance'
[[message]]
key = 'healing'
old = '生命治癒力'
new = 'Healing Power'
[[message]]
key = 'max_health'
old = '最大体力'
new = 'Max Health'
[[message]]
key = 'max_stamina'
old = '最大スタミナ'
new = 'Max Stamina'
[[message]]
key = 'resist_fire'
old = '炎耐性'
new = 'Fire Resist'
[[message]]
key = 'resist_ice'
old = '氷耐性'
new = 'Ice Resist'
[[message]]
key = 'resist_thunder'
old = '雷耐性'
new = 'Thunder Resist'
[[message]]
key = 'resist_holy'
old = '聖耐性'
new = 'Holy Resist'
[[message]]
key = 'resist_dark'
old = '闇耐性'
new = 'Dark Resist'
[[message]]
key = 'resist_cought_fire'
old = '延焼耐性'
new = 'Resist Catching Fire'
[[message]]
key = 'resist_frozen'
old = '凍結耐性'
new = 'Resist Frozen Solid'
[[message]]
key = 'resist_thundershock'
old = '感電耐性'
new = 'Resist Shock'
[[message]]
key = 'resist_holy_drain'
old = '聖吸耐性'
new = 'Resist Holy Drain'
[[message]]
key = 'resist_darkness_mist'
old = '闇霧耐性'
new = 'Resist Blind'
[[message]]
key = 'resist_poison'
old = '毒耐性'
new = 'Resist Poison'
[[message]]
key = 'resist_torpor'
old = '遅延耐性'
new = 'Resist Torpor'
[[message]]
key = 'resist_sleep'
old = '睡眠耐性'
new = 'Resist Sleep'
[[message]]
key = 'resist_faint'
old = '気絶耐性'
new = 'Resist Knockout'
[[message]]
key = 'resist_drenching'
old = '水濡れ耐性'
new = 'Resist Drenching'
[[message]]
key = 'resist_tarring'
old = '油濡れ耐性'
new = 'Resist Tarring'
[[message]]
key = 'resist_stifling'
old = 'スキル封印耐性'
new = 'Resist Skill Stifling'
[[message]]
key = 'resist_curse'
old = '呪い耐性'
new = 'Resist Curse'
[[message]]
key = 'resist_softener'
old = '軟化耐性'
new = 'Resist Frail'
[[message]]
key = 'resist_petrify'
old = '石化耐性'
new = 'Resist Petrification'
[[message]]
key = 'resist_gold'
old = '黄金化耐性'
new = 'Resist Golden'
[[message]]
key = 'resist_fire_resist_down'
old = '炎防低下耐性'
new = 'Resist Fire Resist Down'
[[message]]
key = 'resist_ice_resist_down'
old = '氷防低下耐性'
new = 'Resist Ice Resist Down'
[[message]]
key = 'resist_thunder_resist_down'
old = '雷防低下耐性'
new = 'Resist Thunder Resist Down'
[[message]]
key = 'resist_holy_resist_down'
old = '聖防低下耐性'
new = 'Resist Holy Resist Down'
[[message]]
key = 'resist_dark_resist_down'
old = '闇防低下耐性'
new = 'Resist Dark Resist Down'
[[message]]
key = 'resist_physical_attack_down'
old = '物攻低下耐性'
new = 'Resist Physical Atk. Down'
[[message]]
key = 'resist_physical_difense_down'
old = '物防低下耐性'
new = 'Resist Physical Def. Down'
[[message]]
key = 'resist_magic_attack_down'
old = '魔攻低下耐性'
new = 'Resist Magick Atk. Down'
[[message]]
key = 'resist_magic_difense_down'
old = '魔防低下耐性'
new = 'Resist Magick Def. Down'
[[message]]
key = 'item_categoryname_use'
old = '消費'
new = 'Consumable'
[[message]]
key = 'item_categoryname_material'
old = '素材'
new = 'Material'
[[message]]
key = 'item_categoryname_weapon'
old = '装備品'
new = 'Equipment'
[[message]]
key = 'item_categoryname_key'
old = 'キーアイテム'
new = 'Key Item'
[[message]]
key = 'item_categoryname_special'
old = 'ジョブ専用'
new = 'Job'
[[message]]
key = 'material_cateforyname_metal'
old = '金属'
new = 'Metal'
[[message]]
key = 'material_cateforyname_mineral'
old = '鉱石'
new = 'Ore'
[[message]]
key = 'material_cateforyname_sand'
old = '砂材'
new = 'Sand'
[[message]]
key = 'material_cateforyname_cloth'
old = '布'
new = 'Cloth'
[[message]]
key = 'material_cateforyname_string'
old = '糸'
new = 'String'
[[message]]
key = 'material_cateforyname_fur'
old = '毛'
new = 'Fur'
[[message]]
key = 'material_cateforyname_pelt'
old = '皮'
new = 'Skin'
[[message]]
key = 'material_cateforyname_bone'
old = '骨'
new = 'Bone'
[[message]]
key = 'material_cateforyname_fang'
old = '牙'
new = 'Fang'
[[message]]
key = 'material_cateforyname_horn'
old = '角'
new = 'Horn'
[[message]]
key = 'material_cateforyname_shell'
old = '貝'
new = 'Shell'
[[message]]
key = 'material_cateforyname_feather'
old = '羽'
new = 'Feather'
[[message]]
key = 'material_cateforyname_jewel'
old = '宝石'
new = 'Gem'
[[message]]
key = 'material_cateforyname_grass'
old = '草'
new = 'Grass'
[[message]]
key = 'material_cateforyname_flower'
old = '花'
new = 'Flower'
[[message]]
key = 'material_cateforyname_seed'
old = '実'
new = 'Seed'
[[message]]
key = 'material_cateforyname_mushroom'
old = 'キノコ'
new = 'Mushroom'
[[message]]
key = 'material_cateforyname_wood'
old = '木材'
new = 'Lumber'
[[message]]
key = 'material_cateforyname_liquid'
old = '液体'
new = 'Liquid'
[[message]]
key = 'material_cateforyname_scroll'
old = '巻物'
new = 'Scroll'
[[message]]
key = 'material_cateforyname_alchemy'
old = '錬金材'
new = 'Alchemy Material'
[[message]]
key = 'material_cateforyname_meat'
old = '肉'
new = 'Meat'
[[message]]
key = 'material_cateforyname_etc'
old = 'その他'
new = 'Other'
[[message]]
key = 'material_large_cateforyname_crest'
old = 'クレスト'
new = 'Crest'
[[message]]
key = 'material_large_cateforyname_special'
old = '精錬材'
new = 'Refining Material'
[[message]]
key = 'material_cateforyname_for_w'
old = '武器用'
new = 'For Weapon'
[[message]]
key = 'material_cateforyname_for_g'
old = '防具用'
new = 'For Armor'
[[message]]
key = 'material_cateforyname_dyes'
old = '染料'
new = 'Dye'
[[message]]
key = 'material_large_cateforyname_inorgan'
old = '無機物'
new = 'Inorganic'
[[message]]
key = 'material_large_cateforyname_plant'
old = '植物'
new = 'Plant'
[[message]]
key = 'material_large_cateforyname_animal'
old = '動物'
new = 'Animal'
[[message]]
key = 'material_large_cateforyname_sewing'
old = '裁縫'
new = 'Sewing'
[[message]]
key = 'material_large_cateforyname_artifac'
old = '特殊'
new = 'Special'
[[message]]
key = 'parts_main_weapon'
old = 'メイン武器'
new = 'Main Weapon'
[[message]]
key = 'parts_sub_weapon'
old = 'サブ武器'
new = 'Sub Weapon'
[[message]]
key = 'parts_head_armor'
old = '頭防具'
new = 'Head Armor'
[[message]]
key = 'parts_body_armor'
old = '胴アーマー'
new = 'Body Armor'
[[message]]
key = 'parts_body_wear'
old = '胴ウェア'
new = 'Body Clothing'
[[message]]
key = 'parts_arm_armor'
old = '腕防具'
new = 'Arm Armor'
[[message]]
key = 'parts_leg_armor'
old = '脚アーマー'
new = 'Leg Armor'
[[message]]
key = 'parts_leg_wear'
old = '脚ウェア'
new = 'Legwear'
[[message]]
key = 'parts_overwear'
old = 'オーバーウェア'
new = 'Overwear'
[[message]]
key = 'parts_jewelry'
old = 'ジュエリー'
new = 'Jewelry'
[[message]]
key = 'parts_costume'
old = '一式装備'
new = 'Ensemble'
[[message]]
key = 'item_tower_shield_collect_point'
old = 'フォースストック数'
new = 'Max Force Stock'
[[message]]
key = 'item_craft_gained_exp'
old = '装備強化ポイント'
new = 'Enhancement'
[[message]]
key = 'character_name'
old = '名前'
new = 'Name'
[[message]]
key = 'character_sex'
old = '性別'
new = 'Gender'
[[message]]
key = 'character_height'
old = '身長'
new = 'Height'
[[message]]
key = 'character_hp'
old = '体力'
new = 'Health Points'
[[message]]
key = 'character_st'
old = 'スタミナ'
new = 'Stamina'
[[message]]
key = 'character_number_of_ability_set'
old = 'アビリティセット枠'
[[message]]
key = 'character_number_of_use_item'
old = '消費アイテム枠'
new = 'Usable Bag Slot'
[[message]]
key = 'character_number_of_material'
old = '素材アイテム枠'
new = 'Material Bag Slot'
[[message]]
key = 'character_number_of_weapon'
old = '装備品アイテム枠'
new = 'Equipment Bag Slot'
[[message]]
key = 'character_number_of_key_item'
old = 'キーアイテム'
new = 'Key Item'
[[message]]
key = 'character_number_of_special_item'
old = 'ジョブ専用アイテム枠'
new = 'Job Item Bag Slot'
[[message]]
key = 'character_total_bo'
old = 'ブラッドオーブ総献上量'
new = 'Blood Orb Total'
[[message]]
key = 'pawn_craft_rank'
old = 'クラフトレベル'
new = 'Craft Level'
[[message]]
key = 'pawn_craft_xp'
old = 'クラフト経験値'
new = 'Craft Experience'
[[message]]
key = 'pawn_craft_point'
old = 'クラフトポイント'
new = 'Craft Point'
[[message]]
key = 'pawn_craftskill_time'
old = 'クラフトスキル：生産作業スピード'
new = 'Craft Skill: Production Speed'
[[message]]
key = 'pawn_craftskill_powerup'
old = 'クラフトスキル：装備の強化技術'
new = 'Craft Skill: Equipment Enhancement'
[[message]]
key = 'pawn_craftskill_quality'
old = 'クラフトスキル：高品質装備の作成力'
new = 'Craft Skill: Equipment Quality'
[[message]]
key = 'pawn_craftskill_number'
old = 'クラフトスキル：消耗品の生産数アップ'
new = 'Craft Skill: Consumable Quantity'
[[message]]
key = 'pawn_craftskill_cost'
old = 'クラフトスキル：コストパフォーマンス'
new = 'Craft Skill: Cost Performance'
[[message]]
key = 'pawn_craft_promote'
old = '昇格試験の段階'
[[message]]
key = 'pawn_craft_rank_cap'
old = 'クラフトレベルキャップ'
new = 'Craft Level Cap'
[[message]]
key = 'pawn_number_of_support'
old = 'サポート回数'
[[message]]
key = 'pawn_number_of_adventure'
old = '冒険回数'
[[message]]
key = 'character_job_level'
old = 'ジョブレベル'
new = 'Job Level'
[[message]]
key = 'character_job_xp'
old = 'ジョブ経験値'
new = 'Job Experience'
[[message]]
key = 'character_tiredness'
old = '疲労攻力'
new = 'Exhaust Attack'
[[message]]
key = 'character_jp'
old = 'ジョブポイント'
new = 'Job Point'
[[message]]
key = 'character_phisical_attack'
old = '筋力'
new = 'Strength'
[[message]]
key = 'character_magic_attack'
old = '魔力'
new = 'Magick'
[[message]]
key = 'dye_color_black'
old = '黒'
new = 'Black'
[[message]]
key = 'dye_color_all'
old = 'オールマイティ'
new = 'Almighty'
[[message]]
key = 'dye_color_default'
old = 'デフォルト'
new = 'Default'
[[message]]
key = 'dye_color_red'
old = '赤'
new = 'Red'
[[message]]
key = 'dye_color_green'
old = '緑'
new = 'Green'
[[message]]
key = 'dye_color_blue'
old = '青'
new = 'Blue'
[[message]]
key = 'dye_color_yellow'
old = '黄'
new = 'Yellow'
[[message]]
key = 'dye_color_pink'
old = '桃'
new = 'Pink'
[[message]]
key = 'item_shield_stamina_resist'
old = '盾スタミナ軽減値'
new = 'Blocking Stamina Reduction'
[[message]]
key = 'param_msg_item_use'
old = '消費アイテム'
new = 'Usable Item'
[[message]]
key = 'param_msg_posnum'
old = '所持数'
new = 'Amount'
[[message]]
key = 'param_msg_anti_em'
old = '対敵'
new = 'Slayer'
[[message]]
key = 'param_msg_tolerance'
old = '耐性'
new = 'Resist'
[[message]]
key = 'param_msg_accumulation'
old = '蓄積'
new = 'Inflict'
[[message]]
key = 'param_msg_healing'
old = '体力回復'
new = 'Health Recovery'
[[message]]
key = 'param_msg_stamina_recovery'
old = 'スタミナ回復'
new = 'Stamina Recovery'
[[message]]
key = 'param_msg_bazaar_ok'
old = 'OK'
new = 'OK'
[[message]]
key = 'param_msg_bazaar_ng'
old = 'NG'
new = 'NO'
[[message]]
key = 'param_msg_alljob_equip'
old = '全ジョブ装備可能'
new = 'All vocations can equip'
[[message]]
key = 'param_msg_only_m'
old = '男性専用'
new = 'Male Only'
[[message]]
key = 'param_msg_only_f'
old = '女性専用'
new = 'Female Only'
[[message]]
key = 'param_msg_item_money'
old = '通貨'
new = 'Currency'
[[message]]
key = 'param_msg_item_rental'
old = 'レンタルチケット'
new = 'Rental Ticket'
[[message]]
key = 'param_msg_item_sample'
old = '試供品'
new = 'Sample'
[[message]]
key = 'param_msg_posnum_gs'
old = '所持数：<VAL GS>'
new = 'Amount: <VAL GS>'
[[message]]
key = 'param_msg_posnum_gold'
old = '所持数：<VAL GOLD>'
new = 'Amount: <VAL GOLD>'
[[message]]
key = 'param_msg_posnum_rim'
old = '所持数：<VAL RIM>'
new = 'Amount: <VAL RIM>'
[[message]]
key = 'param_msg_posnum_bo'
old = '所持数：<VAL BO>'
new = 'Amount: <VAL BO>'
[[message]]
key = 'parts_lantern'
old = 'ランタン'
new = 'Lantern'
[[message]]
key = 'param_msg_posnum_ticket'
old = '所持数：<VAL>枚'
new = 'Amount: <VAL>'
[[message]]
key = 'weakness_attack_erosion'
old = '対敵特効【侵食】'
new = 'Corrupted Slayer'
[[message]]
key = 'param_msg_item_furniture'
old = '家具'
new = 'Furniture'
[[message]]
key = 'resist_erosion'
old = '侵食耐性'
new = 'Resist Corruption'
[[message]]
key = 'resist_item_sealed'
old = 'アイテム封印耐性'
new = 'Resist Item Seal'
[[message]]
key = 'material_large_cateforyname_judgment'
old = '鑑定アイテム'
new = 'Appraised Item'
[[message]]
key = 'material_large_cateforyname_material_area'
old = '地域素材'
new = 'Regional Material'
[[message]]
key = 'material_cateforyname_all'
old = 'すべて'
new = 'All'
[[message]]
key = 'param_msg_item_point'
old = 'ポイント'
new = 'Point'
[[message]]
key = 'weakness_attack_armed'
old = '対敵特効【戦甲】'
new = 'War-Ready Slayer'
[[message]]
key = 'material_cateforyname_add_status'
old = '特質錬石'
new = 'Slayer Stone'
[[message]]
key = 'resist_magma'
old = 'マグマ耐性'
new = 'Magma Resist'
[[message]]
key = 'material_cateforyname_pspskill'
old = 'ポーンの閃き'
new = 'Pawn Inspiration'
[[message]]
key = 'material_cateforyname_draskill'
old = 'ドラゴンアビリティ'
