[[message]]
key = 'party_list_title_en'
old = 'Party List'
[[message]]
key = 'party_list_title_jp'
old = 'パーティー管理'
new = 'Party List'
[[message]]
key = 'party_list_invite'
old = 'パーティーへの招待がきています'
new = 'You have been sent a party invite.'
[[message]]
key = 'party_list_time'
old = '<VAL>:<VAL>'
[[message]]
key = 'party_list_member'
old = 'パーティーメンバー'
new = 'Party Members'
[[message]]
key = 'party_list_mpawn'
old = 'メインポーン'
new = 'Main Pawns'
[[message]]
key = 'party_list_spawn'
old = 'サポートポーン'
new = 'Support Pawns'
[[message]]
key = 'party_list_pl_search'
old = 'プレイヤー検索'
new = 'Player Search'
[[message]]
key = 'party_list_q_party'
old = 'クイックパーティー'
new = 'Quick Party'
[[message]]
key = 'party_list_leave'
old = 'パーティーから抜ける'
new = 'Leave'
[[message]]
key = 'party_list_dissolution'
old = 'パーティーを解散する'
new = 'Disband'
[[message]]
key = 'party_list_submenu'
old = 'サブメニュー'
new = 'Submenu'
[[message]]
key = 'party_list_quickp_start'
old = 'クイックパーティー開始'
[[message]]
key = 'party_list_settings'
old = '設定の編集'
[[message]]
key = 'party_list_name'
old = '名前'
new = 'Name'
[[message]]
key = 'party_list_job'
old = 'ジョブレベル'
new = 'Job Level'
[[message]]
key = 'party_list_lobby'
old = 'ワールド'
new = 'World'
[[message]]
key = 'party_list_location'
old = 'Location'
[[message]]
key = 'party_list_clan'
old = 'クラン'
new = 'Clan'
[[message]]
key = 'party_list_state'
old = '状態'
new = 'Status'
[[message]]
key = 'party_list_comment'
old = 'コメント'
new = 'Comment'
[[message]]
key = 'party_list_search'
old = '検索する'
new = 'Search'
[[message]]
key = 'party_list_object'
old = 'Object'
[[message]]
key = 'party_list_pawn'
old = 'Pawn'
[[message]]
key = 'party_list_area_name'
old = '<NAME AREA>'
[[message]]
key = 'party_list_search_now'
old = '検索中です'
[[message]]
key = 'party_list_settings_err'
old = '条件を設定してください'
new = 'Please enter search criteria.'
[[message]]
key = 'party_list_notfound_player'
old = '要請を出せる相手がいませんでした'
[[message]]
key = 'party_list_notfound_party'
old = '参加出来るパーティーがありませんでした'
[[message]]
key = 'party_list_inviting'
old = '（招待中）'
new = '(Pending)'
[[message]]
key = 'party_list_guide_switch'
old = '表示切り替え'
[[message]]
key = 'party_list_count'
old = '冒険／クラフト残り回数'
new = 'Adventure / Craft Left'
[[message]]
key = 'party_list_pawn_joblv'
old = 'ジョブ／クラフトレベル'
new = 'Job / Craft Level'
[[message]]
key = 'party_list_main_pawn_count'
old = '契約状況：'
new = 'Contracts:'
[[message]]
key = 'party_list_support_pawn_count'
old = '雇用状況：'
new = 'Contracts:'
[[message]]
key = 'party_list_notfound_main_pawn'
old = 'ポーンと契約していません'
new = 'You have not made a contract with any pawns'
[[message]]
key = 'party_list_notfound_support_pawn'
old = 'ポーンを雇用していません'
new = 'You have not hired any pawns'
[[message]]
key = 'party_list_party_link'
old = '（合流中）'
[[message]]
key = 'party_list_simple_req_btn'
old = '簡易要請'
new = 'Simple Request'
[[message]]
key = 'party_list_pt_search'
old = 'パーティー検索'
new = 'Party Search'
[[message]]
key = 'party_list_pl_search_notfound'
old = '一致する情報は見つかりませんでした'
[[message]]
key = 'party_list_pl_name_empty'
old = '(指定なし)'
[[message]]
key = 'party_list_btn_dra_skill'
old = 'ドラゴンアビリティ情報'
