[[message]]
key = 'RIM_POP_MSG_HEADER_M_HEADER'
old = '検索条件'
new = 'Search Criteria'
[[message]]
key = 'RIM_POP_MSG_CHARACTER_M_JOB'
old = 'ジョブ'
new = 'Job'
[[message]]
key = 'RIM_POP_MSG_CHARACTER_M_LV'
old = 'ジョブレベル指定'
new = 'Specify Vocation Level'
[[message]]
key = 'RIM_POP_MSG_CHARACTER_M_SKILL'
old = 'スキル'
new = 'Skill'
[[message]]
key = 'RIM_POP_MSG_CHARACTER_M_CHARACTER'
old = '性別'
new = 'Gender'
[[message]]
key = 'RIM_POP_MSG_M_ALL'
old = '全て'
new = 'All'
[[message]]
key = 'RIM_POP_MSG_M_UP'
old = '以上'
new = 'Min'
[[message]]
key = 'RIM_POP_MSG_SKILL_M_LV'
old = 'クラフトレベル'
new = 'Craft Level'
[[message]]
key = 'RIM_POP_MSG_SKILL_M_SKILL00'
old = 'クラフトスキル'
new = 'Craft Skills'
[[message]]
key = 'RIM_POP_MSG_SKILL_M_SKILL01'
old = '生産作業スピード'
new = 'Production Speed'
[[message]]
key = 'RIM_POP_MSG_SKILL_M_SKILL02'
old = '装備の強化技術'
new = 'Equipment Enhancement'
[[message]]
key = 'RIM_POP_MSG_SKILL_M_SKILL03'
old = '高品質装備の作成力'
new = 'Equipment Quality'
[[message]]
key = 'RIM_POP_MSG_SKILL_M_SKILL04'
old = '消耗品の生産数アップ'
new = 'Consumable Quantity'
[[message]]
key = 'RIM_POP_MSG_SKILL_M_SKILL05'
old = 'コストパフォーマンス'
new = 'Cost Performance'
[[message]]
key = 'RIM_POP_MSG_OWNER_M_OWNER'
old = 'オーナー名の指定'
new = 'Owner Name'
[[message]]
key = 'RIM_POP_MSG_OWNER_M_FIRST'
old = 'First Name'
[[message]]
key = 'RIM_POP_MSG_OWNER_M_FAMILY'
old = 'Family Name'
new = 'Last Name'
[[message]]
key = 'RIM_POP_MSG_OWNER_M_PAWN'
old = 'ポーンの名前を指定'
new = 'Pawn Name'
[[message]]
key = 'RIM_POP_MSG_BTN_SEARCH'
old = '検索する'
new = 'Search'
[[message]]
key = 'RIM_POP_MSG_M_DOWN'
old = '以下'
new = 'Maximum'
[[message]]
key = 'RIM_POP_MSG_M_GENDER_ALL'
old = '指定なし'
new = 'Any'
[[message]]
key = 'RIM_POP_MSG_M_GENDER_MALE'
old = '男性'
new = 'Male'
[[message]]
key = 'RIM_POP_MSG_M_GENDER_FEMALE'
old = '女性'
new = 'Female'
[[message]]
key = 'RIM_POP_MSG_SEARCH_JOB'
old = 'ジョブ'
new = 'Job'
[[message]]
key = 'RIM_POP_MSG_SEARCH_CRAFTSKILL'
old = 'クラフトスキル'
new = 'Craft Skills'
[[message]]
key = 'RIM_POP_MSG_CHARACTER_M_IR'
old = 'アイテムランク指定'
new = 'Specify Item Rank'
[[message]]
key = 'RIM_POP_MSG_SEARCH_DRASKILL'
old = 'ドラゴンアビリティ'
