[[message]]
key = 'poptop_bazaar_disp_exhibit_warehouse'
old = '保管ボックスから出品'
new = 'Sell from Storage Box'
[[message]]
key = 'poptop_bazaar_disp_exhibit_item'
old = 'アイテムバッグから出品'
new = 'Sell from Item Bag'
[[message]]
key = 'poptop_bazaar_disp_exhibit'
old = '出品'
new = 'Sell'
[[message]]
key = 'poptop_bazaar_situation'
old = '出品状況'
new = 'Exhibit Status'
[[message]]
key = 'poptop_bazaar_exhibit'
old = '出品'
new = 'Sell'
[[message]]
key = 'poptop_bazaar_buy'
old = '購入'
new = 'Buy'
[[message]]
key = 'poptop_bazaar_jp'
old = 'メニュー'
new = 'Menu'
[[message]]
key = 'poptop_bazaar_en'
old = 'Menu'
new = 'Menu'
[[message]]
key = 'poptop_bazaar_disp_posnum'
old = '出品可能数：'
new = 'Exhibits:'
[[message]]
key = 'poptop_contriinfo'
old = '名声度確認'
new = 'View Reputation'
[[message]]
key = 'poptop_spotinfo'
old = 'スポット情報'
new = 'Spot Info'
[[message]]
key = 'poptop_questinfo'
old = 'ワールドクエスト情報'
new = 'World Quest Info'
[[message]]
key = 'poptop_areamaster_jp'
old = 'エリアマスター'
new = 'Area Master'
[[message]]
key = 'poptop_areamaster_en'
old = 'Area Master'
new = 'Area Master'
[[message]]
key = 'poptop_profile_set'
old = 'プロフィール編集'
new = 'Edit Profile'
[[message]]
key = 'poptop_quick_party'
old = 'クイックパーティー'
new = 'Quick Party'
[[message]]
key = 'poptop_clan_clan_name'
old = '<NAME CLAN> <NAME CLAN_S>'
new = '<NAME CLAN> <NAME CLAN_S>'
[[message]]
key = 'poptop_rim_stone_support_pawn'
old = 'サポートポーン'
new = 'Support Pawns'
[[message]]
key = 'poptop_rim_stone_main_pawn'
old = 'メインポーン'
new = 'Main Pawns'
[[message]]
key = 'poptop_rim_stone_pawn_search'
old = 'ポーン検索'
new = 'Pawn Search'
[[message]]
key = 'poptop_entryboard_extend'
old = '募集時間延長'
new = 'Extend Time'
[[message]]
key = 'poptop_entryboard_cancel_entry'
old = 'エントリー中止'
new = 'Cancel Entry'
[[message]]
key = 'poptop_entryboard_search_union'
old = '別エントリー検索'
new = 'Search Entries'
[[message]]
key = 'poptop_entryboard_sally'
old = '出撃'
new = 'Sortie'
[[message]]
key = 'poptop_entryboard_num'
old = '<VAL>/<VAL>'
[[message]]
key = 'poptop_entryboard_entry'
old = 'エントリー中'
[[message]]
key = 'poptop_entryboard_menu'
old = 'メニュー'
new = 'Menu'
[[message]]
key = 'poptop_entryboard_title'
old = 'Entry Board'
[[message]]
key = 'poptop_clan_invite_list'
old = '招待リスト'
new = 'View Invites'
[[message]]
key = 'poptop_clan_join_list'
old = '加入希望者リスト'
new = 'View Applications'
[[message]]
key = 'poptop_pawn_join'
old = 'ポーンを入れる'
new = 'Invite Pawn'
[[message]]
key = 'poptop_player_search'
old = 'パーティー検索'
new = 'Party Search'
[[message]]
key = 'poptop_member_info'
old = 'パーティーメンバー確認'
new = 'Check Party Members'
[[message]]
key = 'poptop_color_change'
old = 'カラー変更'
new = 'Change Color'
[[message]]
key = 'poptop_crest_attach'
old = 'クレスト装着'
new = 'Mount Crest'
[[message]]
key = 'poptop_equip_build'
old = '装備の強化'
new = 'Enhance Equipment'
[[message]]
key = 'poptop_item_create'
old = 'アイテム生産'
new = 'Craft Item'
[[message]]
key = 'poptop_craft_jp'
old = 'メニュー'
new = 'Menu'
[[message]]
key = 'poptop_craft_en'
old = 'Menu'
new = 'Menu'
[[message]]
key = 'poptop_ability'
old = 'アビリティ'
new = 'Augments'
[[message]]
key = 'poptop_skill'
old = 'スキル'
new = 'Skills'
[[message]]
key = 'poptop_job'
old = 'ジョブ'
new = 'Vocation'
[[message]]
key = 'poptop_battle_assist_jp'
old = '戦技補佐'
[[message]]
key = 'poptop_battle_assist_en'
old = 'Battle Assist'
new = 'Battle Assist'
[[message]]
key = 'poptop_jp'
old = 'JP<JP>'
[[message]]
key = 'poptop_lv'
old = 'Lv<LV>'
[[message]]
key = 'poptop_item_state'
old = 'アイテム作成状況'
new = 'Production Status'
[[message]]
key = 'poptop_point_sep'
old = 'ステータス確認'
new = 'Pawn Status'
[[message]]
key = 'poptop_clan_en'
old = 'Clan'
[[message]]
key = 'poptop_party_jp'
old = 'パーティー管理'
new = 'Party'
[[message]]
key = 'poptop_party_en'
old = 'Party'
[[message]]
key = 'poptop_scout'
old = 'スカウト'
new = 'Scout'
[[message]]
key = 'poptop_clan_reave'
old = 'クラン脱退'
new = 'Leave'
[[message]]
key = 'poptop_clan_management'
old = 'クランステータス'
new = 'Clan Status'
[[message]]
key = 'poptop_clan_entry_now'
old = 'スカウトエントリー中'
[[message]]
key = 'poptop_clan_not_join'
old = '未加入'
new = 'None'
[[message]]
key = 'poptop_clan_invite'
old = 'スカウトエントリー招待'
new = 'View Invites'
[[message]]
key = 'poptop_clan_join'
old = '加入申請中クラン'
new = 'View Applications'
[[message]]
key = 'poptop_clan_scout_entry'
old = 'スカウトエントリー'
new = 'Scout'
[[message]]
key = 'poptop_clan_search'
old = 'クラン検索'
new = 'Clan Search'
[[message]]
key = 'poptop_clan_create'
old = 'クラン設立'
new = 'Found Clan'
[[message]]
key = 'poptop_clan_jp'
old = 'クラン'
new = 'Clan'
[[message]]
key = 'poptop_issue'
old = '支援品'
new = 'Support Goods'
[[message]]
key = 'poptop_bazaar_exhibit_en'
old = 'Sell'
new = 'Sell'
[[message]]
key = 'poptop_clan_entry_cancel'
old = 'スカウトエントリー中止'
new = 'Stop Scouting'
[[message]]
key = 'poptop_clan_entry_check'
old = 'スカウトエントリー確認'
new = 'View Recruits'
[[message]]
key = 'poptop_warehouse_en'
old = 'Menu'
new = 'Menu'
[[message]]
key = 'poptop_warehouse_jp'
old = 'メニュー'
new = 'Menu'
[[message]]
key = 'poptop_entryboard_reentry'
old = '再エントリー'
new = 'Reregister'
[[message]]
key = 'poptop_entryboard_newspaper'
old = 'イベント確認'
new = 'Check Event'
[[message]]
key = 'poptop_clan_member_num'
old = 'メンバー<VAL>名'
new = '<VAL> members'
[[message]]
key = 'poptop_rim_stone_lost_pawn'
old = 'ポーンの救出'
new = 'Lost Pawns'
[[message]]
key = 'poptop_entryboard_password_release'
old = 'パスワード解除'
new = 'Remove Password'
[[message]]
key = 'poptop_entryboard_comment_input'
old = 'コメント再編集'
new = 'Edit Comment'
[[message]]
key = 'poptop_entryboard_member_check'
old = 'メンバー確認'
new = 'Check Members'
[[message]]
key = 'poptop_entryboard_entry_invitation_pt'
old = 'パーティー招待'
new = 'Party Invite'
[[message]]
key = 'poptop_entryboard_ready'
old = '準備完了'
new = 'Ready'
[[message]]
key = 'poptop_clan_interval_now'
old = 'インターバル期間中'
new = 'Interval Duration'
[[message]]
key = 'poptop_entryboard_less_member_go'
old = '少人数でパーティーを組む'
new = 'Form Small Party'
[[message]]
key = 'poptop_depositbox_menutop_en'
old = 'Menu'
new = 'Menu'
[[message]]
key = 'poptop_depositbox_menutop_jp'
old = 'メニュー'
new = 'Menu'
[[message]]
key = 'poptop_depositbox_menu_01'
old = '引き出す / 預ける'
new = 'Withdraw / Deposit'
[[message]]
key = 'poptop_clan_invite_direct'
old = '直接招待'
new = 'Direct Invites'
[[message]]
key = 'poptop_depositbox_menu_ex01'
old = '拡張枠'
new = 'Expansion'
[[message]]
key = 'poptop_lot_normal'
old = '通常ロット'
new = 'Normal Lot'
[[message]]
key = 'poptop_lot_box'
old = 'ボックスロット'
new = 'Box Lot'
[[message]]
key = 'poptop_gp_charge'
old = '黄金石の確認'
new = 'Check GG'
[[message]]
key = 'poptop_deli_box'
old = 'アイテムポスト'
new = 'Item Post'
[[message]]
key = 'poptop_clan_kyoten_4'
old = 'ポーン遠征隊の状況確認'
new = 'Pawn Expedition Corps Status'
[[message]]
key = 'poptop_clan_kyoten_1'
old = '拠点拡張'
new = 'Hall Expansion'
[[message]]
key = 'poptop_clan_kyoten_2'
old = 'ポーン遠征隊支援'
new = 'Pawn Expedition Corps Support'
[[message]]
key = 'poptop_clan_kyoten_3'
old = 'クラン執務官の変更'
new = 'Change Clan Officers'
[[message]]
key = 'poptop_clan_kyoten_5'
old = '拠点のレイアウト'
new = 'Hall Layout'
[[message]]
key = 'poptop_enhance_evolution'
old = 'リミット解除'
new = 'Limit Break'
[[message]]
key = 'poptop_enhance_special_evolution'
old = '極限合成'
new = 'Ultimate Synthesis'
[[message]]
key = 'poptop_recycle_remaining_num'
old = '残り回数：'
new = 'Remaining:'
[[message]]
key = 'poptop_recycle_equip'
old = '武具の分解'
new = 'Disassemble Arms'
[[message]]
key = 'poptop_recycle_gs_equip'
old = '特殊武具の分解'
new = 'Disassemble Special Arms'
[[message]]
key = 'poptop_recycle_remaining_num_reset'
old = '残り回数リセット'
new = 'Reset Remaining'
[[message]]
key = 'poptop_depositbox_menu_02_restore'
old = 'アイテム復元'
new = 'Item Restoration'
[[message]]
key = 'poptop_craft_change_quality'
old = '装備の品質変更'
new = 'Change Quality'
[[message]]
key = 'poptop_entryboard_chat_recruit'
old = 'チャット募集'
new = 'Chat Recruitment'
[[message]]
key = 'poptop_daily_mission'
old = 'ミッションリスト'
new = 'Mission List'
[[message]]
key = 'poptop_weekly_mission'
old = '特別報酬'
new = 'Special Reward'
[[message]]
key = 'poptop_time_event'
old = '期間イベント'
new = 'Time Event'
[[message]]
key = 'poptop_daily_mission_title_en'
old = 'Menu'
new = 'Menu'
[[message]]
key = 'poptop_daily_mission_title_jp'
old = 'メニュー'
new = 'Menu'
[[message]]
key = 'poptop_recycle_ds_equip'
old = '竜武具の分解'
[[message]]
key = 'poptop_btn_dra_skill'
old = 'ドラゴンアビリティ情報'
