[[message]]
key = 'QUEST_MSG_LB_REC'
old = '推奨'
new = 'Recommend'
[[message]]
key = 'QUEST_MSG_LB_PROV'
old = '受注条件'
new = 'Accept Conditions'
[[message]]
key = 'QUEST_MSG_LB_NOTHING'
old = 'なし'
new = 'None'
[[message]]
key = 'QUEST_MSG_LB_REQ'
old = '依頼内容'
new = 'Request Details'
[[message]]
key = 'QUEST_MSG_LB_REWARD'
old = '報酬'
new = 'Reward'
[[message]]
key = 'QUEST_MSG_LB_EXP'
old = '経験値'
new = 'Experience points'
[[message]]
key = 'QUEST_MSG_LB_G'
old = 'ゴールド'
new = 'Gold'
[[message]]
key = 'QUEST_MSG_LB_RIM'
old = 'リム'
new = 'Rift'
[[message]]
key = 'QUEST_MSG_PRIOD'
old = '<VAL>まで'
new = 'Until <VAL>'
[[message]]
key = 'QUEST_MSG_LB_NOREWARD'
old = '報酬アイテムなし'
new = 'No rewards'
[[message]]
key = 'QUEST_MSG_MASK'
old = '？？？？？'
new = '?????'
[[message]]
key = 'QUEST_MSG_TITLE01'
old = 'Quest Log'
new = 'Quest Log'
[[message]]
key = 'QUEST_MSG_TITLE02'
old = 'クエストログ'
new = 'Quest Log'
[[message]]
key = 'QUEST_MSG_MENU_ENPRI'
old = '優先クエストに設定'
new = 'Set Priority Quest'
[[message]]
key = 'QUEST_MSG_ACCEPTED'
old = '受注数：'
new = 'Accepted: '
[[message]]
key = 'QUEST_MSG_MENU'
old = 'メニュー'
new = 'Menu'
[[message]]
key = 'QUEST_MSG_LB_ABS'
old = '概要'
new = 'Overview'
[[message]]
key = 'QUEST_MSG_LB_PROG'
old = '進行'
new = 'Progress'
[[message]]
key = 'QUEST_MSG_TAB_MYQ'
old = 'マイクエスト'
new = 'My Quests'
[[message]]
key = 'QUEST_MSG_TAB_PTQ'
old = 'パーティークエスト情報'
new = 'Party Quests'
[[message]]
key = 'QUEST_MSG_CG_MAIN'
old = 'メインクエスト'
new = 'Main Quest'
[[message]]
key = 'QUEST_MSG_CG_GRAND'
old = 'ワールドクエスト'
new = 'World Quest'
[[message]]
key = 'QUEST_MSG_CG_SOLO'
old = 'パーソナルクエスト'
new = 'Personal Quest'
[[message]]
key = 'QUEST_MSG_LB_NSTEP'
old = '次の目的'
new = 'Next Step'
[[message]]
key = 'QUEST_MSG_LB_CLEARED'
old = 'クリア回数'
new = 'Times Cleared'
[[message]]
key = 'QUEST_MSG_LB_ADDINFO'
old = 'クリア回数による追加情報'
[[message]]
key = 'QUEST_MSG_LB_AREAP'
old = 'エリア名声度：<NAME AREA_NAME>'
new = 'Area Reputation: <NAME AREA_NAME>'
[[message]]
key = 'QUEST_MSG_NAME_AREA'
old = 'エリア名'
new = 'Area Name'
[[message]]
key = 'QUEST_MSG_UN_AP'
old = 'AP'
new = 'AP'
[[message]]
key = 'QUEST_MSG_LB_BONUS'
old = 'ボーナス'
new = 'Bonus'
[[message]]
key = 'QUEST_MSG_LB_CHARGINFO'
old = '課金情報'
[[message]]
key = 'QUEST_MSG_LB_GOAL'
old = '目的'
new = 'Goal'
[[message]]
key = 'QUEST_MSG_OPERATION'
old = 'クエスト操作'
[[message]]
key = 'QUEST_MSG_MENU_CANCELLATION'
old = '優先解除'
new = 'Cancel Priority'
[[message]]
key = 'QUEST_MSG_MENU_PROORITY'
old = '優先クエスト'
new = 'Priority Quest'
[[message]]
key = 'QUEST_MSG_MENU_CANCEL'
old = 'クエスト破棄'
new = 'Cancel Quest'
[[message]]
key = 'QUEST_MSG_MENU_MAP'
old = '地図で確認'
new = 'Check Map'
[[message]]
key = 'QUEST_MSG_QUESTMENU'
old = 'クエストメニュー'
new = 'Quest Menu'
[[message]]
key = 'QUEST_MSG_QUESTLIST'
old = '受注クエスト一覧'
[[message]]
key = 'QUEST_MSG_BOARD_TITLE01'
old = 'Quest Board'
[[message]]
key = 'QUEST_MSG_BOARD_TITLE02'
old = 'クエストボード'
new = 'Quest Board'
[[message]]
key = 'QUEST_MSG_LB_REQ2'
old = '依頼'
[[message]]
key = 'QUEST_MSG_BUTTON_ACCEPT'
old = '受注する'
new = 'Accept'
[[message]]
key = 'QUEST_MSG_BUTTON_CANCEL'
old = 'キャンセル'
new = 'Cancel'
[[message]]
key = 'QUEST_MSG_LB_SPBONUS'
old = 'Special Bonus'
new = 'Special Bonus'
[[message]]
key = 'QUEST_MSG_SUBMENU'
old = 'サブメニュー'
new = 'Submenu'
[[message]]
key = 'QUEST_MSG_AREAPOINT'
old = 'エリア名声度 <VAL AREA_POINT>'
new = 'Area Reputation <VAL AREA_POINT>'
[[message]]
key = 'QUEST_MSG_TAB_ALL'
old = 'すべて'
new = 'All'
[[message]]
key = 'QUEST_MSG_TAB_HUNT'
old = '討伐'
new = 'Hunt'
[[message]]
key = 'QUEST_MSG_TAB_COLLECT'
old = '納品'
new = 'Deliver'
[[message]]
key = 'QUEST_MSG_CAUTION_FULL'
old = '''
クエスト受注数が上限に達しているため
クエストを受注できません'''
[[message]]
key = 'QUEST_MSG_CAUTION_NOTHING'
old = '現在、特別な報せはありません'
new = 'There are no quests currently available.'
[[message]]
key = 'QUEST_MSG_BN_UNDETECTED'
old = '未公開ボーナス'
new = 'Hidden Bonus'
[[message]]
key = 'QUEST_MSG_BN_REPLAY'
old = '繰り返しボーナス'
new = 'Repeat Bonus'
[[message]]
key = 'QUEST_MSG_ACCIDENTAL'
old = 'ボードボーナス発生中！'
new = 'Board bonus is active!'
[[message]]
key = 'QUEST_MSG_PROGRESS_CONDITION'
old = '進行条件'
new = 'Progress Conditions'
[[message]]
key = 'QUEST_MSG_HOLDING_PERIOD'
old = '開催期間'
[[message]]
key = 'QUEST_MSG_WAIT_ORDER_QUEST'
old = '受注待ちクエスト'
[[message]]
key = 'QUEST_MSG_LIST_UPDATE_ERROR'
old = 'リストの更新に失敗しました'
new = 'Failed to update the quest list.'
[[message]]
key = 'QUEST_MSG_SELECT_REWARD'
old = '選択報酬 (1つ選択)'
new = 'Select Reward (1)'
[[message]]
key = 'QUEST_MSG_NOTHING'
old = '現在受注しているクエストはありません'
new = 'There are currently no quests available.'
[[message]]
key = 'QUEST_MSG_NUMBER'
old = 'No.<VAL>'
[[message]]
key = 'QUEST_MSG_REPLAY_XP_UP'
old = '経験値アップ'
new = 'Experience Point Up'
[[message]]
key = 'QUEST_MSG_REPLAY_AP_UP'
old = 'エリアポイントアップ'
new = 'Area Point Up'
[[message]]
key = 'QUEST_MSG_REPLAY_RIM_UP'
old = 'リムアップ'
new = 'Rift Crystal Up'
[[message]]
key = 'QUEST_MSG_REPLAY_GOLD_UP'
old = 'ゴールドアップ'
new = 'Gold Up'
[[message]]
key = 'QUEST_MSG_REPLAY_SLOT_UP'
old = 'ランダム報酬枠増加'
new = 'Random Reward Up'
[[message]]
key = 'QUEST_MSG_CONFIRM_QUEST_CANCEL'
old = '''
クエストを破棄しますか？

※破棄したクエストは白竜神殿などの
　拠点に入りなおすと再受注可能になります'''
new = '''
Are you sure you want to cancel this quest?

※破棄したクエストは白竜神殿などの
　拠点に入りなおすと再受注可能になります'''
[[message]]
key = 'QUEST_MSG_CONFIRM_QUEST_ORDER'
old = '''
クエストを受注します
よろしいですか？'''
[[message]]
key = 'QUEST_MSG_MENU_ORDER'
old = 'クエスト受注'
new = 'Quest Order'
[[message]]
key = 'QUEST_MSG_SUPPORT_REWARD'
old = 'アシスト報酬'
new = 'Assist Reward'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_XP'
old = '経験値報酬が%2.1f倍（%s）'
new = 'x%2.1f Experience Point reward (%s)'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_AP'
old = 'エリアポイント報酬が%2.1f倍（%s）'
new = 'x%2.1f Area Point reward (%s)'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_RIM'
old = 'リム報酬が%2.1f倍（%s）'
new = 'x%2.1f Rift reward (%s)'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_GOLD'
old = 'ゴールド報酬が%2.1f倍（%s）'
new = 'x%2.1f Gold reward (%s)'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_RANDOM'
old = 'ランダム報酬枠が%d増加（%s）'
new = 'Random rewards increased by %d (%s)'
[[message]]
key = 'QUEST_MSG_BONUS_CHANCE_NUMBER'
old = 'ボーナス発生まで%d回'
new = 'bonus after %d clears'
[[message]]
key = 'QUEST_MSG_BONUS_TIME'
old = 'ボーナス発生中'
new = 'bonus active'
[[message]]
key = 'QUEST_MSG_OPTION_COURSE'
old = '<OPCS>'
new = '<OPCS>'
[[message]]
key = 'QUEST_MSG_NOTION_WAITING'
old = 'リーダーが受注時に受注待ちは解除できます'
[[message]]
key = 'QUEST_MSG_NOTION_DISABLE_PT'
old = '「パーティークエスト情報」では使用できません'
[[message]]
key = 'QUEST_MSG_NOTE_COLLISION_PROC'
old = 'リーダーとクエスト進行状況が一致していないため進行不可'
new = 'You cannot continue because your progress is different than the party leader'
[[message]]
key = 'QUEST_MSG_ORDERED_OVER'
old = 'クエスト受注数オーバー（クエストクリア/破棄で受注可）'
new = 'You have reached your limit on quests (you must clear/cancel quests).'
[[message]]
key = 'QUEST_MSG_PARTYB_ON1'
old = 'パーティークリアボーナス対象'
new = 'Party Clear Bonus Target'
[[message]]
key = 'QUEST_MSG_PARTYB_OFF1'
old = 'パーティークリアボーナス対象(取得済)'
new = 'Party Clear Bonus Target (already acquired)'
[[message]]
key = 'QUEST_MSG_PARTYB_ON2'
old = 'クリア報酬（アイテム以外）が最大<VAL>倍！'
new = 'Clear rewards (other than items) increased by x<VAL>!'
[[message]]
key = 'QUEST_MSG_PARTYB_OFF2'
old = '''
クリア報酬（アイテム以外）が最大<VAL>倍！
ブラッドオーブが<VAL>個獲得！'''
new = '''
Clear rewards (other than items) increased by x<VAL>!
ブラッドオーブが<VAL>個獲得！'''
[[message]]
key = 'QUEST_MSG_RAIDB_TITLE'
old = 'スコア倍率ボーナス'
new = 'Score Multiplier Bonus'
[[message]]
key = 'QUEST_MSG_RAIDb_BODY'
old = '<VAL>倍からスタート'
[[message]]
key = 'QUEST_MSG_OUT_LEADER'
old = 'リーダーが不在のため進行／受注不可'
[[message]]
key = 'QUEST_MSG_RANDOM_REWARD'
old = 'ランダム報酬'
new = 'Random Reward'
[[message]]
key = 'QUEST_MSG_TIME_LIMIT'
old = '配信終了まで'
new = 'Time Limit '
[[message]]
key = 'QUEST_MSG_NOTHING_0'
old = '---'
new = '---'
[[message]]
key = 'QUEST_MSG_LEADER_CONDITION'
old = 'リーダーが受注条件を満たしていません'
new = 'Leader does not meet the conditions'
[[message]]
key = 'QUEST_MSG_AREA_BONUS'
old = 'ボードボーナスでクリア時の報酬が最大<VAL>倍！'
new = 'Clear reward increased by x<VAL> with board bonus!'
[[message]]
key = 'QUEST_MSG_LEADER_PROGRESS'
old = 'リーダーが進行条件を満たしていません'
[[message]]
key = 'QUEST_MSG_BN_UNDETECTED1'
old = '未公開ボーナス(取得済)'
new = 'Hidden Bonus (acquired)'
[[message]]
key = 'QUEST_MSG_BN_TIMEBONUS'
old = 'タイムボーナス'
new = 'Time Bonus'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_TIMEBONUS'
old = 'スコア倍率が最大<VAL>倍！'
[[message]]
key = 'QUEST_MSG_PARTY_LARGE'
old = '特定のコンテンツ中は進行できません'
[[message]]
key = 'QUEST_MSG_SELECT_REWARD_ONLY_ONE'
old = '選択報酬'
new = 'Select Reward'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_DAILY'
old = '''
１日１回「基本報酬」
レア素材入手可能！'''
new = '''
Once daily "Basic Reward"
Rare material available!'''
[[message]]
key = 'QUEST_MSG_BN_DAILY'
old = 'デイリーボーナス'
new = 'Daily Bonus'
[[message]]
key = 'QUEST_MSG_ENEMYINFO'
old = '魔物情報'
new = 'Enemies'
[[message]]
key = 'QUEST_MSG_DELIVERYINFO'
old = 'クリアに必要な納品情報'
new = 'Delivery Required'
[[message]]
key = 'QUEST_MSG_BN_ROOT'
old = 'ボーナス報酬'
new = 'Bonus Reward'
[[message]]
key = 'QUEST_MSG_BONUS_ROOT'
old = '成功時に報酬を追加付与'
new = 'Additional reward granted upon success'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_TITLE_EN'
old = 'Clan Quest'
new = 'Clan Quest'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_TITLE_JP'
old = 'クランクエスト'
new = 'Clan Quest'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_CAP_ENABLE_CLEAR'
old = 'CP報酬の有効クリア回数'
new = 'CP reward clear count'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_NUM_ENABLE_CLEAR'
old = '%d / %d 回'
new = '%d / %d times'
[[message]]
key = 'QUEST_MSG_WQ_UNRELEASED_AREA'
old = '対象エリアのワールドクエストが未解放のため受注不可'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_BTN'
old = '一括クリア'
new = 'All Clear'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_ERR_01'
old = 'すべてのクエストがクリア状態のため、使用できません'
new = 'All quests have already been cleared'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_CONF'
old = '''
このクエストボードから配信されている
すべてのクエストを一括してクリア状態にします
<COL ffdc78>黄金石<VAL>個</COL>を消費して、一括クリアしますか？
(所持数：<VAL>)'''
new = '''
All quests delivered from this Quest Board
can be cleared.
Are you sure you want to use
<COL ffdc78><VAL> Golden Gemstone</COL> to clear all quests?
(Have: <VAL>)'''
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_LACK'
old = '''
黄金石が不足しています
一括クリアするには<COL ffdc78>黄金石<VAL>個</COL>が必要です
(所持数：<VAL>)'''
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_GOTO_ONLINESHOP'
old = 'オンラインショップを開く'
new = 'Open Online Shop'
[[message]]
key = 'QUEST_MSG_ASSIST_ACCEPT'
old = '条件を満たしていないためアシスト状態で受注可'
new = 'Because you do not meet the conditions, the quest will be accepted in assist mode.'
[[message]]
key = 'QUEST_MSG_SEQUENCE_DUPLICATE'
old = '同一シーケンス内の別クエストを受注中のため受注不可'
[[message]]
key = 'QUEST_MSG_CG_ROYAL'
old = 'サブストーリークエスト'
new = 'Substory Quest'
[[message]]
key = 'QUEST_MSG_PLAYABLE_DATE'
old = '配信開始：'
new = 'Distribution Begins:'
[[message]]
key = 'QUEST_MSG_EQUIPMENT_RESTRICTIONS'
old = '装備制限あり'
[[message]]
key = 'QUEST_MSG_HARD_QUEST_TITLE_EN'
old = 'Quest Board'
new = 'Quest Board'
[[message]]
key = 'QUEST_MSG_HARD_QUEST_TITLE_JP'
old = 'スペシャルクエストボード'
new = 'Special Quest Board'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_CONF_HARD'
old = '''
このクエストボードから配信されている
すべてのクエストを一括してクリア状態にします
<COL ffdc78>黄金石<VAL>個</COL>を消費して、一括クリアしますか？
(所持数：<VAL>)

<COL aa1414>スペシャルクエストボードは、一括クリアする度に
必要な黄金石がボード毎に増加します</COL>

<COL aa1414>PPモード中や、LVが最大の時には
報酬の経験値を入手することはできません</COL>'''
new = '''
All quests delivered from this Quest Board
can be cleared.
Are you sure you want to use
<COL ffdc78><VAL> Golden Gemstone</COL> to clear all quests?
(Have: <VAL>)

<COL aa1414>スペシャルクエストボードは、一括クリアする度に
必要な黄金石がボード毎に増加します</COL>

<COL aa1414>In PP mode or when maximum LV, experience
from rewards cannot be obtained.</COL>'''
[[message]]
key = 'QUEST_MSG_LV_BONUS'
old = 'クリア報酬が最大%s倍！'
new = 'Clear reward up to x%s!'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_TITLE_01'
old = 'Adventure Guide'
new = 'Adventure Guide'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_TITLE_02'
old = '冒険ガイド'
new = 'Adventure Guide'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_NOTHING'
old = '現在紹介出来るクエストはありません'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_01'
old = 'メインクエスト'
new = 'Main Quest'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_02'
old = 'レベル上げミッション'
new = 'Leveling Mission'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_03'
old = 'レベル上げクエスト'
new = 'Leveling Quest'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_04'
old = '冒険に役立つクエスト'
new = 'Quest Useful for Adventure'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_05'
old = 'ジョブクエスト'
new = 'Vocation Quest'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_06'
old = 'コラボ/シーズナルクエスト'
new = 'Collaboration / Seasonal Quest'
[[message]]
key = 'QUEST_MSG_LB_OPEN_CONTENTS'
old = '解放コンテンツ'
new = 'Unlock Content'
[[message]]
key = 'QUEST_MSG_MENU_NAVI_ON'
old = 'ナビゲート設定'
new = 'Navigate On'
[[message]]
key = 'QUEST_MSG_MENU_NAVI_OFF'
old = 'ナビゲート解除'
new = 'Navigate Off'
[[message]]
key = 'QUEST_MSG_MENU_ENTRY'
old = '参加する'
new = 'Participate'
[[message]]
key = 'QUEST_MSG_OPEN_MAP_ERROR_NO_NAVI'
old = '地図で確認するには、ナビゲーションを設定してください'
[[message]]
key = 'QUEST_MSG_OPEN_MAP_ERROR_NO_MARKER'
old = '受注可能になるまで、地図で確認できません。'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_EXM_REWARD_NAME'
old = 'その他報酬'
new = 'Other Rewards'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_EXM_REWARD_INFO'
old = '詳細は参加ボタンを押して、エントリー画面でご確認ください'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_07'
old = 'エリア試練/エリアミッション'
new = 'Area Trial / Area Mission'
[[message]]
key = 'QUEST_MSG_MISSION_INFO_NOEQUIP_HEADER'
old = '装備制限'
[[message]]
key = 'QUEST_MSG_MISSION_INFO_REWARD_EQUIP_HEADER'
old = '報酬追加装備'
[[message]]
key = 'QUEST_MSG_MISSION_INFO_NOEQUIP_ARMOR'
old = '防具は装備できません'
[[message]]
key = 'QUEST_MSG_MISSION_INFO_NOEQUIP_JEWELRY'
old = 'ジュエリーは装備できません'
[[message]]
key = 'QUEST_MSG_MISSION_INFO_NOEQUIP_ABILITY'
old = '以下のアビリティは装備できません'
[[message]]
key = 'QUEST_MSG_REGULATION_ERROR'
old = '%sが%sを装備しているため、出撃できません'
[[message]]
key = 'QUEST_MSG_REGULATION_AROMOR'
old = '防具'
new = 'Armor'
[[message]]
key = 'QUEST_MSG_REGULATION_JEWELRY'
old = 'ジュエリー'
new = 'Jewelry'
[[message]]
key = 'QUEST_MSG_REGULATION_ABILITY'
old = '禁止アビリティ'
new = 'Restricted Ability'
[[message]]
key = 'QUEST_MSG_MOB_HUNT_TITLE_EN'
old = 'Wild Hunt'
new = 'Wild Hunt'
[[message]]
key = 'QUEST_MSG_MOB_HUNT_TITLE_JP'
old = 'ワイルドハント'
new = 'Wild Hunt'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_08'
old = 'ワイルドハント'
new = 'Wild Hunt'
[[message]]
key = 'QUEST_MSG_MOB_HUNT_LOT_HIGH'
old = 'リサの信頼度：★★★★'
new = "Lisa's Confidence: ★★★★"
[[message]]
key = 'QUEST_MSG_MOB_HUNT_LOT_MIDDLE'
old = 'リサの信頼度：★★★　'
new = "Lisa's Confidence: ★★★　"
[[message]]
key = 'QUEST_MSG_MOB_HUNT_LOT_LOW'
old = 'リサの信頼度：★★　　'
new = "Lisa's Confidence: ★★　　"
[[message]]
key = 'QUEST_MSG_MOB_HUNT_LOT_NONE'
old = 'リサの信頼度：★　　　'
new = "Lisa's Confidence: ★　　　"
[[message]]
key = 'QUEST_MSG_MOB_HUNT_NUM'
old = 'ワイルドハント数：'
new = 'Wild Hunt Count:'
[[message]]
key = 'QUEST_MSG_LOT_RATE_TITLE'
old = 'Ｓランク抽選：%s'
new = 'S Rank Lottery: %s'
[[message]]
key = 'QUEST_MSG_LOT_RATE_HIGH'
old = '中'
new = 'Medium'
[[message]]
key = 'QUEST_MSG_LOT_RATE_MIDDLE'
old = '低'
new = 'Low'
[[message]]
key = 'QUEST_MSG_LOT_RATE_LOW'
old = '無し'
new = 'None'
[[message]]
key = 'QUEST_MSG_LOT_RANK_S'
old = 'Ｓランク'
new = 'S Rank'
[[message]]
key = 'QUEST_MSG_LOT_RANK_A'
old = 'Ａランク'
new = 'A Rank'
[[message]]
key = 'QUEST_MSG_LOT_RANK_B'
old = 'Ｂランク'
new = 'B Rank'
[[message]]
key = 'QUEST_MSG_LOT_NUM'
old = '（抽選数：%d）'
new = '(Lottery Count: %d)'
[[message]]
key = 'QUEST_MSG_GUIDE_LOT_INFO'
old = '抽選確率詳細'
new = 'Lottery Chance Details'
[[message]]
key = 'QUEST_MSG_BONUS_MOB_HUNT_TITLE'
old = 'ボーナスターゲット出現中！'
new = 'Bonus Target Appearance!'
[[message]]
key = 'QUEST_MSG_BONUS_MOB_HUNT_INFO'
old = '討伐でPP報酬量UP'
new = 'Target PP Reward Amount UP'
[[message]]
key = 'QUEST_MSG_REWARD_TRADE_COST_TITLE'
old = '必要アイテム（ボス討伐後に報酬アイテムと交換します）'
[[message]]
key = 'QUEST_MSG_ERROR_REWARD_TRADE_ITEM_NONE'
old = '''
必要アイテム（%s）を
アイテムバッグに所持していないため、出撃できません'''
[[message]]
key = 'QUEST_MSG_LOT_RATE_HIGHEST'
old = '高'
new = 'High'
[[message]]
key = 'QUEST_MSG_CONFIRM_MOB_QUEST_CANCEL'
old = '''
クエストを破棄しますか？

<COL ffdc78>※破棄したワイルドハントは
　一定期間経過するまで再受注することができません</COL>'''
[[message]]
key = 'QUEST_MSG_ERROR_NAVIGATE_MOB_HUNT'
old = 'ワイルドハントでは使用できません'
[[message]]
key = 'QUEST_MSG_UI_REWARD_TRADE_ITEM'
old = '%s×%d（所持数：%d）'
