[[message]]
key = 'shop_title_rim_stone_sub'
old = 'リムストーン'
new = 'Riftstone'
[[message]]
key = 'shop_title_clan'
old = 'Clan'
new = 'Clan'
[[message]]
key = 'shop_title_clan_sub'
old = 'クラン'
new = 'Clan'
[[message]]
key = 'shop_title_cycle_contents'
old = 'Grand Mission'
new = 'Grand Mission'
[[message]]
key = 'shop_title_cycle_contents_sub'
old = 'グランドミッション'
new = 'Grand Mission'
[[message]]
key = 'shop_title_warehouse'
old = 'Warehouse'
new = 'Warehouse'
[[message]]
key = 'shop_title_warehouse_sub'
old = '保管ボックス'
new = 'Storage Box'
[[message]]
key = 'shop_title_craft'
old = 'Craft'
new = 'Craft'
[[message]]
key = 'shop_title_craft_sub'
old = 'クラフト'
new = 'Craft'
[[message]]
key = 'shop_title_area_master'
old = 'Area Master'
new = 'Area Master'
[[message]]
key = 'shop_title_area_master_sub'
old = 'エリアマスター'
new = 'Area Master'
[[message]]
key = 'shop_title_inn'
old = 'Inn'
new = 'Inn'
[[message]]
key = 'shop_title_inn_sub'
old = '宿屋'
new = 'Inn'
[[message]]
key = 'shop_title_bazaar'
old = 'Bazaar'
new = 'Bazaar'
[[message]]
key = 'shop_title_bazaar_sub'
old = 'バザー'
new = 'Bazaar'
[[message]]
key = 'shop_title_party_support'
old = 'Party Support'
[[message]]
key = 'shop_title_party_support_sub'
old = '冒険仲介'
[[message]]
key = 'shop_title_shop'
old = 'Shop'
new = 'Shop'
[[message]]
key = 'shop_title_shop_sub'
old = 'ショップ'
new = 'Shop'
[[message]]
key = 'shop_title_orb_shop'
old = 'Orb Shop'
new = 'Orb Shop'
[[message]]
key = 'shop_title_orb_shop_sub'
old = 'ショップ'
new = 'Orb Shop'
[[message]]
key = 'shop_title_arts_support'
old = 'Arts Support'
new = 'Arts Support'
[[message]]
key = 'shop_title_arts_support_sub'
old = '戦技補佐'
new = 'Arts Support'
[[message]]
key = 'shop_title_job_master'
old = 'Job Master'
new = 'Job Master'
[[message]]
key = 'shop_title_job_master_sub'
old = 'ジョブマスター'
new = 'Job Master'
[[message]]
key = 'shop_title_beauty_parlor'
old = 'Beauty Salon'
[[message]]
key = 'shop_title_beauty_parlor_sub'
old = '美容院'
new = 'Beauty Salon'
[[message]]
key = 'shop_title_revival_recover'
old = 'Revival Recover'
new = 'Recover Revival Power'
[[message]]
key = 'shop_title_revival_recover_sub'
old = '復活力の回復'
new = 'Recover Revival Power'
[[message]]
key = 'shop_title_delivery'
old = 'Delivery'
new = 'Delivery'
[[message]]
key = 'shop_title_delivery_sub'
old = '納品'
new = 'Delivery'
[[message]]
key = 'shop_title_rim_stone'
old = 'Rim Stone'
new = 'Riftstone'
[[message]]
key = 'shop_title_gacha'
old = 'Treasures Lot'
new = 'Treasure Lot'
[[message]]
key = 'shop_title_gacha_sub'
old = 'トレジャーズロット'
new = 'Treasure Lot'
[[message]]
key = 'shop_title_quest_board'
old = 'Quest Board'
new = 'Quest Board'
[[message]]
key = 'shop_title_quest_board_sub'
old = 'クエストボード'
new = 'Quest Board'
[[message]]
key = 'shop_title_end_contents'
old = 'Extreme Missions'
new = 'Extreme Missions'
[[message]]
key = 'shop_title_end_contents_sub'
old = 'エクストリームミッション'
new = 'Extreme Missions'
[[message]]
key = 'shop_title_appraise_sub'
old = '鑑定交換'
new = 'Appraisal Exchange'
[[message]]
key = 'shop_title_appraise'
old = 'Appraise'
new = 'Appraise'
[[message]]
key = 'shop_title_depositbox_sub'
old = '格納チェスト'
new = 'Storage Chest'
[[message]]
key = 'shop_title_depositbox'
old = 'Storage Chest'
new = 'Storage Chest'
[[message]]
key = 'shop_title_boxgacha'
old = 'Box Treasure Lot'
new = 'Box Treasure Lot'
[[message]]
key = 'shop_title_boxgacha_sub'
old = 'ボックストレジャーズロット'
new = 'Box Treasure Lot'
[[message]]
key = 'shop_title_pp_shop'
old = 'Play Point Shop'
new = 'Play Point Shop'
[[message]]
key = 'shop_title_pp_shop_sub'
old = 'プレイポイントショップ'
new = 'Play Point Shop'
[[message]]
key = 'shop_title_clan_base'
old = 'クラン拠点管理'
new = 'Clan Hall Management'
[[message]]
key = 'shop_title_clan_quest'
old = 'Clan Quest'
new = 'Clan Quest'
[[message]]
key = 'shop_title_clan_quest_sub'
old = 'クランクエスト'
new = 'Clan Quest'
[[message]]
key = 'shop_title_clan_dungeon'
old = 'クランダンジョン'
new = 'Clan Dungeon'
[[message]]
key = 'shop_title_partyboard'
old = 'パーティー募集掲示板'
new = 'Party Recruitment Board'
[[message]]
key = 'shop_title_war_mission'
old = 'ウォーミッション'
new = 'War Mission'
[[message]]
key = 'shop_title_equip_enhance'
old = '武具のカスタムメイド'
new = 'Custom-Made Arms'
[[message]]
key = 'shop_title_equip_recycle'
old = '武具の資源分解'
new = 'Arms Resource Disassembly'
[[message]]
key = 'shop_title_job_emblem'
old = 'ジョブエンブレム'
new = 'Vocation Emblem'
[[message]]
key = 'shop_title_hard_Quest'
old = 'スペシャルクエストボード'
new = 'Special Quest Board'
[[message]]
key = 'shop_title_infdelivery_event'
old = '大口納品イベント'
new = 'Large Delivery Event'
[[message]]
key = 'shop_title_bbi_efcsealed'
old = '黒呪装具の効果封印'
new = 'Bitterblack Equipment Effect Seal'
[[message]]
key = 'shop_title_bbi_dispel'
old = 'レアアイテムの鑑定'
new = 'Rare Item Appraisal'
[[message]]
key = 'shop_title_bbi_embody'
old = '黒呪アイテムの持ち帰り'
new = 'Bitterblack Item Takeaway'
[[message]]
key = 'shop_title_daily_mission'
old = 'リワードミッション'
new = 'Reward Mission'
[[message]]
key = 'shop_title_ds_fusion'
old = 'ドラゴンアビリティの合成'
new = 'Dragon Ability Synthesis'
[[message]]
key = 'shop_title_mob_hunt'
old = 'ワイルドハント'
new = 'Wild Hunt'
