[[message]]
key = 'sys_announce_controllernotconnect'
old = '<PFWD 0>が接続されていません'
new = '<PFWD 0> is not currently connected.'
[[message]]
key = 'sys_announce_check_strage'
old = 'ハードディスクドライブの容量をチェックしています'
new = 'Checking HDD capacity.'
[[message]]
key = 'sys_announce_notenoughstorage'
old = '''
ハードディスクドライブの空き容量が不足しています
ゲームを開始するためには
<VAL 0> 以上の空き容量が必要です
ゲームを終了して空き容量を確保してください'''
new = '''
Insufficient free space on the HDD.
In order to start the game,
more than <VAL 0> is required.
Please exit the game and free the space necessary.'''
[[message]]
key = 'sys_announce_trophy'
old = ''
[[message]]
key = 'sys_announce_newsave'
old = '''
新規にセーブデータを作成しています
PCの電源を切らないでください'''
new = '''
Creating new save data.
Do not turn off the PC.'''
[[message]]
key = 'sys_announce_savedata_broken'
old = '''
セーブデータが破損しています
セーブデータを破棄して
新規に作成しますか？'''
new = '''
Save data is corrupted
and will be discarded.
Do you want to create a new save?'''
[[message]]
key = 'sys_announce_ps3_loadfail'
old = '''
セーブデータをロードできませんでした
セーブデータを破棄して
新規に作成しますか？'''
new = '''
Save data could not be loaded,
and will be discarded.
Do you want to create a new save?'''
[[message]]
key = 'sys_announce_notuse_anothersave'
old = '''
他のユーザーのセーブデータを
使用することはできません
セーブデータを破棄して
新規に作成します'''
new = '''
Other user's save data
cannot be used and will be discarded.
Please create a new save.'''
[[message]]
key = 'sys_announce_goto_launcher'
old = '''
セーブデータを準備できませんでした
ランチャーへ戻ります'''
new = '''
Could not create save data.
Exiting to the launcher.'''
[[message]]
key = 'sys_announce_failedsave'
old = 'セーブデータの保存に失敗しました'
new = 'Failed to save.'
[[message]]
key = 'sys_announce_checkingsave'
old = '''
セーブデータをチェックしています
PCの電源を切らないでください'''
new = '''
Checking save data.
Please do not turn off your PC.'''
[[message]]
key = 'sys_announce_check_strage_fail'
old = '''
ハードディスクドライブ容量の
チェックに失敗しました
ランチャーへ戻ります'''
new = '''
Checking HDD capacity failed.
Exiting to the launcher.'''
[[message]]
key = 'sys_announce_trophy_fail'
old = '''
トロフィーデータの準備に失敗しました
ランチャーへ戻ります'''
new = '''
Failed to create trophy data.
Exiting to the launcher.'''
[[message]]
key = 'sys_announce_firstoption'
old = '''
操作デバイスを選択してください
※この項目はデバイス設定からいつでも変更できます'''
new = '''
Please select the input device.
※ This selection can be changed at any time from the settings menu.'''
[[message]]
key = 'sys_announce_choice_pad'
old = '<PFWD 0>'
[[message]]
key = 'sys_announce_choice_mouse'
old = 'マウス・キーボード'
new = 'Mouse/Keyboard'
[[message]]
key = 'sys_announce_calibration'
old = '''
<PFWD 0>のボタン配置を初期化しました
ボタン配置の確認後
必要であれば配置変更を行ってください'''
new = '''
Initialized inputs from <PFWD 0>.
After checking the button layout, you may change the
button placement if necessary.'''
[[message]]
key = 'sys_announce_saving'
old = '設定を保存します'
new = 'Save settings'
[[message]]
key = 'sys_announce_exit'
old = "Dragon's Dogma Online を終了しますか？"
new = "Are you sure you want to exit Dragon's Dogma Online?"
[[message]]
key = 'sys_announce_connecting'
old = 'サーバーと通信中です'
new = 'Connecting to server.'
[[message]]
key = 'sys_announce_firstoption_uisize'
old = '''
UIの表示設定を選択してください
(解像度1600×900 以上で有効になります)'''
new = '''
Please select the UI display setting.
(Available when resolution is 1600×900 or greater)'''
[[message]]
key = 'sys_announce_choice_uilarge'
old = 'UIを拡大表示する'
new = 'Enlarge UI'
[[message]]
key = 'sys_announce_choice_uinormal'
old = 'UIを拡大表示しない'
new = 'Do not enlarge UI'
[[message]]
key = 'sys_announce_firstoption_uisize_check'
old = '''
UIの表示サイズはこれでよろしいですか？
※この項目はデバイス設定からいつでも変更できます'''
new = '''
Are you sure you want this UI display size?
※ This selection can be changed at any time from the settings menu.'''
