[[message]]
key = 'DAILY_MISSION_PURPOSE_1'
old = 'クエストを<VAL>回クリア'
new = 'Clear quest <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_2'
old = 'ダンジョンを<VAL>回クリア'
new = 'Clear dungeon <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_3'
old = '高難度ダンジョンを<VAL>回クリア'
new = 'Clear high difficulty dungeon <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_4'
old = 'バトルコンテンツを<VAL>回クリア'
new = 'Clear battle content <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_6'
old = 'クラフトを<VAL>回する'
new = 'Craft <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_5'
old = 'その他の目的を<VAL>回達成'
new = 'Achieve other objectives <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_7'
old = 'リワードミッションを<VAL>回クリアする'
new = 'Clear Reward Mission <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_8'
old = 'リワードミッションを<VAL>回クリアする'
new = 'Clear Reward Mission <VAL> times'
[[message]]
key = 'DAILY_MISSION_PURPOSE_9'
old = 'リワードミッションを<VAL>回クリアする'
new = 'Clear Reward Mission <VAL> times'
