[[message]]
key = 'DAILY_MISSION_TASK_16'
old = 'ウォーミッションをクリアする'
new = 'Clear War Mission'
[[message]]
key = 'DAILY_MISSION_TASK_17'
old = 'エクストリームミッションをクリアする'
new = 'Clear Extreme Mission'
[[message]]
key = 'DAILY_MISSION_TASK_18'
old = 'ワイルドハントをクリアする'
new = 'Clear Wild Hunt'
