[[message]]
key = 'DAILY_MISSION_TASK_40'
old = '滅びの渦で暗黒の大竜晶を破壊する'
new = 'Destroy the Dark Dragon Crystal in the Vortex of Ruin'
[[message]]
key = 'DAILY_MISSION_TASK_42'
old = '''
魔赤島、フィンダム、アッカ―シェランの地域素材が
入手可能なダンジョン/期間解放スポットをクリアする
※聖炎の参竜道を除く'''
