[[message]]
key = 'DAILY_MISSION_TASK_2'
old = 'ボードクエストをクリアする'
new = 'Clear Board Quest'
[[message]]
key = 'DAILY_MISSION_TASK_7'
old = 'ワールドクエストをクリアする'
new = 'Clear World Quest'
[[message]]
key = 'DAILY_MISSION_TASK_9'
old = 'パーソナルクエストをクリアする'
new = 'Clear Personal Quest'
[[message]]
key = 'DAILY_MISSION_TASK_8'
old = 'ポーンクエストをクリアする'
new = 'Clear Pawn Quest'
[[message]]
key = 'DAILY_MISSION_TASK_11'
old = 'クランクエストをクリアする'
new = 'Clear Clan Quest'
[[message]]
key = 'DAILY_MISSION_TASK_15'
old = 'スペシャルボードクエストをクリアする'
new = 'Clear Special Board Quest'
