[[message]]
key = 'DAILY_MISSION_TASK_28'
old = 'マンドラゴラを育てる'
new = 'Raising Mandragora'
[[message]]
key = 'DAILY_MISSION_TASK_31'
old = 'パートナーポーンにリムの欠片をあげる'
new = "Raise Partner Pawn's Riftstone Shards"
[[message]]
key = 'DAILY_MISSION_TASK_29'
old = 'ログインスタンプを押してもらう'
new = 'Press Login Stamp'
[[message]]
key = 'DAILY_MISSION_TASK_30'
old = '冒パスショップで買い物をする'
new = 'Shop at Adventure Pass Shop'
