[[message]]
key = 'DAILY_MISSION_TASK_19'
old = 'いずれかのアイテムをクラフトする'
new = 'Craft Any Item'
[[message]]
key = 'DAILY_MISSION_TASK_21'
old = '武具のグレードをあげる'
new = 'Increase Grade of Arms'
[[message]]
key = 'DAILY_MISSION_TASK_23'
old = 'クレストを装着する'
new = 'Mount Crest'
[[message]]
key = 'DAILY_MISSION_TASK_24'
old = '武具のカラーを変更する'
new = 'Change Color of Arms'
[[message]]
key = 'DAILY_MISSION_TASK_25'
old = '家具をクラフトする'
new = 'Craft Furniture'
[[message]]
key = 'DAILY_MISSION_TASK_26'
old = 'リミット解除する'
new = 'Limit Break'
[[message]]
key = 'DAILY_MISSION_TASK_27'
old = '極限合成する'
new = 'Ultimate Synthesis'
