[[message]]
key = 'DAILY_MISSION_TASK_16'
old = 'ウォーミッションをクリアする'
new = 'Clear War Mission'
[[message]]
key = 'DAILY_MISSION_TASK_17'
#NEEDS REVIEW
#エクストリームミッションをクリアする
old = 'エクストリームミッションをクリア　※大竜晶破壊戦を除く'
new = 'Clear Extreme Mission ※Except 大竜晶破壊戦'
[[message]]
key = 'DAILY_MISSION_TASK_18'
old = 'ワイルドハントをクリアする'
new = 'Clear Wild Hunt'
