[[message]]
old = '（肩書なし）'
new = '(No Title)'
[[message]]
old = '竜力の継承'
new = 'Dragon Force Augmentation'
[[message]]
old = '記録官'
new = 'Historian'
[[message]]
old = 'ジョブマスター：アルケミスト'
new = 'Job Master: Alchemist'
[[message]]
old = 'ジョブマスター：ファイター'
new = 'Job Master: Fighter'
[[message]]
old = 'よろず屋・ハイオーブ交換'
new = 'General Shop / High Orb Exchange'
[[message]]
old = 'グランドミッション：魔赤島の狂宴'
new = "Grand Mission: Bloodbane Isle's Feast of Madness"
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '武器屋'
new = 'Weapon Shop'
[[message]]
old = '防具屋'
new = 'Armor Shop'
[[message]]
old = '美容院'
new = 'Beauty Salon'
[[message]]
old = '素材屋'
new = 'Material Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = 'バザー'
new = 'Bazaar'
[[message]]
old = 'バザー'
new = 'Bazaar'
[[message]]
old = 'バザー'
new = 'Bazaar'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = 'クラン酒場'
new = 'Clan Tavern'
[[message]]
old = '店員'
new = 'Waitress'
[[message]]
old = 'レスタニアニュース・白竜祭・EXM'
new = 'Lestania News / White Dragon Festival / EXM'
[[message]]
old = 'グランドミッション：目覚めし闇の魔物'
new = 'Grand Mission: The Demon of Darkness Awakens'
[[message]]
old = 'グランドミッション：太古の強者'
new = 'Grand Mission: Ancient Warrior'
[[message]]
old = 'グランドミッション：眩き黄金'
new = 'Grand Mission: The Dazzling Gold'
[[message]]
old = '宿屋'
new = 'Inn'
[[message]]
old = 'グランドミッション：失われた秩序'
new = 'Grand Mission: The Lost Order'
[[message]]
old = 'クラフト係官'
new = 'Craft Officer'
[[message]]
old = 'エクストリームミッション'
new = 'Extreme Missions'
[[message]]
old = '転職・戦技補佐'
new = 'Vocation / Arts Support'
[[message]]
old = '訓練官'
new = 'Trainer'
[[message]]
old = 'トレジャーズロット・納品イベント受付'
new = 'Treasure Lot / Delivery Event Reception'
[[message]]
old = '素材屋'
new = 'Material Shop'
[[message]]
old = 'バザー'
new = 'Bazaar'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '素材屋'
new = 'Material Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = '店員'
new = 'Waitress'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '店員'
new = 'Waitress'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '素材屋'
new = 'Material Shop'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '素材屋'
new = 'Material Shop'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '泉の係官'
new = 'Spring Manager'
[[message]]
old = '泉の係官'
new = 'Spring Manager'
[[message]]
old = '泉の係官'
new = 'Spring Manager'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '素材屋'
new = 'Material Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = 'ジョブマスター：ウォリアー'
new = 'Job Master: Warrior'
[[message]]
old = '店員'
new = 'Waitress'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = 'オーブ交換：珍品／素材'
new = 'Orb Exchange: Rare Items / Materials'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = 'オーブ交換：クレスト'
new = 'Orb Exchange: Crests'
[[message]]
old = 'ジョブマスター：プリースト'
new = 'Job Master: Priest'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'ジョブマスター：シールドセージ'
new = 'Job Master: Shield Sage'
[[message]]
old = 'ジョブマスター：ソーサラー'
new = 'Job Master: Sorcerer'
[[message]]
old = '宿・ジョブマスター：Ｅアーチャ―'
new = 'Inn / Job Master: Element Archer'
[[message]]
old = '道具屋・ジョブマスター：ハンター'
new = 'Item Shop / Job Master: Hunter'
[[message]]
old = 'ジョブマスター：シーカー'
new = 'Job Master: Seeker'
[[message]]
old = 'エリアマスター・宿'
new = 'Area Master / Inn'
[[message]]
old = 'エリアマスター・宿'
new = 'Area Master / Inn'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = 'エリアマスター・道具屋'
new = 'Area Master / Item Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '復活力・ログインスタンプ'
new = 'Revival Power / Login Stamp'
[[message]]
old = '鑑定交換'
new = 'Appraisal Exchange'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '自室の管理'
new = 'Room Management'
[[message]]
old = '戦技練習'
new = 'Warfare Practice'
[[message]]
old = '受付'
new = 'Receptionist'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '現れしポーン'
[[message]]
old = '黒呪の迷宮 案内人'
new = 'Bitterblack Maze Guide'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '冒険ガイド・エクストリームミッション'
new = 'Adventure Guide / Extreme Missions'
[[message]]
old = '宿・よろず屋'
new = 'Inn / General Shop'
[[message]]
old = 'クラン執務官'
new = 'Clan Officer'
[[message]]
old = 'クラン執務官'
new = 'Clan Officer'
[[message]]
old = 'クランダンジョン'
new = 'Clan Dungeon'
[[message]]
old = '宿・転職・戦技補佐'
new = 'Inn / Vocation / Arts Support'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '宿・転職・戦技補佐'
new = 'Inn / Vocation / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = 'オーブ交換：クレスト'
new = 'Orb Exchange: Crests'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'エリアマスター'
new = 'Area Master'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '食堂'
new = 'Cafeteria'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'エリアマスター・戦技補佐'
new = 'Area Master / Arts Support'
[[message]]
old = 'ジョブマスター：スピリットランサー'
new = 'Job Master: Spirit Lancer'
[[message]]
old = '復活力の回復'
new = 'Recover Revival Power'
[[message]]
old = 'ポーン遠征隊'
new = 'Pawn Expedition Corps'
[[message]]
old = 'グランドミッション：呼び覚まされし竜'
new = 'Grand Mission: The Dragon Awakened'
[[message]]
old = 'グランドミッション：古代神殿の死闘'
new = 'Grand Mission: The Deathly Battle of the Ancient Temple'
[[message]]
old = 'エリアマスター・紋章メダル交換'
new = 'Area Master / Emblem Medal Exchange'
[[message]]
old = 'エリアマスター・紋章メダル交換'
new = 'Area Master / Emblem Medal Exchange'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '宿・転職・戦技補佐'
new = 'Inn / Vocation / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '戦技補佐'
new = 'Arts Support'
[[message]]
old = '宿屋'
new = 'Inn'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'オーブ交換：クレスト'
new = 'Orb Exchange: Crests'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = 'エリアマスター・紋章メダル交換'
new = 'Area Master / Emblem Medal Exchange'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '戦技補佐'
new = 'Arts Support'
[[message]]
old = '宿屋'
new = 'Inn'
[[message]]
old = '武具屋'
new = 'Equipment Shop'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'エリアマスター・紋章メダル交換'
new = 'Area Master / Emblem Medal Exchange'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '転職・戦技補佐'
new = 'Vocation / Arts Support'
[[message]]
old = '防具屋'
new = 'Armor Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'バザー'
new = 'Bazaar'
[[message]]
old = 'クラフト係官'
new = 'Craft Officer'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = 'ジョブマスター：ハイセプター'
new = 'Job Master: High Scepter'
[[message]]
old = 'ウォーミッション：ジフール砦'
new = 'War Mission: Jifule Fortress'
[[message]]
old = '戦技補佐'
new = 'Arts Support'
[[message]]
old = 'ウォーミッション：ダクレイム砦'
new = 'War Mission: Dacreim Fortress'
[[message]]
old = '戦技補佐'
new = 'Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = 'バザー'
new = 'Bazaar'
[[message]]
old = '宿屋'
new = 'Inn'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '道具屋'
new = 'Item Shop'
[[message]]
old = 'クラン拠点管理'
new = 'Clan Hall Management'
[[message]]
old = 'カスタムメイド工房'
new = 'Custom-Made Workshop'
[[message]]
old = 'クラン拠点管理'
new = 'Clan Hall Management'
[[message]]
old = 'セレクトショップ'
new = 'Secret Shop'
[[message]]
old = '鑑定交換'
new = 'Appraisal Exchange'
[[message]]
old = '冒険サポート係'
new = 'Adventure Support Staff'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = 'よろず屋'
new = 'General Shop'
[[message]]
old = '冒険仲介係'
new = 'Adventure Organizer'
[[message]]
old = '宿・戦技補佐'
new = 'Inn / Arts Support'
[[message]]
old = '美容院'
new = 'Beauty Salon'
[[message]]
old = '鑑定交換'
new = 'Appraisal Exchange'
[[message]]
old = '復活力・ログインスタンプ'
new = 'Revival Power / Login Stamp'
[[message]]
old = '武器屋'
new = 'Weapon Shop'
[[message]]
old = 'ウォーミッション：霧の森の死闘'
new = 'War Mission: The Deathly Battle of the Forest of Mist'
[[message]]
old = 'ウォーミッション：蘇りし絶望の炎'
new = 'War Mission: Resurrection of the Flame of Despair'
[[message]]
old = 'カスタムメイド工房'
new = 'Custom-Made Workshop'
[[message]]
old = '戦技補佐'
new = 'Arts Support'
[[message]]
old = 'ウォーミッション：アッカーシェラン追懐戦記'
new = 'War Mission: Acre Selund War Chronicles'
[[message]]
old = '黒呪の迷宮 案内人'
new = 'Bitterblack Maze Guide'
[[message]]
old = '黒呪の迷宮 案内人'
new = 'Bitterblack Maze Guide'
[[message]]
old = '黒呪の迷宮 案内人'
new = 'Bitterblack Maze Guide'
[[message]]
old = '滅びの渦対策本部'
[[message]]
old = '黒呪の迷宮 案内人'
new = 'Bitterblack Maze Guide'
