[[message]]
key = 'q00030410_00_86'
old = '理の崩壊'
[[message]]
key = 'q00030410_00_86'
old = '''
理の世界に起きようとしている
不穏な出来事を白竜と共に垣間見る'''
[[message]]
key = 'q00030410_00_4992'
old = '白竜の元へ向かう'
new = 'Seek out the White Dragon'
[[message]]
key = 'q00030410_00_5193'
old = '白竜と共に自身の竜の目で理が壊される様を垣間見る'
[[message]]
key = 'q00030410_00_4993'
old = 'ジョゼフと話す'
new = 'Speak with Joseph'
[[message]]
key = 'q00030410_00_4994'
old = '覚者隊と共にフィンダムへ向かう'
new = 'Head to Phindym with the Arisen Corps'
[[message]]
key = 'q00030410_00_5127'
old = 'ガラダの使いのミューセルと話す'
new = "Speak with Gearóid's envoy Musel"
[[message]]
key = 'q00030410_00_4995'
old = 'シェドレアン大神殿前で待つガラダの元へ向かう'
new = 'Head to Gearóid waiting before Shadolean Great Temple'
[[message]]
key = 'q00030410_00_4996'
old = 'エラン水林にいるモードレッドの元へ向かう'
new = 'Rendezvous with Mordred in the Elan Water Grove'
[[message]]
key = 'q00030410_00_4997'
old = '黒剣の場所へ向かう'
new = 'Head to the location of the Black Sword'
[[message]]
key = 'q00030410_00_4998'
old = '魔物を倒し黒剣を破壊する'
[[message]]
key = 'q00030410_00_4999'
old = 'モードレッドに報告する'
new = 'Report to Mordred'
[[message]]
key = 'q00030410_00_5000'
old = 'キンガル峡谷に向かい黒剣を探す'
[[message]]
key = 'q00030410_00_5001'
old = '魔物を倒し黒剣を破壊する'
[[message]]
key = 'q00030410_00_5002'
old = '始まりの洞へ向かい新たな黒剣の情報を得る'
[[message]]
key = 'q00030410_00_5229'
old = '精霊竜のねぐらへ向かい黒剣を探す'
[[message]]
key = 'q00030410_00_5003'
old = '魔物を倒し黒剣を破壊する'
[[message]]
key = 'q00030410_00_5004'
old = 'アデルドナハと話す'
new = 'Speak with Adair Donnchadh'
[[message]]
key = 'q00030410_00_5005'
old = '渦に呑みこまれようとしているシェドレアン大神殿へ向かう'
new = 'Head to 渦に呑みこまれようとしているシェドレアン大神殿'
[[message]]
key = 'q00030410_00_5017'
old = 'レスタニアに帰還し白竜と話す'
new = 'Return to Lestania and speak with the White Dragon'
[[message]]
key = 'q00030410_00_5126'
old = 'ジョゼフと話す'
new = 'Speak with Joseph'
[[message]]
key = 'q00030410_00_5018'
old = 'トラバースの元へ向かう'
new = 'Seek out Travers'
[[message]]
key = 'q00030410_00_5047'
old = 'トラバースから大竜晶破壊戦：抗う大地を受諾してクリアする'
[[message]]
key = 'q00030410_00_5048'
old = 'トラバースに報告する'
new = 'Report to Travers'
[[message]]
key = 'q00030410_00_5128'
old = '白竜の元へ向かう'
new = 'Seek out the White Dragon'
[[message]]
key = 'q00030410_00_5049'
old = 'シェドレアン大神殿で待つ覚者隊の元へ向かう'
new = 'Head to シェドレアン大神殿で待つ覚者隊の元'
[[message]]
key = 'q00030410_00_5050'
old = '大神殿内の闇の波動に変化の現れた場所を目指す'
[[message]]
key = 'q00030410_00_5064'
old = '遭遇した魔物を倒す'
new = 'Defeat the encountered demons'
[[message]]
key = 'q00030410_00_5069'
old = '滅びの渦の魔物を倒す'
new = 'Defeat 滅びの渦の魔物'
[[message]]
key = 'q00030410_00_5070'
old = '始まりの洞へ戻る'
new = 'Return to the Hollow of Beginnings'
[[message]]
key = 'q00030410_00_5072'
old = 'レスタニアに帰還しジョゼフに報告する'
new = 'Return to Lestania and report to Joseph'
