[[message]]
key = 'q00030250_00_85'
old = '初代王の遺品'
new = 'The Relics of the First King'
[[message]]
key = 'q00030250_00_85'
old = '火垂れ山へ入るための門へ向かう'
new = 'Head to the gate to enter Firefall Mountain'
[[message]]
key = 'q00030250_00_4576'
old = '火垂れ山の入口へ向かう'
new = 'Head to the entrance of Firefall Mountain'
[[message]]
key = 'q00030250_00_4577'
old = 'ジリアンと落ち合うためメガド居住層へ向かう'
new = 'Head to the Megado residential level to rendezvous with Gillian'
[[message]]
key = 'q00030250_00_4578'
old = 'ジリアンから得た情報の屋敷を調べる'
[[message]]
key = 'q00030250_00_4592'
old = '冒険者のメッセージを頼りに次の場所を探す'
[[message]]
key = 'q00030250_00_4579'
old = 'ウルテカ山岳東部の洞窟へ向かう'
new = 'Head to the cave in eastern Urteca Mountains'
[[message]]
key = 'q00030250_00_4580'
old = '初代王の遺品の指輪を探す'
[[message]]
key = 'q00030250_00_4581'
old = '遭遇した敵を殲滅する'
new = 'Defeat the enemy encountered'
[[message]]
key = 'q00030250_00_4582'
old = '初代王の遺品の指輪を探す'
[[message]]
key = 'q00030250_00_4583'
old = '火垂れ山の入口にいるセロに報告する'
new = 'Report to Cyril at the entrance to Firefall Mountain'
[[message]]
key = 'q00030250_00_4709'
old = 'レスタニアに帰還しジョゼフに報告する'
new = 'Return to Lestania and report to Joseph'
