[[message]]
key = 'q00030430_00_88'
old = '白竜の覚者'
[[message]]
key = 'q00030430_00_88'
old = '''
レスタニアに現れた滅びの渦に対処するために
ファビオの元へ向かう'''
[[message]]
key = 'q00030430_00_5024'
old = 'ダウ渓谷のジンゲンにいるファビオの元へ向かう'
new = 'Rendezvous with Fabio in ダウ渓谷のジンゲン'
[[message]]
key = 'q00030430_00_5025'
old = 'エルテ・ディナンに向かい黒剣を探す'
[[message]]
key = 'q00030430_00_5026'
old = '魔物を倒し黒剣を破壊する'
[[message]]
key = 'q00030430_00_5198'
old = 'リングディールと話す'
new = 'Speak with Ringdeel'
[[message]]
key = 'q00030430_00_5027'
old = 'ガルドノック砦に向かい仲間を探す'
[[message]]
key = 'q00030430_00_5028'
old = 'エリオット達と合流する'
new = 'Rendezvous with Elliot'
[[message]]
key = 'q00030430_00_5029'
old = '黒剣とハインツ率いる騎士団を探す'
[[message]]
key = 'q00030430_00_5030'
old = '魔物を倒し黒剣を破壊する'
[[message]]
key = 'q00030430_00_5031'
old = 'ハインツと話す'
new = 'Speak with Heinz'
[[message]]
key = 'q00030430_00_5032'
old = 'ゲルト団長が囮役を買った禊の神殿へ向かう'
new = 'Head to ゲルト団長が囮役を買った禊の神殿'
[[message]]
key = 'q00030430_00_5120'
old = '淀みの渦へ向かう'
new = 'Head to the Vortex of Stagnation'
[[message]]
key = 'q00030430_00_5033'
old = '黒騎士の幻影を倒し黒剣を破壊する'
[[message]]
key = 'q00030430_00_5034'
old = 'ゲルトと話す'
new = 'Speak with Gerd'
[[message]]
key = 'q00030430_00_5035'
old = 'ヴァネッサ率いる白翼覚者隊の待つドリード城へ向かう'
new = 'Head to ヴァネッサ率いる白翼覚者隊 waiting in Dreed Castle'
[[message]]
key = 'q00030430_00_5054'
old = '白竜神殿のトラバースの元へ向かう'
new = 'Head to Travers in the White Dragon Temple'
[[message]]
key = 'q00030430_00_5055'
old = 'トラバースから大竜晶破壊戦：主無き古城を受諾してクリアする'
[[message]]
key = 'q00030430_00_5056'
old = 'トラバースに報告する'
new = 'Report to Travers'
[[message]]
key = 'q00030430_00_5057'
old = 'ドリード城で待つスケルツォの元へ向かう'
new = 'Head to ドリード城で待つスケルツォの元'
[[message]]
key = 'q00030430_00_5065'
old = 'ドリード城内に出現したゲートの場所へ向かう'
new = 'Head to the location of ドリード城内に出現したゲート'
[[message]]
key = 'q00030430_00_5066'
old = '遭遇した魔物を倒す'
new = 'Defeat the encountered demons'
[[message]]
key = 'q00030430_00_5078'
old = 'ヴァネッサと話す'
new = 'Speak with Vanessa'
[[message]]
key = 'q00030430_00_5079'
old = '滅びの渦へ突入する'
new = 'Storm into 滅びの渦'
[[message]]
key = 'q00030430_00_5080'
old = '黒騎士を倒す'
new = 'Defeat the Black Knight'
[[message]]
key = 'q00030430_00_5081'
old = 'ヴァネッサと話す'
new = 'Speak with Vanessa'
[[message]]
key = 'q00030430_00_5082'
old = '白竜神殿に帰還しジョゼフに報告する'
new = 'Return to the White Dragon Temple and report to Joseph'
