[[message]]
key = 'q00030220_00_84'
old = 'ネドの足取り'
new = "Nedo's Trail"
[[message]]
key = 'q00030220_00_84'
old = '''
火垂れ山へ向かったと考えられる、ネド王子の
足取りを探るため展望城へ向かう'''
[[message]]
key = 'q00030220_00_4541'
old = '展望城へ向かう'
new = 'Head to the Lookout Castle'
[[message]]
key = 'q00030220_00_4542'
old = 'ウルテカ山岳にある北の盗賊の集落へ向かう'
new = 'Head to the northern bandit community in the Urteca Mountains'
[[message]]
key = 'q00030220_00_4544'
old = '北の盗賊の頭目セロと話す'
new = 'Speak with the northern bandit leader Cyril'
[[message]]
key = 'q00030220_00_4545'
old = 'エリアマスターのバシアスと話す'
new = 'Speak with Bacias, the Area Master'
[[message]]
key = 'q00030220_00_4546'
old = '礎を解放する'
new = 'Activate the portcrystal'
[[message]]
key = 'q00030220_00_4609'
old = '捜索状況の確認へ向かう'
new = 'Head to confirm the search situation'
[[message]]
key = 'q00030220_00_4547'
old = 'ベルタの手の者と落ち合う'
new = "Rendezvous with Bertha's subordinate"
[[message]]
key = 'q00030220_00_4548'
old = '攫われた王子の追跡者の手掛かりを探す（残り２）'
[[message]]
key = 'q00030220_00_4549'
old = '攫われた王子の追跡者の手掛かりを探す（残り１）'
[[message]]
key = 'q00030220_00_4662'
old = '敵を殲滅し盗賊団員を助ける'
[[message]]
key = 'q00030220_00_4663'
old = '助けた盗賊団員と話す'
new = 'Speak with the assisting bandit group member'
[[message]]
key = 'q00030220_00_4551'
old = '新たな手掛かりの場所へ向かう'
new = 'Head to the location of the fresh trail'
[[message]]
key = 'q00030220_00_4552'
old = '遭遇した敵を殲滅する'
new = 'Defeat the enemy encountered'
[[message]]
key = 'q00030220_00_4553'
old = '負傷した女性と話す'
new = 'Speak with the injured woman'
[[message]]
key = 'q00030220_00_4554'
old = 'スライと話す'
new = 'Speak with Sly'
[[message]]
key = 'q00030220_00_4555'
old = '北の盗賊の集落へ戻る'
new = 'Return to the northern bandit community'
[[message]]
key = 'q00030220_00_4556'
old = '展望城へ戻りメイロワに報告する'
new = 'Return to the Lookout Castle and report to Meirova'
[[message]]
key = 'q00030220_00_4664'
old = 'レスタニアに帰還しジョゼフに報告する'
new = 'Return to Lestania and report to Joseph'
