[[message]]
key = 'q15020001_00_5'
old = 'Bランク　指定討伐：ディナン深層林'
new = 'B Rank Target Subjugation: Deenan Woods'
[[message]]
key = 'q15020001_00_5'
old = ''
[[message]]
key = 'q15020001_00_5092'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15020001_00_5143'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15020001_00_5144'
old = 'リサに報告する'
new = 'Report to Lisa'
