[[message]]
key = 'q15070001_00_20'
old = 'Bランク　指定討伐：ザンドラ禁域'
new = 'B Rank Target Subjugation: Zandora Wastelands'
[[message]]
key = 'q15070001_00_20'
old = ''
[[message]]
key = 'q15070001_00_5107'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15070001_00_5173'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15070001_00_5174'
old = 'リサに報告する'
new = 'Report to Lisa'
