[[message]]
key = 'q15030001_00_8'
old = 'Bランク　指定討伐：ミスリウ森林'
new = 'B Rank Target Subjugation: Mysree Forest'
[[message]]
key = 'q15030001_00_8'
old = ''
[[message]]
key = 'q15030001_00_5095'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15030001_00_5149'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15030001_00_5150'
old = 'リサに報告する'
new = 'Report to Lisa'
