[[message]]
key = 'q15040003_00_13'
old = 'Sランク　指定討伐：ボルド鉱山'
new = 'S Rank Target Subjugation: Volden Mines'
[[message]]
key = 'q15040003_00_13'
old = ''
[[message]]
key = 'q15040003_00_5100'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15040003_00_5159'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15040003_00_5160'
old = 'リサに報告する'
new = 'Report to Lisa'
