[[message]]
key = 'q15040001_00_11'
old = 'Bランク　指定討伐：ボルド鉱山'
new = 'B Rank Target Subjugation: Volden Mines'
[[message]]
key = 'q15040001_00_11'
old = ''
[[message]]
key = 'q15040001_00_5098'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15040001_00_5155'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15040001_00_5156'
old = 'リサに報告する'
new = 'Report to Lisa'
