[[message]]
key = 'q15030003_00_10'
old = 'Sランク　指定討伐：ミスリウ森林'
new = 'S Rank Target Subjugation: Mysree Forest'
[[message]]
key = 'q15030003_00_10'
old = ''
[[message]]
key = 'q15030003_00_5097'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15030003_00_5153'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15030003_00_5154'
old = 'リサに報告する'
new = 'Report to Lisa'
