[[message]]
key = 'q15050003_00_16'
old = 'Sランク　指定討伐：ダウ渓谷'
new = 'S Rank Target Subjugation: Dowe Valley'
[[message]]
key = 'q15050003_00_16'
old = ''
[[message]]
key = 'q15050003_00_5103'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15050003_00_5165'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15050003_00_5166'
old = 'リサに報告する'
new = 'Report to Lisa'
