[[message]]
key = 'q15050002_00_15'
old = 'Aランク　指定討伐：ダウ渓谷'
new = 'A Rank Target Subjugation: Dowe Valley'
[[message]]
key = 'q15050002_00_15'
old = ''
[[message]]
key = 'q15050002_00_5102'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15050002_00_5163'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15050002_00_5164'
old = 'リサに報告する'
new = 'Report to Lisa'
