[[message]]
key = 'q15010001_00_2'
old = 'Bランク　指定討伐：ハイデル平原'
new = 'B Rank Target Subjugation: Hidell Plains'
[[message]]
key = 'q15010001_00_2'
old = ''
[[message]]
key = 'q15010001_00_5089'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15010001_00_5137'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15010001_00_5138'
old = 'リサに報告する'
new = 'Report to Lisa'
