[[message]]
key = 'q15060003_00_19'
old = 'Sランク　指定討伐：バートランド平原'
new = 'S Rank Target Subjugation: Betland Plains'
[[message]]
key = 'q15060003_00_19'
old = ''
[[message]]
key = 'q15060003_00_5106'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15060003_00_5171'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15060003_00_5172'
old = 'リサに報告する'
new = 'Report to Lisa'
