[[message]]
key = 'q15060001_00_17'
old = 'Bランク　指定討伐：バートランド平原'
[[message]]
key = 'q15060001_00_17'
old = ''
[[message]]
key = 'q15060001_00_5104'
old = '地域に潜む魔物を探す'
[[message]]
key = 'q15060001_00_5167'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15060001_00_5168'
old = 'リサに報告する'
new = 'Report to Lisa'
