[[message]]
key = 'q15030002_00_9'
old = 'Aランク　指定討伐：ミスリウ森林'
new = 'A Rank Target Subjugation: Mysree Forest'
[[message]]
key = 'q15030002_00_9'
old = ''
[[message]]
key = 'q15030002_00_5096'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15030002_00_5151'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15030002_00_5152'
old = 'リサに報告する'
new = 'Report to Lisa'
