[[message]]
key = 'q15020002_00_6'
old = 'Aランク　指定討伐：ディナン深層林'
new = 'A Rank Target Subjugation: Deenan Woods'
[[message]]
key = 'q15020002_00_6'
old = ''
[[message]]
key = 'q15020002_00_5093'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15020002_00_5145'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15020002_00_5146'
old = 'リサに報告する'
new = 'Report to Lisa'
