[[message]]
key = 'q15050001_00_14'
old = 'Bランク　指定討伐：ダウ渓谷'
new = 'B Rank Target Subjugation: Dowe Valley'
[[message]]
key = 'q15050001_00_14'
old = ''
[[message]]
key = 'q15050001_00_5101'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15050001_00_5161'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15050001_00_5162'
old = 'リサに報告する'
new = 'Report to Lisa'
