[[message]]
key = 'q15060002_00_18'
old = 'Aランク　指定討伐：バートランド平原'
new = 'A Rank Target Subjugation: Betland Plains'
[[message]]
key = 'q15060002_00_18'
old = ''
[[message]]
key = 'q15060002_00_5105'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15060002_00_5169'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15060002_00_5170'
old = 'リサに報告する'
new = 'Report to Lisa'
