[[message]]
key = 'q15010002_00_3'
old = 'Aランク　指定討伐：ハイデル平原'
new = 'A Rank Target Subjugation: Hidell Plains'
[[message]]
key = 'q15010002_00_3'
old = ''
[[message]]
key = 'q15010002_00_5090'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15010002_00_5139'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15010002_00_5140'
old = 'リサに報告する'
new = 'Report to Lisa'
