[[message]]
key = 'q15080001_00_21'
old = 'Bランク　指定討伐：亡都メルゴダ'
new = 'B Rank Target Subjugation: Mergoda Ruins'
[[message]]
key = 'q15080001_00_21'
old = ''
[[message]]
key = 'q15080001_00_5108'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15080001_00_5175'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15080001_00_5176'
old = 'リサに報告する'
new = 'Report to Lisa'
