[[message]]
key = 'q15150003_00_28'
old = 'Aランク　指定討伐：ウルテカ山岳'
new = 'A Rank Target Subjugation: Urteca Mountains'
[[message]]
key = 'q15150003_00_28'
old = ''
[[message]]
key = 'q15150003_00_5115'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15150003_00_5189'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15150003_00_5190'
old = 'リサに報告する'
new = 'Report to Lisa'
