[[message]]
key = 'q15110002_00_24'
old = 'Aランク　指定討伐：ファーラナ平原'
new = 'A Rank Target Subjugation: Farana Plains'
[[message]]
key = 'q15110002_00_24'
old = ''
[[message]]
key = 'q15110002_00_5111'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15110002_00_5181'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15110002_00_5182'
old = 'リサに報告する'
new = 'Report to Lisa'
