[[message]]
key = 'q15120002_00_25'
old = 'Sランク　指定討伐：キンガル峡谷'
new = 'S Rank Target Subjugation: Kingal Canyon'
[[message]]
key = 'q15120002_00_25'
old = ''
[[message]]
key = 'q15120002_00_5112'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15120002_00_5183'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15120002_00_5184'
old = 'リサに報告する'
new = 'Report to Lisa'
