[[message]]
key = 'q15110001_00_29'
old = 'Bランク　指定討伐：ファーラナ平原'
new = 'B Rank Target Subjugation: Farana Plains'
[[message]]
key = 'q15110001_00_29'
old = ''
[[message]]
key = 'q15110001_00_5231'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15110001_00_5232'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15110001_00_5233'
old = 'リサに報告する'
new = 'Report to Lisa'
