[[message]]
key = 'q15140003_00_27'
old = 'Sランク　指定討伐：メガドシス高地'
new = 'S Rank Target Subjugation: Megadosys Plateau'
[[message]]
key = 'q15140003_00_27'
old = ''
[[message]]
key = 'q15140003_00_5114'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15140003_00_5187'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15140003_00_5188'
old = 'リサに報告する'
new = 'Report to Lisa'
