[[message]]
key = 'q15110003_00_30'
old = 'Sランク　指定討伐：ファーラナ平原'
new = 'S Rank Target Subjugation: Farana Plains'
[[message]]
key = 'q15110003_00_30'
old = ''
[[message]]
key = 'q15110003_00_5234'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15110003_00_5235'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15110003_00_5236'
old = 'リサに報告する'
new = 'Report to Lisa'
