[[message]]
key = 'q15100002_00_23'
old = 'Aランク　指定討伐：モロー樹林'
new = 'A Rank Target Subjugation: Morrow Forest'
[[message]]
key = 'q15100002_00_23'
old = ''
[[message]]
key = 'q15100002_00_5110'
old = '地域に潜む魔物を探す'
new = 'Search for the demons lurking in the area'
[[message]]
key = 'q15100002_00_5179'
old = '発見した魔物を討伐する'
new = 'Defeat the found demons'
[[message]]
key = 'q15100002_00_5180'
old = 'リサに報告する'
new = 'Report to Lisa'
