[[message]]
key = 'q60300203_00_352'
old = '王冠と王笏＜４＞'
new = 'Crown and Scepter IV'
[[message]]
key = 'q60300203_00_352'
old = '''
キルスティから
初代王の指輪について話を聞く'''
[[message]]
key = 'q60300203_00_4822'
old = '崩れた進入路へ向かう'
new = 'Head to the Crumbling Entrance Path'
[[message]]
key = 'q60300203_00_4823'
old = 'キルスティと合流する'
new = 'Rendezvous with Kirsty'
[[message]]
key = 'q60300203_00_4824'
old = '指輪を見つけた場所へ向かう'
new = 'Head to 指輪を見つけた場所'
[[message]]
key = 'q60300203_00_4842'
old = 'キルスティと話をする'
new = 'Speak to Kirsty'
[[message]]
key = 'q60300203_00_4825'
old = '出現した敵を殲滅する'
new = 'Defeat the enemy that has appeared'
[[message]]
key = 'q60300203_00_4873'
old = '急襲の敵を倒す'
new = 'Defeat 急襲の敵'
[[message]]
key = 'q60300203_00_4826'
old = 'キルスティと話をする'
new = 'Speak to Kirsty'
[[message]]
key = 'q60300203_00_4827'
old = '高地のあばら屋へ戻る'
new = 'Return to the Plateau Shack'
