[[message]]
key = 'q60340002_00_364'
old = '麗しの君へ綴る文＜１＞'
[[message]]
key = 'q60340002_00_364'
old = '''
アンジェロと今年のホワイトデーのため
プレゼントを作る'''
[[message]]
key = 'q60340002_00_5217'
old = '《パッションパピルス》を入手する'
new = 'Obtain "Passion Papyrus"'
[[message]]
key = 'q60340002_00_5218'
old = 'アンジェロに報告する'
new = 'Report to Angelo'
[[message]]
key = 'q60340002_00_5219'
old = 'グレゴリーに相談する'
new = 'Consult with Gregory'
[[message]]
key = 'q60340002_00_5220'
old = '鑑定交換で《ロマンチックな手紙》を入手する'
new = 'Obtain "Romantic Letter" at Appraisal Exchange'
[[message]]
key = 'q60340002_00_5221'
old = 'アンジェロに報告する'
new = 'Report to Angelo'
