[[message]]
key = 'q60340000_00_362'
old = '一目ごとに想いを込めて＜１＞'
[[message]]
key = 'q60340000_00_362'
old = '''
シェリーと今年のバレンタインのため
プレゼントを作る'''
[[message]]
key = 'q60340000_00_5212'
old = '《もこもこ毛糸》を入手する'
new = 'Obtain "Fluffy Yarn"'
[[message]]
key = 'q60340000_00_5213'
old = 'シェリーに報告する'
new = 'Report to Shelly'
[[message]]
key = 'q60340000_00_5214'
old = 'グレゴリーに相談する'
new = 'Consult with Gregory'
[[message]]
key = 'q60340000_00_5215'
old = '鑑定交換で《手編みのニット》を入手する'
new = 'Obtain "手編みのニット" at Appraisal Exchange'
[[message]]
key = 'q60340000_00_5216'
old = 'シェリーに報告する'
new = 'Report to Shelly'
