[[message]]
key = 'q90030302_00_115'
old = '霧の森の死闘'
new = 'The Deathly Battle of the Forest of Mist'
[[message]]
key = 'q90030302_00_115'
old = '''
霧の森でのウォーミッションは終了した
各々の戦果については追って報告があるので
それまでは待機とする'''
[[message]]
key = 'q90030302_00_115'
old = ''
[[message]]
key = 'q90030302_00_115'
old = ''
