[[message]]
key = 'q90030306_00_137'
old = '霧の森の死闘　戦況：大将奮起'
[[message]]
key = 'q90030306_00_137'
old = '''
霧の森に闇の将が出現した！
森に潜む魔竜軍のリーダー格を
白竜の覚者達が一丸となって追い詰めたのだ
闇の将は覚者を異界へ送らんと目論む強敵である
メンバー同士の協力が不可欠であり、異界へ送られる
覚者をいかにして守り、素早く救出するかが重要だ'''
[[message]]
key = 'q90030306_00_5290'
old = '霧の森を征圧する（残り２０分）'
new = 'Conquer the Forest of Mist (20 min left)'
[[message]]
key = 'q90030306_00_5291'
old = '霧の森を征圧する（残り１９分）'
new = 'Conquer the Forest of Mist (19 min left)'
[[message]]
key = 'q90030306_00_5292'
old = '霧の森を征圧する（残り１８分）'
new = 'Conquer the Forest of Mist (18 min left)'
[[message]]
key = 'q90030306_00_5293'
old = '霧の森を征圧する（残り１７分）'
new = 'Conquer the Forest of Mist (17 min left)'
[[message]]
key = 'q90030306_00_5294'
old = '霧の森を征圧する（残り１６分）'
new = 'Conquer the Forest of Mist (16 min left)'
[[message]]
key = 'q90030306_00_5295'
old = '霧の森を征圧する（残り１５分）'
new = 'Conquer the Forest of Mist (15 min left)'
[[message]]
key = 'q90030306_00_5296'
old = '霧の森を征圧する（残り１４分）'
new = 'Conquer the Forest of Mist (14 min left)'
[[message]]
key = 'q90030306_00_5297'
old = '霧の森を征圧する（残り１３分）'
new = 'Conquer the Forest of Mist (13 min left)'
[[message]]
key = 'q90030306_00_5298'
old = '霧の森を征圧する（残り１２分）'
new = 'Conquer the Forest of Mist (12 min left)'
[[message]]
key = 'q90030306_00_5299'
old = '霧の森を征圧する（残り１１分）'
new = 'Conquer the Forest of Mist (11 min left)'
[[message]]
key = 'q90030306_00_5300'
old = '霧の森を征圧する（残り１０分）'
new = 'Conquer the Forest of Mist (10 min left)'
[[message]]
key = 'q90030306_00_5301'
old = '霧の森を征圧する（残り９分）'
new = 'Conquer the Forest of Mist (9 min left)'
[[message]]
key = 'q90030306_00_5302'
old = '霧の森を征圧する（残り８分）'
new = 'Conquer the Forest of Mist (8 min left)'
[[message]]
key = 'q90030306_00_5303'
old = '霧の森を征圧する（残り７分）'
new = 'Conquer the Forest of Mist (7 min left)'
[[message]]
key = 'q90030306_00_5304'
old = '霧の森を征圧する（残り６分）'
new = 'Conquer the Forest of Mist (6 min left)'
[[message]]
key = 'q90030306_00_5305'
old = '霧の森を征圧する（残り５分）'
new = 'Conquer the Forest of Mist (5 min left)'
[[message]]
key = 'q90030306_00_5306'
old = '霧の森を征圧する（残り４分）'
new = 'Conquer the Forest of Mist (4 min left)'
[[message]]
key = 'q90030306_00_5307'
old = '霧の森を征圧する（残り３分）'
new = 'Conquer the Forest of Mist (3 min left)'
[[message]]
key = 'q90030306_00_5308'
old = '霧の森を征圧する（残り２分）'
new = 'Conquer the Forest of Mist (2 min left)'
[[message]]
key = 'q90030306_00_5309'
old = '霧の森を征圧する（残り１分）'
new = 'Conquer the Forest of Mist (1 min left)'
[[message]]
key = 'q90030306_00_137'
old = ''
[[message]]
key = 'q90030306_00_137'
old = ''
