[[message]]
key = 'q90040006_00_132'
old = '骸の将との戦い：ジフール砦'
[[message]]
key = 'q90040006_00_132'
old = '''
ジフール砦に骸の将が出現した！
骸の将は、配下となる魔物を絶えず召喚し続けては
魔物の力を自らに吸収して自身を強化する
召喚された魔物に素早く対処し、骸の将の
強化行動を阻止せよ'''
[[message]]
key = 'q90040006_00_4932'
old = 'ジフール砦を征圧する（残り２０分）'
new = 'Conquer Jifule Fortress (20 min left)'
[[message]]
key = 'q90040006_00_4933'
old = 'ジフール砦を征圧する（残り１９分）'
new = 'Conquer Jifule Fortress (19 min left)'
[[message]]
key = 'q90040006_00_4934'
old = 'ジフール砦を征圧する（残り１８分）'
new = 'Conquer Jifule Fortress (18 min left)'
[[message]]
key = 'q90040006_00_4935'
old = 'ジフール砦を征圧する（残り１７分）'
new = 'Conquer Jifule Fortress (17 min left)'
[[message]]
key = 'q90040006_00_4936'
old = 'ジフール砦を征圧する（残り１６分）'
new = 'Conquer Jifule Fortress (16 min left)'
[[message]]
key = 'q90040006_00_4937'
old = 'ジフール砦を征圧する（残り１５分）'
new = 'Conquer Jifule Fortress (15 min left)'
[[message]]
key = 'q90040006_00_4938'
old = 'ジフール砦を征圧する（残り１４分）'
new = 'Conquer Jifule Fortress (14 min left)'
[[message]]
key = 'q90040006_00_4939'
old = 'ジフール砦を征圧する（残り１３分）'
new = 'Conquer Jifule Fortress (13 min left)'
[[message]]
key = 'q90040006_00_4940'
old = 'ジフール砦を征圧する（残り１２分）'
new = 'Conquer Jifule Fortress (12 min left)'
[[message]]
key = 'q90040006_00_4941'
old = 'ジフール砦を征圧する（残り１１分）'
new = 'Conquer Jifule Fortress (11 min left)'
[[message]]
key = 'q90040006_00_4942'
old = 'ジフール砦を征圧する（残り１０分）'
new = 'Conquer Jifule Fortress (10 min left)'
[[message]]
key = 'q90040006_00_4943'
old = 'ジフール砦を征圧する（残り９分）'
new = 'Conquer Jifule Fortress (9 min left)'
[[message]]
key = 'q90040006_00_4944'
old = 'ジフール砦を征圧する（残り８分）'
new = 'Conquer Jifule Fortress (8 min left)'
[[message]]
key = 'q90040006_00_4945'
old = 'ジフール砦を征圧する（残り７分）'
new = 'Conquer Jifule Fortress (7 min left)'
[[message]]
key = 'q90040006_00_4946'
old = 'ジフール砦を征圧する（残り６分）'
new = 'Conquer Jifule Fortress (6 min left)'
[[message]]
key = 'q90040006_00_4947'
old = 'ジフール砦を征圧する（残り５分）'
new = 'Conquer Jifule Fortress (5 min left)'
[[message]]
key = 'q90040006_00_4948'
old = 'ジフール砦を征圧する（残り４分）'
new = 'Conquer Jifule Fortress (4 min left)'
[[message]]
key = 'q90040006_00_4949'
old = 'ジフール砦を征圧する（残り３分）'
new = 'Conquer Jifule Fortress (3 min left)'
[[message]]
key = 'q90040006_00_4950'
old = 'ジフール砦を征圧する（残り２分）'
new = 'Conquer Jifule Fortress (2 min left)'
[[message]]
key = 'q90040006_00_4951'
old = 'ジフール砦を征圧する（残り１分）'
new = 'Conquer Jifule Fortress (1 min left)'
[[message]]
key = 'q90040006_00_132'
old = ''
[[message]]
key = 'q90040006_00_132'
old = ''
