[[message]]
key = 'q90030303_00_116'
#NEEDS REVIEW
#霧の森の死闘：報酬受取
old = '霧の森の死闘'
new = 'The Deathly Battle of the Forest of Mist: Reward Receiving'
[[message]]
key = 'q90030303_00_116'
old = '''
メガドにいるアッバスより、各個人の戦果に
伴う報酬を受け取ることが出来る
特別な報酬には受け取るための条件や上限数が
あるため、貢献具合に応じた品物を選ぶように'''
[[message]]
key = 'q90030303_00_116'
old = ''
[[message]]
key = 'q90030303_00_116'
old = ''
