[[message]]
key = 'q90040008_00_134'
old = '闇の将との戦い：霧の森'
[[message]]
key = 'q90040008_00_134'
old = '''
霧の森に闇の将が出現した！
闇の将は、覚者を異界へ送る術を持つ強敵である
討ち果たすにはメンバー同士の協力が不可欠だ
特に異界へ送られそうな覚者をいかにして守り
素早く救出するかが重要となるだろう'''
[[message]]
key = 'q90040008_00_4972'
old = '霧の森を征圧する（残り２０分）'
new = 'Conquer the Forest of Mist (20 min left)'
[[message]]
key = 'q90040008_00_4973'
old = '霧の森を征圧する（残り１９分）'
new = 'Conquer the Forest of Mist (19 min left)'
[[message]]
key = 'q90040008_00_4974'
old = '霧の森を征圧する（残り１８分）'
new = 'Conquer the Forest of Mist (18 min left)'
[[message]]
key = 'q90040008_00_4975'
old = '霧の森を征圧する（残り１７分）'
new = 'Conquer the Forest of Mist (17 min left)'
[[message]]
key = 'q90040008_00_4976'
old = '霧の森を征圧する（残り１６分）'
new = 'Conquer the Forest of Mist (16 min left)'
[[message]]
key = 'q90040008_00_4977'
old = '霧の森を征圧する（残り１５分）'
new = 'Conquer the Forest of Mist (15 min left)'
[[message]]
key = 'q90040008_00_4978'
old = '霧の森を征圧する（残り１４分）'
new = 'Conquer the Forest of Mist (14 min left)'
[[message]]
key = 'q90040008_00_4979'
old = '霧の森を征圧する（残り１３分）'
new = 'Conquer the Forest of Mist (13 min left)'
[[message]]
key = 'q90040008_00_4980'
old = '霧の森を征圧する（残り１２分）'
new = 'Conquer the Forest of Mist (12 min left)'
[[message]]
key = 'q90040008_00_4981'
old = '霧の森を征圧する（残り１１分）'
new = 'Conquer the Forest of Mist (11 min left)'
[[message]]
key = 'q90040008_00_4982'
old = '霧の森を征圧する（残り１０分）'
new = 'Conquer the Forest of Mist (10 min left)'
[[message]]
key = 'q90040008_00_4983'
old = '霧の森を征圧する（残り９分）'
new = 'Conquer the Forest of Mist (9 min left)'
[[message]]
key = 'q90040008_00_4984'
old = '霧の森を征圧する（残り８分）'
new = 'Conquer the Forest of Mist (8 min left)'
[[message]]
key = 'q90040008_00_4985'
old = '霧の森を征圧する（残り７分）'
new = 'Conquer the Forest of Mist (7 min left)'
[[message]]
key = 'q90040008_00_4986'
old = '霧の森を征圧する（残り６分）'
new = 'Conquer the Forest of Mist (6 min left)'
[[message]]
key = 'q90040008_00_4987'
old = '霧の森を征圧する（残り５分）'
new = 'Conquer the Forest of Mist (5 min left)'
[[message]]
key = 'q90040008_00_4988'
old = '霧の森を征圧する（残り４分）'
new = 'Conquer the Forest of Mist (4 min left)'
[[message]]
key = 'q90040008_00_4989'
old = '霧の森を征圧する（残り３分）'
new = 'Conquer the Forest of Mist (3 min left)'
[[message]]
key = 'q90040008_00_4990'
old = '霧の森を征圧する（残り２分）'
new = 'Conquer the Forest of Mist (2 min left)'
[[message]]
key = 'q90040008_00_4991'
old = '霧の森を征圧する（残り１分）'
new = 'Conquer the Forest of Mist (1 min left)'
[[message]]
key = 'q90040008_00_134'
old = ''
[[message]]
key = 'q90040008_00_134'
old = ''
