[[message]]
key = 'q90030105_00_111'
old = 'ダクレイム砦奪還戦　戦況：大将討滅'
new = 'Dacreim Fortress Recapture Battle: Boss Annihilation'
[[message]]
key = 'q90030105_00_111'
old = '''
ダクレイム砦に獣の将が出現した！
この砦を占領した魔竜軍のリーダー格を
白竜の覚者達が一丸となって追い詰めたのだ
次々と手下を使役し、集団となって襲い来る獣の将は
手下の力を借りて更に強力な魔物を呼び寄せる力を
持っているようだ――使役される魔物への対処で
戦局は大きく左右することになるだろう'''
[[message]]
key = 'q90030105_00_3806'
old = 'ダクレイム砦を征圧する（残り２０分）'
new = 'Conquer Dacreim Fortress (20 min left)'
[[message]]
key = 'q90030105_00_3807'
old = 'ダクレイム砦を征圧する（残り１９分）'
new = 'Conquer Dacreim Fortress (19 min left)'
[[message]]
key = 'q90030105_00_3808'
old = 'ダクレイム砦を征圧する（残り１８分）'
new = 'Conquer Dacreim Fortress (18 min left)'
[[message]]
key = 'q90030105_00_3809'
old = 'ダクレイム砦を征圧する（残り１７分）'
new = 'Conquer Dacreim Fortress (17 min left)'
[[message]]
key = 'q90030105_00_3810'
old = 'ダクレイム砦を征圧する（残り１６分）'
new = 'Conquer Dacreim Fortress (16 min left)'
[[message]]
key = 'q90030105_00_3811'
old = 'ダクレイム砦を征圧する（残り１５分）'
new = 'Conquer Dacreim Fortress (15 min left)'
[[message]]
key = 'q90030105_00_3812'
old = 'ダクレイム砦を征圧する（残り１４分）'
new = 'Conquer Dacreim Fortress (14 min left)'
[[message]]
key = 'q90030105_00_3813'
old = 'ダクレイム砦を征圧する（残り１３分）'
new = 'Conquer Dacreim Fortress (13 min left)'
[[message]]
key = 'q90030105_00_3814'
old = 'ダクレイム砦を征圧する（残り１２分）'
new = 'Conquer Dacreim Fortress (12 min left)'
[[message]]
key = 'q90030105_00_3815'
old = 'ダクレイム砦を征圧する（残り１１分）'
new = 'Conquer Dacreim Fortress (11 min left)'
[[message]]
key = 'q90030105_00_3411'
old = 'ダクレイム砦を征圧する（残り１０分）'
new = 'Conquer Dacreim Fortress (10 min left)'
[[message]]
key = 'q90030105_00_3523'
old = 'ダクレイム砦を征圧する（残り９分）'
new = 'Conquer Dacreim Fortress (9 min left)'
[[message]]
key = 'q90030105_00_3816'
old = 'ダクレイム砦を征圧する（残り８分）'
new = 'Conquer Dacreim Fortress (8 min left)'
[[message]]
key = 'q90030105_00_3817'
old = 'ダクレイム砦を征圧する（残り７分）'
new = 'Conquer Dacreim Fortress (7 min left)'
[[message]]
key = 'q90030105_00_3818'
old = 'ダクレイム砦を征圧する（残り６分）'
new = 'Conquer Dacreim Fortress (6 min left)'
[[message]]
key = 'q90030105_00_3819'
old = 'ダクレイム砦を征圧する（残り５分）'
new = 'Conquer Dacreim Fortress (5 min left)'
[[message]]
key = 'q90030105_00_3410'
old = 'ダクレイム砦を征圧する（残り４分）'
new = 'Conquer Dacreim Fortress (4 min left)'
[[message]]
key = 'q90030105_00_3820'
old = 'ダクレイム砦を征圧する（残り３分）'
new = 'Conquer Dacreim Fortress (3 min left)'
[[message]]
key = 'q90030105_00_3821'
old = 'ダクレイム砦を征圧する（残り２分）'
new = 'Conquer Dacreim Fortress (2 min left)'
[[message]]
key = 'q90030105_00_3822'
old = 'ダクレイム砦を征圧する（残り１分）'
new = 'Conquer Dacreim Fortress (1 min left)'
[[message]]
key = 'q90030105_00_111'
old = 'ウォーミッション：ダクレイム砦《リザルト報酬》'
new = 'War Mission: Dacreim Fortress (Result Reward)'
[[message]]
key = 'q90030105_00_111'
old = ''
