[[message]]
key = 'q90040000_00_126'
old = 'アッカーシェラン追懐戦記'
new = 'Acre Selund War Chronicles'
[[message]]
key = 'q90040000_00_126'
old = ''
[[message]]
key = 'q90040000_00_126'
old = ''
[[message]]
key = 'q90040000_00_126'
old = '3.4WM管理'
