[[message]]
key = 'q90040005_00_131'
old = '獣の将との戦い：ダクレイム砦'
[[message]]
key = 'q90040005_00_131'
old = '''
ダクレイム砦に獣の将が出現した！
魔物を率い、集団となって襲い来る獣の将は
使役する魔物の力を使い、さらに強力な魔物を
呼び寄せる策を持っているようだ――
配下にある魔物への対処で戦局は大きく
左右されることになるだろう'''
[[message]]
key = 'q90040005_00_4912'
old = 'ダクレイム砦を征圧する（残り２０分）'
new = 'Conquer Dacreim Fortress (20 min left)'
[[message]]
key = 'q90040005_00_4913'
old = 'ダクレイム砦を征圧する（残り１９分）'
new = 'Conquer Dacreim Fortress (19 min left)'
[[message]]
key = 'q90040005_00_4914'
old = 'ダクレイム砦を征圧する（残り１８分）'
new = 'Conquer Dacreim Fortress (18 min left)'
[[message]]
key = 'q90040005_00_4915'
old = 'ダクレイム砦を征圧する（残り１７分）'
new = 'Conquer Dacreim Fortress (17 min left)'
[[message]]
key = 'q90040005_00_4916'
old = 'ダクレイム砦を征圧する（残り１６分）'
new = 'Conquer Dacreim Fortress (16 min left)'
[[message]]
key = 'q90040005_00_4917'
old = 'ダクレイム砦を征圧する（残り１５分）'
new = 'Conquer Dacreim Fortress (15 min left)'
[[message]]
key = 'q90040005_00_4918'
old = 'ダクレイム砦を征圧する（残り１４分）'
new = 'Conquer Dacreim Fortress (14 min left)'
[[message]]
key = 'q90040005_00_4919'
old = 'ダクレイム砦を征圧する（残り１３分）'
new = 'Conquer Dacreim Fortress (13 min left)'
[[message]]
key = 'q90040005_00_4920'
old = 'ダクレイム砦を征圧する（残り１２分）'
new = 'Conquer Dacreim Fortress (12 min left)'
[[message]]
key = 'q90040005_00_4921'
old = 'ダクレイム砦を征圧する（残り１１分）'
new = 'Conquer Dacreim Fortress (11 min left)'
[[message]]
key = 'q90040005_00_4922'
old = 'ダクレイム砦を征圧する（残り１０分）'
new = 'Conquer Dacreim Fortress (10 min left)'
[[message]]
key = 'q90040005_00_4923'
old = 'ダクレイム砦を征圧する（残り９分）'
new = 'Conquer Dacreim Fortress (9 min left)'
[[message]]
key = 'q90040005_00_4924'
old = 'ダクレイム砦を征圧する（残り８分）'
new = 'Conquer Dacreim Fortress (8 min left)'
[[message]]
key = 'q90040005_00_4925'
old = 'ダクレイム砦を征圧する（残り７分）'
new = 'Conquer Dacreim Fortress (7 min left)'
[[message]]
key = 'q90040005_00_4926'
old = 'ダクレイム砦を征圧する（残り６分）'
new = 'Conquer Dacreim Fortress (6 min left)'
[[message]]
key = 'q90040005_00_4927'
old = 'ダクレイム砦を征圧する（残り５分）'
new = 'Conquer Dacreim Fortress (5 min left)'
[[message]]
key = 'q90040005_00_4928'
old = 'ダクレイム砦を征圧する（残り４分）'
new = 'Conquer Dacreim Fortress (4 min left)'
[[message]]
key = 'q90040005_00_4929'
old = 'ダクレイム砦を征圧する（残り３分）'
new = 'Conquer Dacreim Fortress (3 min left)'
[[message]]
key = 'q90040005_00_4930'
old = 'ダクレイム砦を征圧する（残り２分）'
new = 'Conquer Dacreim Fortress (2 min left)'
[[message]]
key = 'q90040005_00_4931'
old = 'ダクレイム砦を征圧する（残り１分）'
new = 'Conquer Dacreim Fortress (1 min left)'
[[message]]
key = 'q90040005_00_131'
old = ''
[[message]]
key = 'q90040005_00_131'
old = ''
