[[message]]
key = 'FURNITURE_GROUP_NAME_1'
old = '書斎'
new = 'Study'
[[message]]
key = 'FURNITURE_GROUP_NAME_2'
old = 'キッチン'
new = 'Kitchen'
[[message]]
key = 'FURNITURE_GROUP_NAME_3'
old = 'ベッド'
new = 'Bed'
[[message]]
key = 'FURNITURE_GROUP_NAME_4'
old = 'リビング'
new = 'Living Room'
[[message]]
key = 'FURNITURE_GROUP_NAME_7'
old = 'お風呂'
new = 'Bath'
[[message]]
key = 'FURNITURE_GROUP_NAME_8'
old = '室内の装飾'
new = 'Interior Decoration'
[[message]]
key = 'FURNITURE_GROUP_NAME_9'
old = '家具'
new = 'Furniture'
[[message]]
key = 'FURNITURE_GROUP_NAME_10'
old = '部屋着'
new = 'Loungewear'
[[message]]
key = 'FURNITURE_GROUP_NAME_11'
old = '庭具'
new = 'Garden Furniture'
[[message]]
key = 'FURNITURE_GROUP_NAME_12'
old = '壁紙'
new = 'Wallpaper'
[[message]]
key = 'FURNITURE_GROUP_NAME_13'
old = '時計'
new = 'Clock'
[[message]]
key = 'FURNITURE_GROUP_NAME_21'
old = '楽譜'
new = 'Sheet Music'
[[message]]
key = 'FURNITURE_GROUP_NAME_22'
old = 'ホログラム'
