[[message]]
key = 'FURNITURE_LAYOUT_NAME_1'
old = 'テーブルの種類'
new = 'Table Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_2'
old = '机右のミニテーブル'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_3'
old = 'キャビネットの種類'
new = 'Cabinet Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_4'
old = 'カーペットの種類'
new = 'Carpet Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_5'
old = '単品の椅子'
new = 'Single Chair'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_6'
old = '壁の本棚'
new = 'Wall Bookshelf'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_7'
old = 'キッチン・テーブルの種類'
new = 'Kitchen Table Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_8'
old = '釜まわり一式'
new = 'Full Kettle Set'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_9'
old = '料理'
new = 'Cuisine'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_10'
old = 'ぬいぐるみ・A'
new = 'Plush Doll - A'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_11'
old = 'ぬいぐるみ・B'
new = 'Plush Doll - B'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_12'
old = '調理場左の棚/食材'
new = 'Left Kitchen Shelf/Foodstuffs'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_13'
old = '調理器具セット'
new = 'Cookware Set'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_14'
old = 'ベッドの種類'
new = 'Bed Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_15'
old = 'パペットの種類'
new = 'Puppet Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_16'
old = 'バルコニー'
new = 'Balcony'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_17'
old = 'ランプの種類'
new = 'Lamp Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_18'
old = 'リビング・テーブルの種類'
new = 'Living Table Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_19'
old = '料理の種類'
new = 'Cuisine Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_20'
old = 'チェスト'
new = 'Chest'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_21'
old = 'チェストの置物'
new = 'Chest Figurine'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_25'
old = 'お風呂'
new = 'Bath'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_26'
old = '自室の装飾'
new = "Arisen's Room Decor"
[[message]]
key = 'FURNITURE_LAYOUT_NAME_27'
old = 'オブジェクト'
new = 'Object'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_28'
old = 'オブジェクト・B'
new = 'Object (B)'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_29'
old = '覚者の部屋着'
new = "Arisen's Loungewear"
[[message]]
key = 'FURNITURE_LAYOUT_NAME_30'
old = '従者の部屋着'
new = "Servant's Loungewear"
[[message]]
key = 'FURNITURE_LAYOUT_NAME_31'
old = '従者の湯浴み着'
new = "Servant's Bathing Clothes"
[[message]]
key = 'FURNITURE_LAYOUT_NAME_32'
old = '従者の寝巻き'
new = "Servant's Sleepwear"
[[message]]
key = 'FURNITURE_LAYOUT_NAME_34'
old = 'オブジェクト・A'
new = 'Object (A)'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_35'
old = '自室の照明'
new = "Arisen's Room Lighting"
[[message]]
key = 'FURNITURE_LAYOUT_NAME_36'
old = 'テーブルフラワー'
new = 'Table Flower'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_37'
old = 'テーブルフラワー'
new = 'Table Flower'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_38'
old = '天気予報'
new = 'Weather Forecast'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_39'
old = '壁紙'
new = 'Wallpaper'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_40'
old = '湯口'
new = 'Spout'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_41'
old = '鳩時計'
new = 'Cuckoo Clock'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_42'
old = '壁面家具・左'
new = 'Left Wall Furniture'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_43'
old = '壁面家具・右'
new = 'Right Wall Furniture'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_44'
old = 'カーペットの種類'
new = 'Carpet Type'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_45'
old = '家具'
new = 'Furniture'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_46'
old = '呼び鈴'
new = 'Summoning Bell'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_47'
old = 'マンドラゴラ鉢植え①ノーマル'
new = 'Mandagora Potted Plant 1 (Normal)'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_48'
old = 'マンドラゴラ鉢植え②パスポート'
new = 'Mandagora Potted Plant 2 (Passport)'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_49'
old = 'マンドラゴラ鉢植え③パスポート'
new = 'Mandagora Potted Plant 3 (Passport)'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_61'
old = '楽譜'
new = 'Sheet Music'
[[message]]
key = 'FURNITURE_LAYOUT_NAME_63'
old = 'ホログラムパターン'
