[[message]]
key = 'ORDER_CONDITION_988'
old = '無し'
new = 'None'
[[message]]
key = 'ORDER_CONDITION_989'
old = '全ジョブのいずれかがジョブレベル<QCND 0>以上'
new = 'Level <QCND 0> in any vocation'
[[message]]
key = 'ORDER_CONDITION_994'
old = 'ジョブ限定：<QCND 0>のジョブレベル<QCND 1>以上'
new = 'Vocation restriction: <QCND 0>, at least level <QCND 1>'
[[message]]
key = 'ORDER_CONDITION_995'
old = 'パーティープレイ不可（ポーン同行不可）'
new = 'No party members (pawns not allowed)'
[[message]]
key = 'ORDER_CONDITION_996'
old = '無し'
new = 'None'
[[message]]
key = 'ORDER_CONDITION_997'
old = '無し'
new = 'None'
[[message]]
key = 'ORDER_CONDITION_998'
old = 'メインクエスト＜<QCND 0>＞をクリア'
new = 'Clear Main Quest "<QCND 0>"'
[[message]]
key = 'ORDER_CONDITION_999'
old = 'パーソナルクエスト＜<QCND 0>＞をクリア'
new = 'Clear Personal Quest "<QCND 0>"'
[[message]]
key = 'ORDER_CONDITION_1000'
old = 'エクストリームミッション＜<QCND 0>＞をクリア'
new = 'Clear Extreme Mission "<QCND 0>"'
[[message]]
key = 'ORDER_CONDITION_993'
old = '<QCND 0>のエリアランク<QCND 1>以上'
new = 'Area rank for <QCND 0> at least <QCND 1>'
[[message]]
key = 'ORDER_CONDITION_1003'
old = 'パーティープレイ不可（ポーン同行可）'
new = 'No party members (pawns allowed)'
[[message]]
key = 'ORDER_CONDITION_1004'
old = '白竜神殿レンテンから覚者の戦術試練を学ぶ'
new = "Learn about the Arisen's tactics trial from Renton in the White Dragon Temple"
[[message]]
key = 'ORDER_CONDITION_1005'
old = 'イリスから十分な装備の準備方法について学ぶ'
new = 'Learn how to prepare adequate equipment from Iris'
[[message]]
key = 'ORDER_CONDITION_1007'
old = '無し'
new = 'None'
[[message]]
key = 'ORDER_CONDITION_1008'
old = 'パーティー内にパートナーポーンがいる'
new = 'Partner Pawn in party'
[[message]]
key = 'ORDER_CONDITION_1010'
old = '無し'
new = 'None'
[[message]]
key = 'ORDER_CONDITION_1011'
old = '装備のアイテムランクが<QCND 0>以上（平均IR）'
new = 'Item Rank of <QCND 0> or more (average IR)'
[[message]]
key = 'ORDER_CONDITION_1012'
old = 'アイテム＜<QCND 0>＞を<QCND 1>個所持'
[[message]]
key = 'ORDER_CONDITION_1014'
old = 'パーティプレイ不可（メインポーン<QCND 0>人同行可）'
new = 'No party members (<QCND 0> main pawn allowed)'
[[message]]
key = 'ORDER_CONDITION_1015'
old = 'ワールドクエスト＜<QCND 0>＞をクリア'
new = 'Clear World Quest "<QCND 0>"'
[[message]]
key = 'ORDER_CONDITION_1016'
old = 'サブストーリー＜<QCND 0>＞をクリア'
new = 'Clear Substory "<QCND 0>"'
[[message]]
key = 'ORDER_CONDITION_1017'
old = '現在のジョブのジョブレベル<QCND 0>以上'
new = 'Current Job Level <QCND 0> or more'
