[[message]]
key = 'RELEASE_CONTENT_1'
old = '他のプレイヤーとのパーティープレイ'
new = 'Party Play (With Other Players)'
[[message]]
key = 'RELEASE_CONTENT_2'
old = 'ポーンとのパーティープレイ'
new = 'Pawn and Party Play'
[[message]]
key = 'RELEASE_CONTENT_3'
old = 'ワールドクエスト'
new = 'World Quests'
[[message]]
key = 'RELEASE_CONTENT_5'
old = 'エクストリームミッション'
new = 'Extreme Missions'
[[message]]
key = 'RELEASE_CONTENT_6'
old = '着飾り装備'
new = 'Dress Equipment'
[[message]]
key = 'RELEASE_CONTENT_7'
old = 'レスタニアニュース'
new = 'Lestania News'
[[message]]
key = 'RELEASE_CONTENT_8'
old = 'ジョブ修練ログ'
new = 'Job Training Log'
[[message]]
key = 'RELEASE_CONTENT_9'
old = 'リム転移'
new = 'Rift Teleport'
[[message]]
key = 'RELEASE_CONTENT_10'
old = '竜力の継承'
new = 'Dragon Force Augmentation'
[[message]]
key = 'RELEASE_CONTENT_11'
old = 'クラフト'
new = 'Craft'
[[message]]
key = 'RELEASE_CONTENT_12'
old = 'リムストーン'
new = 'Riftstone'
[[message]]
key = 'RELEASE_CONTENT_13'
old = 'クエストボード'
new = 'Quest Board'
[[message]]
key = 'RELEASE_CONTENT_15'
old = 'エリアマスター'
new = 'Area Master'
[[message]]
key = 'RELEASE_CONTENT_16'
old = 'エリアマスターのワールドクエスト情報'
new = "Area Master's World Quest Info"
[[message]]
key = 'RELEASE_CONTENT_17'
old = 'ファイターのジョブ修練'
new = 'Fighter Job Training'
[[message]]
key = 'RELEASE_CONTENT_18'
old = 'ハンターのジョブ修練'
new = 'Hunter Job Training'
[[message]]
key = 'RELEASE_CONTENT_19'
old = 'プリーストのジョブ修練'
new = 'Priest Job Training'
[[message]]
key = 'RELEASE_CONTENT_20'
old = 'シールドセージのジョブ修練'
new = 'Shield Sage Job Training'
[[message]]
key = 'RELEASE_CONTENT_21'
old = 'シーカーのジョブ修練'
new = 'Seeker Job Training'
[[message]]
key = 'RELEASE_CONTENT_22'
old = 'ソーサラーのジョブ修練'
new = 'Sorcerer Job Training'
[[message]]
key = 'RELEASE_CONTENT_23'
old = 'ウォリアーのジョブ修練'
new = 'Warrior Job Training'
[[message]]
key = 'RELEASE_CONTENT_24'
old = 'エレメントアーチャーのジョブ修練'
new = 'Element Archer Job Training'
[[message]]
key = 'RELEASE_CONTENT_25'
old = 'アルケミストのジョブ修練'
new = 'Alchemist Job Training'
[[message]]
key = 'RELEASE_CONTENT_26'
old = '他のジョブへの転職'
new = 'Change Vocations'
[[message]]
key = 'RELEASE_CONTENT_27'
old = 'クランの設立と加入'
new = 'Create and Join Clans'
[[message]]
key = 'RELEASE_CONTENT_29'
old = '戦徒の契り'
new = "Myrmidon's Pledge"
[[message]]
key = 'RELEASE_CONTENT_32'
old = '冒険仲介係'
new = 'Adventure Broker'
[[message]]
key = 'RELEASE_CONTENT_33'
old = 'マッチングプロフィール'
new = 'Matching Profile'
[[message]]
key = 'RELEASE_CONTENT_34'
old = 'クイックパーティー'
new = 'Quick Party'
[[message]]
key = 'RELEASE_CONTENT_37'
old = '戦技の継承'
new = 'War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_38'
old = 'ファイターの戦技の継承'
new = 'Fighter War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_39'
old = 'ハンターの戦技の継承'
new = 'Hunter War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_40'
old = 'プリーストの戦技の継承'
new = 'Priest War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_41'
old = 'シールドセージの戦技の継承'
new = 'Shield Sage War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_42'
old = 'シーカーの戦技の継承'
new = 'Seeker War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_43'
old = 'ソーサラーの戦技の継承'
new = 'Sorcerer War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_44'
old = 'ウォリアーの戦技の継承'
new = 'Warrior War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_45'
old = 'エレメントアーチャーの戦技の継承'
new = 'Element Archer War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_46'
old = 'アルケミストの戦技の継承'
new = 'Alchemist War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_47'
old = '魔赤島ワールドクエスト'
new = 'Bloodbane Isle World Quests'
[[message]]
key = 'RELEASE_CONTENT_49'
old = 'マイルーム'
new = 'My Room'
[[message]]
key = 'RELEASE_CONTENT_51'
old = 'スピリットランサーのジョブ修練'
new = 'Spirit Lancer Job Training'
[[message]]
key = 'RELEASE_CONTENT_52'
old = 'スピリットランサーの戦技の継承'
new = 'Spirit Lancer War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_53'
old = 'モロー樹林ワールドクエスト'
new = 'Morrow Forest World Quests'
[[message]]
key = 'RELEASE_CONTENT_54'
old = 'エラン水林ワールドクエスト'
new = 'Elan Water Grove World Quests'
[[message]]
key = 'RELEASE_CONTENT_55'
old = 'ファーラナ平原ワールドクエスト'
new = 'Farana Plains World Quests'
[[message]]
key = 'RELEASE_CONTENT_56'
old = 'キンガル峡谷ワールドクエスト'
new = 'Kingal Canyon World Quests'
[[message]]
key = 'RELEASE_CONTENT_57'
old = 'プレイポイント'
new = 'Play Points'
[[message]]
key = 'RELEASE_CONTENT_58'
old = 'エリア目視調査'
new = 'Area Investigation'
[[message]]
key = 'RELEASE_CONTENT_59'
old = 'ポーン戦術育成'
new = 'Pawn Tactical Training'
[[message]]
key = 'RELEASE_CONTENT_60'
old = 'ファイターのジョブの証'
new = 'Fighter Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_61'
old = 'プリーストのジョブの証'
new = 'Priest Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_62'
old = 'ハンターのジョブの証'
new = 'Hunter Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_63'
old = 'シールドセージのジョブの証'
new = 'Shield Sage Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_64'
old = 'シーカーのジョブの証'
new = 'Seeker Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_65'
old = 'ソーサラーのジョブの証'
new = 'Sorcerer Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_66'
old = 'エレメントアーチャーのジョブの証'
new = 'Element Archer Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_67'
old = 'ウォリアーのジョブの証'
new = 'Warrior Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_68'
old = 'アルケミストのジョブの証'
new = 'Alchemist Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_69'
old = 'スピリットランサーのジョブの証'
new = 'Spirit Lancer Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_70'
old = 'ラスニテ山麓ワールドクエスト'
new = 'Rathnite Foothills World Quests'
[[message]]
key = 'RELEASE_CONTENT_71'
old = 'フェルヤナ荒原ワールドクエスト'
new = 'Feryana Wilderness World Quests'
[[message]]
key = 'RELEASE_CONTENT_72'
old = 'マンドラゴラ育成'
new = 'Mandragora Breeding'
[[message]]
key = 'RELEASE_CONTENT_73'
old = '絶技の継承'
new = 'Special Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_74'
old = '自室のテラス'
new = "Your Room's Terrace"
[[message]]
key = 'RELEASE_CONTENT_75'
old = '王家の協力者'
new = 'Cooperators of the Royal Family'
[[message]]
key = 'RELEASE_CONTENT_76'
old = 'ハイセプターのジョブ修練'
new = 'High Scepter Job Training'
[[message]]
key = 'RELEASE_CONTENT_77'
old = 'メガドシス高地ワールドクエスト'
new = 'Megadosys Plateau World Quests'
[[message]]
key = 'RELEASE_CONTENT_78'
old = 'ハイセプターのジョブの証'
new = 'High Scepter Vocation Emblem'
[[message]]
key = 'RELEASE_CONTENT_79'
old = 'ハイセプターへの転職'
new = 'Change to High Scepter'
[[message]]
key = 'RELEASE_CONTENT_80'
old = 'ポーンの新特技'
new = "Pawn's New Special Skills"
[[message]]
key = 'RELEASE_CONTENT_81'
old = 'ハイセプターの戦技の継承'
new = 'High Scepter War Skill Augmentation'
[[message]]
key = 'RELEASE_CONTENT_84'
old = 'ウルテカ山岳ワールドクエスト'
new = 'Urteca Mountains World Quests'
[[message]]
key = 'RELEASE_CONTENT_86'
old = 'ワイルドハント'
new = 'Wild Hunt'
[[message]]
key = 'RELEASE_CONTENT_87'
old = '竜武具の分解'
new = 'Dismantling of Dragon Arms'
[[message]]
key = 'RELEASE_CONTENT_88'
old = 'ドラゴンアビリティの合成'
new = 'Synthesis of Dragon Abilities'
[[message]]
key = 'RELEASE_CONTENT_89'
old = 'エクストリームミッション「黒界の門番」'
new = 'Extreme Mission "黒界の門番"'
[[message]]
key = 'RELEASE_CONTENT_90'
old = 'エクストリームミッション「狂宴に舞う蒼影」'
new = 'Extreme Mission "狂宴に舞う蒼影"'
[[message]]
key = 'RELEASE_CONTENT_91'
old = 'エクストリームミッション「黒き闇の覚者」'
new = 'Extreme Mission "黒き闇の覚者"'
[[message]]
key = 'RELEASE_CONTENT_92'
old = 'エクストリームミッション「理を破壊する者」'
new = 'Extreme Mission "理を破壊する者"'
[[message]]
key = 'RELEASE_CONTENT_93'
old = '竜防具の鑑定交換'
new = 'Appraisal Exchange of Dragon Armor'
