default_format = {proper = false}
[[message]]
key = 'SPOT_NAME_'
old = 'ウルテカ山岳 西部'
new = 'Western Urteca Mountains'
[[message]]
key = 'SPOT_NAME_'
old = 'ウルテカ山岳 北部'
new = 'Northern Urteca Mountains'
[[message]]
key = 'SPOT_NAME_'
old = 'ウルテカ山岳 東部'
new = 'Eastern Urteca Mountains'
[[message]]
key = 'SPOT_NAME_'
old = 'ウルテカの記憶'
new = 'Memory of Urteca'
[message.format]
proper = true
[[message]]
key = 'SPOT_NAME_'
old = '北の盗賊のアジト'
new = 'Northern Bandit Hideout'
[[message]]
key = 'SPOT_NAME_'
old = '火垂れ山野営地'
new = 'Firefall Mountain Campsite'
[[message]]
key = 'SPOT_NAME_'
old = 'サラマンダーコロニー'
new = 'Pyre Saurian Colony'
[[message]]
key = 'SPOT_NAME_'
old = '空望広場'
[[message]]
key = 'SPOT_NAME_'
old = '静かな抗戦跡'
[[message]]
key = 'SPOT_NAME_'
old = '痛刻の洞'
[[message]]
key = 'SPOT_NAME_'
old = '原初の集落'
[[message]]
key = 'SPOT_NAME_'
old = '建設資材集積場'
[[message]]
key = 'SPOT_NAME_'
old = '原種の縄張り'
[[message]]
key = 'SPOT_NAME_'
old = '還れぬ炎の吹き溜まり'
[[message]]
key = 'SPOT_NAME_'
old = 'メガド離宮'
new = 'Megado Detached Palace'
[[message]]
key = 'SPOT_NAME_'
old = '王家の墓'
new = 'The Royal Family Mausoleum'
[message.format]
new = 'Royal Family Mausoleum'
[[message]]
key = 'SPOT_NAME_'
old = '憩いの坑洞'
[[message]]
key = 'SPOT_NAME_'
old = '崩れた進入路'
new = 'Crumbling Entrance Path'
[[message]]
key = 'SPOT_NAME_'
old = '火垂れ山拝竜院'
new = 'Firefall Mountain Dragon Temple'
[[message]]
key = 'SPOT_NAME_'
old = '聖炎の参竜道'
[[message]]
key = 'SPOT_NAME_'
old = '魔角の間'
[[message]]
key = 'SPOT_NAME_'
old = '悼まれぬ者の葬室'
